/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Reclamation_client (void);
GtkWidget* create_Creer (void);
GtkWidget* create_consulter (void);
GtkWidget* create_employe (void);
GtkWidget* create_principal1 (void);
GtkWidget* create_modifier (void);
GtkWidget* create_reponse (void);
























void
on_nbbutton6_clicked                   (GtkWidget       *objet,
                                        gpointer         user_data);

void
on_nbbutton7_clicked                   (GtkWidget       *objet,
                                        gpointer         user_data);

void
on_nbbutton8_clicked                   (GtkWidget       *objet,
                                        gpointer         user_data);

void
on_nbbutton9_clicked                   (GtkWidget       *objet,
                                        gpointer         user_data);

void
on_nbbutton11_clicked                  (GtkWidget       *objet,
                                        gpointer         user_data);

void
on_nbbutton12_clicked                  (GtkWidget       *objet,
                                        gpointer         user_data);

void
on_nbbutton4_clicked                   (GtkWidget       *objet,
                                        gpointer         user_data);

void
on_nbbutton3_clicked                   (GtkWidget       *objet,
                                        gpointer         user_data);

void
on_nbbutton5_clicked                   (GtkWidget       *objet,
                                        gpointer         user_data);

void
on_nbbutton13_clicked                  (GtkWidget       *objet,
                                        gpointer         user_data);

void
on_nbbutton14_clicked                  (GtkWidget       *objet,
                                        gpointer         user_data);

void
on_nbbutton15_clicked                  (GtkWidget       *objet,
                                        gpointer         user_data);

void
on_nbbutton20_clicked                  (GtkWidget       *objet,
                                        gpointer         user_data);

void
on_nbbutton10_clicked                  (GtkWidget       *objet,
                                        gpointer         user_data);

void
on_nbbutton10_clicked                  (GtkWidget       *objet,
                                        gpointer         user_data);

void
on_nbbutton2_clicked                   (GtkWidget       *objet,
                                        gpointer         user_data);

void
on_nbbutton1_clicked                   (GtkWidget       *objet,
                                        gpointer         user_data);
