/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interfaceadmin.h"
#include "support.h"
#include "supporta.h"
#include "employers.h"
#include "fonction.h"
#include "fonctions.h"
#include "interface.h"
#include "interfacev.h"
#include "gest.h"
#include "interfacere.h"
#include "interfacehe.h"
#include "gestionhotel.h"
#include "interfacen.h"
#include "reclamation.h"



#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

/*GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *image16;
  GtkWidget *connexion;
  GtkWidget *inscription;
  GtkWidget *button3;
  GtkWidget *annuler;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label2;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);
  gtk_container_set_border_width (GTK_CONTAINER (fixed1), 45);

  image16 = create_pixmap (window1, "78851190_448531609193543_2003673050414841856_n.jpg");
  gtk_widget_show (image16);
  gtk_fixed_put (GTK_FIXED (fixed1), image16, 0, 0);
  gtk_widget_set_size_request (image16, 379, 395);

  connexion = gtk_button_new_with_mnemonic (_("connexion"));
  gtk_widget_show (connexion);
  gtk_fixed_put (GTK_FIXED (fixed1), connexion, 144, 56);
  gtk_widget_set_size_request (connexion, 120, 32);

  inscription = gtk_button_new_with_mnemonic (_("inscription"));
  gtk_widget_show (inscription);
  gtk_fixed_put (GTK_FIXED (fixed1), inscription, 144, 128);
  gtk_widget_set_size_request (inscription, 112, 29);

  button3 = gtk_button_new_with_mnemonic (_("catalogue"));
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed1), button3, 136, 280);
  gtk_widget_set_size_request (button3, 104, 29);

  annuler = gtk_button_new ();
  gtk_widget_show (annuler);
  gtk_fixed_put (GTK_FIXED (fixed1), annuler, 272, 328);
  gtk_widget_set_size_request (annuler, 96, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (annuler), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("annuler"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox1), label2, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) connexion, "clicked",
                    G_CALLBACK (on_connexion_clicked),
                    NULL);
  g_signal_connect ((gpointer) inscription, "clicked",
                    G_CALLBACK (on_inscription_clicked),
                    NULL);
  g_signal_connect ((gpointer) annuler, "clicked",
                    G_CALLBACK (on_annuler_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  /*GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, image16, "image16");
  GLADE_HOOKUP_OBJECT (window1, connexion, "connexion");
  GLADE_HOOKUP_OBJECT (window1, inscription, "inscription");
  GLADE_HOOKUP_OBJECT (window1, button3, "button3");
  GLADE_HOOKUP_OBJECT (window1, annuler, "annuler");
  GLADE_HOOKUP_OBJECT (window1, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1, image1, "image1");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");

  return window1;
}*/

/*GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed2;
  GtkWidget *entryuser;
  GtkWidget *entrypass;
  GtkWidget *image15;
  GtkWidget *labeluser;
  GtkWidget *password;
  GtkWidget *button;
  GtkWidget *label58;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window2), fixed2);
  gtk_container_set_border_width (GTK_CONTAINER (fixed2), 23);

  entryuser = gtk_entry_new ();
  gtk_widget_show (entryuser);
  gtk_fixed_put (GTK_FIXED (fixed2), entryuser, 176, 144);
  gtk_widget_set_size_request (entryuser, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryuser), 8226);

  entrypass = gtk_entry_new ();
  gtk_widget_show (entrypass);
  gtk_fixed_put (GTK_FIXED (fixed2), entrypass, 168, 216);
  gtk_widget_set_size_request (entrypass, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (entrypass), FALSE);

  image15 = create_pixmap (window2, "79164570_1469691083191220_6591764142015643648_n.jpg");
  gtk_widget_show (image15);
  gtk_fixed_put (GTK_FIXED (fixed2), image15, 0, 0);
  gtk_widget_set_size_request (image15, 497, 545);
  gtk_misc_set_alignment (GTK_MISC (image15), 0.88, 0.47);

  labeluser = gtk_label_new (_("<span font_desc=\"pursia\" foreground  =\"black\" size=\"small\"><b>user:</b></span>\n"));
  gtk_widget_show (labeluser);
  gtk_fixed_put (GTK_FIXED (fixed2), labeluser, 112, 144);
  gtk_widget_set_size_request (labeluser, 41, 17);
  gtk_label_set_use_markup (GTK_LABEL (labeluser), TRUE);

  password = gtk_label_new (_("<span font_desc=\"pursia\" foreground  =\"black\" size=\"small\"><b>password:</b></span>\n"));
  gtk_widget_show (password);
  gtk_fixed_put (GTK_FIXED (fixed2), password, 48, 216);
  gtk_widget_set_size_request (password, 104, 17);
  gtk_label_set_use_markup (GTK_LABEL (password), TRUE);

  button = gtk_button_new_with_mnemonic (_("login"));
  gtk_widget_show (button);
  gtk_fixed_put (GTK_FIXED (fixed2), button, 144, 336);
  gtk_widget_set_size_request (button, 136, 48);

  label58 = gtk_label_new (_("<span font_desc=\"pursia\" foreground  =\"black\" size=\"small\"><b></b></span>\n"));
  gtk_widget_show (label58);
  gtk_fixed_put (GTK_FIXED (fixed2), label58, 128, 288);
  gtk_widget_set_size_request (label58, 190, 19);
  gtk_label_set_use_markup (GTK_LABEL (label58), TRUE);

  g_signal_connect ((gpointer) button, "clicked",
                    G_CALLBACK (on_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  /*GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window2, entryuser, "entryuser");
  GLADE_HOOKUP_OBJECT (window2, entrypass, "entrypass");
  GLADE_HOOKUP_OBJECT (window2, image15, "image15");
  GLADE_HOOKUP_OBJECT (window2, labeluser, "labeluser");
  GLADE_HOOKUP_OBJECT (window2, password, "password");
  GLADE_HOOKUP_OBJECT (window2, button, "button");
  GLADE_HOOKUP_OBJECT (window2, label58, "label58");

  return window2;
}*/

/*GtkWidget*
create_window3 (void)
{
  GtkWidget *window3;
  GtkWidget *fixed4;
  GtkWidget *identifiant;
  GtkWidget *mot_de_passe;
  GtkWidget *nom;
  GtkWidget *tel;
  GtkWidget *email;
  GtkWidget *adresse;
  GtkWidget *prenom;
  GtkWidget *ii;
  GtkWidget *mot_;
  GtkWidget *n;
  GtkWidget *ajout;
  GtkWidget *adres;
  GtkWidget *ema;
  GtkWidget *pr;
  GtkObject *jour_adj;
  GtkWidget *jour;
  GtkObject *mois_adj;
  GtkWidget *mois;
  GtkObject *annee_adj;
  GtkWidget *annee;
  GtkWidget *label20;
  GtkWidget *label23;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkWidget *se;
  GtkWidget *erreur3;
  GtkWidget *erreur4;
  GtkWidget *erreur5;
  GtkWidget *erreur6;
  GtkWidget *erreur7;
  GtkWidget *te;
  GtkWidget *sexe;
  GtkWidget *image17;
  GtkWidget *erreur1;
  GtkWidget *erreur2;
  GtkWidget *supprimer;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label24;
  GtkWidget *modifier;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label25;
  GtkWidget *image13;
  GtkWidget *ajouter;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image18;
  GtkWidget *label55;
  GtkWidget *afficher;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label17;
  GtkWidget *sortie;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image19;
  GtkWidget *label59;

  window3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window3), _("window3"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (window3), fixed4);
  gtk_container_set_border_width (GTK_CONTAINER (fixed4), 9);

  identifiant = gtk_entry_new ();
  gtk_widget_show (identifiant);
  gtk_fixed_put (GTK_FIXED (fixed4), identifiant, 168, 56);
  gtk_widget_set_size_request (identifiant, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (identifiant), 8226);

  mot_de_passe = gtk_entry_new ();
  gtk_widget_show (mot_de_passe);
  gtk_fixed_put (GTK_FIXED (fixed4), mot_de_passe, 168, 88);
  gtk_widget_set_size_request (mot_de_passe, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (mot_de_passe), 8226);

  nom = gtk_entry_new ();
  gtk_widget_show (nom);
  gtk_fixed_put (GTK_FIXED (fixed4), nom, 168, 128);
  gtk_widget_set_size_request (nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom), 8226);

  tel = gtk_entry_new ();
  gtk_widget_show (tel);
  gtk_fixed_put (GTK_FIXED (fixed4), tel, 160, 336);
  gtk_widget_set_size_request (tel, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (tel), 8226);

  email = gtk_entry_new ();
  gtk_widget_show (email);
  gtk_fixed_put (GTK_FIXED (fixed4), email, 160, 376);
  gtk_widget_set_size_request (email, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (email), 8226);

  adresse = gtk_entry_new ();
  gtk_widget_show (adresse);
  gtk_fixed_put (GTK_FIXED (fixed4), adresse, 160, 416);
  gtk_widget_set_size_request (adresse, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (adresse), 8226);

  prenom = gtk_entry_new ();
  gtk_widget_show (prenom);
  gtk_fixed_put (GTK_FIXED (fixed4), prenom, 168, 168);
  gtk_widget_set_size_request (prenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenom), 8226);

  ii = gtk_label_new (_("identifiant"));
  gtk_widget_show (ii);
  gtk_fixed_put (GTK_FIXED (fixed4), ii, 48, 64);
  gtk_widget_set_size_request (ii, 104, 17);

  mot_ = gtk_label_new (_("mot de passe"));
  gtk_widget_show (mot_);
  gtk_fixed_put (GTK_FIXED (fixed4), mot_, 48, 96);
  gtk_widget_set_size_request (mot_, 104, 17);

  n = gtk_label_new (_("nom"));
  gtk_widget_show (n);
  gtk_fixed_put (GTK_FIXED (fixed4), n, 72, 128);
  gtk_widget_set_size_request (n, 41, 17);

  ajout = gtk_label_new (_("ajouter d'employer"));
  gtk_widget_show (ajout);
  gtk_fixed_put (GTK_FIXED (fixed4), ajout, 120, 16);
  gtk_widget_set_size_request (ajout, 160, 16);

  adres = gtk_label_new (_("adresse"));
  gtk_widget_show (adres);
  gtk_fixed_put (GTK_FIXED (fixed4), adres, 40, 424);
  gtk_widget_set_size_request (adres, 96, 16);

  ema = gtk_label_new (_("email"));
  gtk_widget_show (ema);
  gtk_fixed_put (GTK_FIXED (fixed4), ema, 56, 384);
  gtk_widget_set_size_request (ema, 49, 17);

  pr = gtk_label_new (_("prenom"));
  gtk_widget_show (pr);
  gtk_fixed_put (GTK_FIXED (fixed4), pr, 56, 176);
  gtk_widget_set_size_request (pr, 72, 17);

  jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jour = gtk_spin_button_new (GTK_ADJUSTMENT (jour_adj), 1, 0);
  gtk_widget_show (jour);
  gtk_fixed_put (GTK_FIXED (fixed4), jour, 184, 264);
  gtk_widget_set_size_request (jour, 60, 27);

  mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  mois = gtk_spin_button_new (GTK_ADJUSTMENT (mois_adj), 1, 0);
  gtk_widget_show (mois);
  gtk_fixed_put (GTK_FIXED (fixed4), mois, 296, 264);
  gtk_widget_set_size_request (mois, 60, 27);

  annee_adj = gtk_adjustment_new (1, 1990, 2020, 1, 10, 10);
  annee = gtk_spin_button_new (GTK_ADJUSTMENT (annee_adj), 1, 0);
  gtk_widget_show (annee);
  gtk_fixed_put (GTK_FIXED (fixed4), annee, 408, 264);
  gtk_widget_set_size_request (annee, 60, 27);

  label20 = gtk_label_new (_("date de naissance"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed4), label20, 8, 272);
  gtk_widget_set_size_request (label20, 152, 17);

  label23 = gtk_label_new (_("annee"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed4), label23, 400, 248);
  gtk_widget_set_size_request (label23, 49, 17);

  label21 = gtk_label_new (_("jour"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed4), label21, 184, 248);
  gtk_widget_set_size_request (label21, 49, 17);

  label22 = gtk_label_new (_("mois"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed4), label22, 304, 248);
  gtk_widget_set_size_request (label22, 49, 17);

  se = gtk_label_new (_("sexe"));
  gtk_widget_show (se);
  gtk_fixed_put (GTK_FIXED (fixed4), se, 64, 216);
  gtk_widget_set_size_request (se, 49, 17);

  erreur3 = gtk_label_new ("");
  gtk_widget_show (erreur3);
  gtk_fixed_put (GTK_FIXED (fixed4), erreur3, 336, 128);
  gtk_widget_set_size_request (erreur3, 175, 20);

  erreur4 = gtk_label_new ("");
  gtk_widget_show (erreur4);
  gtk_fixed_put (GTK_FIXED (fixed4), erreur4, 344, 176);
  gtk_widget_set_size_request (erreur4, 159, 19);

  erreur5 = gtk_label_new ("");
  gtk_widget_show (erreur5);
  gtk_fixed_put (GTK_FIXED (fixed4), erreur5, 352, 336);
  gtk_widget_set_size_request (erreur5, 167, 20);

  erreur6 = gtk_label_new ("");
  gtk_widget_show (erreur6);
  gtk_fixed_put (GTK_FIXED (fixed4), erreur6, 336, 384);
  gtk_widget_set_size_request (erreur6, 143, 22);

  erreur7 = gtk_label_new ("");
  gtk_widget_show (erreur7);
  gtk_fixed_put (GTK_FIXED (fixed4), erreur7, 344, 424);
  gtk_widget_set_size_request (erreur7, 143, 19);

  te = gtk_label_new (_("tel"));
  gtk_widget_show (te);
  gtk_fixed_put (GTK_FIXED (fixed4), te, 64, 336);
  gtk_widget_set_size_request (te, 49, 17);

  sexe = gtk_combo_box_entry_new_text ();
  gtk_widget_show (sexe);
  gtk_fixed_put (GTK_FIXED (fixed4), sexe, 152, 208);
  gtk_widget_set_size_request (sexe, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (sexe), _("homme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (sexe), _("femme"));

  image17 = create_pixmap (window3, "78312768_1528947837255762_1653044732256845824_n.jpg");
  gtk_widget_show (image17);
  gtk_fixed_put (GTK_FIXED (fixed4), image17, 81, 488);
  gtk_widget_set_size_request (image17, 583, 70);
  gtk_misc_set_alignment (GTK_MISC (image17), 0, 0.34);

  erreur1 = gtk_label_new ("");
  gtk_widget_show (erreur1);
  gtk_fixed_put (GTK_FIXED (fixed4), erreur1, 336, 56);
  gtk_widget_set_size_request (erreur1, 183, 24);

  erreur2 = gtk_label_new ("");
  gtk_widget_show (erreur2);
  gtk_fixed_put (GTK_FIXED (fixed4), erreur2, 352, 88);
  gtk_widget_set_size_request (erreur2, 167, 22);

  supprimer = gtk_button_new ();
  gtk_widget_show (supprimer);
  gtk_fixed_put (GTK_FIXED (fixed4), supprimer, 568, 392);
  gtk_widget_set_size_request (supprimer, 120, 30);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (supprimer), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox5), label24, FALSE, FALSE, 0);

  modifier = gtk_button_new ();
  gtk_widget_show (modifier);
  gtk_fixed_put (GTK_FIXED (fixed4), modifier, 568, 456);
  gtk_widget_set_size_request (modifier, 120, 30);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (modifier), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-new", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox6), label25, FALSE, FALSE, 0);

  image13 = create_pixmap (window3, "pngtree-business-male-icon-vector-png-image_916468.jpg");
  gtk_widget_show (image13);
  gtk_fixed_put (GTK_FIXED (fixed4), image13, 520, 64);
  gtk_widget_set_size_request (image13, 158, 193);

  ajouter = gtk_button_new ();
  gtk_widget_show (ajouter);
  gtk_fixed_put (GTK_FIXED (fixed4), ajouter, 552, 272);
  gtk_widget_set_size_request (ajouter, 104, 37);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (ajouter), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image18 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox12), image18, FALSE, FALSE, 0);

  label55 = gtk_label_new_with_mnemonic (_("cree"));
  gtk_widget_show (label55);
  gtk_box_pack_start (GTK_BOX (hbox12), label55, FALSE, FALSE, 0);

  afficher = gtk_button_new ();
  gtk_widget_show (afficher);
  gtk_fixed_put (GTK_FIXED (fixed4), afficher, 568, 424);
  gtk_widget_set_size_request (afficher, 120, 30);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (afficher), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-goto-bottom", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("afficher"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox3), label17, FALSE, FALSE, 0);

  sortie = gtk_button_new ();
  gtk_widget_show (sortie);
  gtk_fixed_put (GTK_FIXED (fixed4), sortie, 552, 8);
  gtk_widget_set_size_request (sortie, 129, 32);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (sortie), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image19 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox13), image19, FALSE, FALSE, 0);

  label59 = gtk_label_new_with_mnemonic (_("deconnexion"));
  gtk_widget_show (label59);
  gtk_box_pack_start (GTK_BOX (hbox13), label59, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) supprimer, "clicked",
                    G_CALLBACK (on_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier, "clicked",
                    G_CALLBACK (on_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter, "clicked",
                    G_CALLBACK (on_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficher, "clicked",
                    G_CALLBACK (on_afficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) sortie, "clicked",
                    G_CALLBACK (on_sortie_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  /*GLADE_HOOKUP_OBJECT_NO_REF (window3, window3, "window3");
  GLADE_HOOKUP_OBJECT (window3, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window3, identifiant, "identifiant");
  GLADE_HOOKUP_OBJECT (window3, mot_de_passe, "mot_de_passe");
  GLADE_HOOKUP_OBJECT (window3, nom, "nom");
  GLADE_HOOKUP_OBJECT (window3, tel, "tel");
  GLADE_HOOKUP_OBJECT (window3, email, "email");
  GLADE_HOOKUP_OBJECT (window3, adresse, "adresse");
  GLADE_HOOKUP_OBJECT (window3, prenom, "prenom");
  GLADE_HOOKUP_OBJECT (window3, ii, "ii");
  GLADE_HOOKUP_OBJECT (window3, mot_, "mot_");
  GLADE_HOOKUP_OBJECT (window3, n, "n");
  GLADE_HOOKUP_OBJECT (window3, ajout, "ajout");
  GLADE_HOOKUP_OBJECT (window3, adres, "adres");
  GLADE_HOOKUP_OBJECT (window3, ema, "ema");
  GLADE_HOOKUP_OBJECT (window3, pr, "pr");
  GLADE_HOOKUP_OBJECT (window3, jour, "jour");
  GLADE_HOOKUP_OBJECT (window3, mois, "mois");
  GLADE_HOOKUP_OBJECT (window3, annee, "annee");
  GLADE_HOOKUP_OBJECT (window3, label20, "label20");
  GLADE_HOOKUP_OBJECT (window3, label23, "label23");
  GLADE_HOOKUP_OBJECT (window3, label21, "label21");
  GLADE_HOOKUP_OBJECT (window3, label22, "label22");
  GLADE_HOOKUP_OBJECT (window3, se, "se");
  GLADE_HOOKUP_OBJECT (window3, erreur3, "erreur3");
  GLADE_HOOKUP_OBJECT (window3, erreur4, "erreur4");
  GLADE_HOOKUP_OBJECT (window3, erreur5, "erreur5");
  GLADE_HOOKUP_OBJECT (window3, erreur6, "erreur6");
  GLADE_HOOKUP_OBJECT (window3, erreur7, "erreur7");
  GLADE_HOOKUP_OBJECT (window3, te, "te");
  GLADE_HOOKUP_OBJECT (window3, sexe, "sexe");
  GLADE_HOOKUP_OBJECT (window3, image17, "image17");
  GLADE_HOOKUP_OBJECT (window3, erreur1, "erreur1");
  GLADE_HOOKUP_OBJECT (window3, erreur2, "erreur2");
  GLADE_HOOKUP_OBJECT (window3, supprimer, "supprimer");
  GLADE_HOOKUP_OBJECT (window3, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window3, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window3, image5, "image5");
  GLADE_HOOKUP_OBJECT (window3, label24, "label24");
  GLADE_HOOKUP_OBJECT (window3, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (window3, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window3, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window3, image6, "image6");
  GLADE_HOOKUP_OBJECT (window3, label25, "label25");
  GLADE_HOOKUP_OBJECT (window3, image13, "image13");
  GLADE_HOOKUP_OBJECT (window3, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (window3, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window3, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window3, image18, "image18");
  GLADE_HOOKUP_OBJECT (window3, label55, "label55");
  GLADE_HOOKUP_OBJECT (window3, afficher, "afficher");
  GLADE_HOOKUP_OBJECT (window3, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window3, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window3, image3, "image3");
  GLADE_HOOKUP_OBJECT (window3, label17, "label17");
  GLADE_HOOKUP_OBJECT (window3, sortie, "sortie");
  GLADE_HOOKUP_OBJECT (window3, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (window3, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window3, image19, "image19");
  GLADE_HOOKUP_OBJECT (window3, label59, "label59");

  return window3;
}*/

/*GtkWidget*
create_window4 (void)
{
  GtkWidget *window4;
  GtkWidget *fixed5;
  GtkWidget *treeview1;
  GtkWidget *image14;
  GtkWidget *retour;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label19;
  GtkWidget *label18;
  GtkWidget *calendar1;

  window4 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window4), _("window4"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (window4), fixed5);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed5), treeview1, 168, 48);
  gtk_widget_set_size_request (treeview1, 816, 160);

  image14 = create_pixmap (window4, "79029384_2091505294286380_3080564618746134528_n.jpg");
  gtk_widget_show (image14);
  gtk_fixed_put (GTK_FIXED (fixed5), image14, 0, 2);
  gtk_widget_set_size_request (image14, 1040, 384);
  gtk_misc_set_alignment (GTK_MISC (image14), 0.6, 0.23);
  gtk_misc_set_padding (GTK_MISC (image14), 235, 0);

  retour = gtk_button_new ();
  gtk_widget_show (retour);
  gtk_fixed_put (GTK_FIXED (fixed5), retour, 664, 336);
  gtk_widget_set_size_request (retour, 128, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (retour), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox4), label19, FALSE, FALSE, 0);

  label18 = gtk_label_new (_("liste des employers"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed5), label18, 384, 24);
  gtk_widget_set_size_request (label18, 168, 17);

  calendar1 = gtk_calendar_new ();
  gtk_widget_show (calendar1);
  gtk_fixed_put (GTK_FIXED (fixed5), calendar1, 8, 216);
  gtk_widget_set_size_request (calendar1, 192, 160);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  g_signal_connect ((gpointer) retour, "clicked",
                    G_CALLBACK (on_retour_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  /*GLADE_HOOKUP_OBJECT_NO_REF (window4, window4, "window4");
  GLADE_HOOKUP_OBJECT (window4, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window4, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (window4, image14, "image14");
  GLADE_HOOKUP_OBJECT (window4, retour, "retour");
  GLADE_HOOKUP_OBJECT (window4, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window4, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window4, image4, "image4");
  GLADE_HOOKUP_OBJECT (window4, label19, "label19");
  GLADE_HOOKUP_OBJECT (window4, label18, "label18");
  GLADE_HOOKUP_OBJECT (window4, calendar1, "calendar1");

  return window4;
}

GtkWidget*
create_window5 (void)
{
  GtkWidget *window5;
  GtkWidget *fixed6;
  GtkWidget *nid;
  GtkWidget *nmot_de_passe;
  GtkWidget *nnom;
  GtkWidget *ntel;
  GtkWidget *nemail;
  GtkWidget *nadresse;
  GtkWidget *nprenom;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkWidget *label32;
  GtkWidget *label33;
  GtkObject *njour_adj;
  GtkWidget *njour;
  GtkObject *nmois_adj;
  GtkWidget *nmois;
  GtkObject *nannee_adj;
  GtkWidget *nannee;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkWidget *label36;
  GtkWidget *label37;
  GtkWidget *label38;
  GtkWidget *id;
  GtkWidget *label29;
  GtkWidget *nsexe;
  GtkWidget *image12;
  GtkWidget *oui;
  GtkWidget *label50;
  GtkWidget *valider;
  GtkWidget *afficher;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label40;
  GtkWidget *modifierr;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label51;

  window5 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window5), _("window5"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (window5), fixed6);
  gtk_container_set_border_width (GTK_CONTAINER (fixed6), 9);

  nid = gtk_entry_new ();
  gtk_widget_show (nid);
  gtk_fixed_put (GTK_FIXED (fixed6), nid, 168, 56);
  gtk_widget_set_size_request (nid, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nid), 8226);

  nmot_de_passe = gtk_entry_new ();
  gtk_widget_show (nmot_de_passe);
  gtk_fixed_put (GTK_FIXED (fixed6), nmot_de_passe, 168, 88);
  gtk_widget_set_size_request (nmot_de_passe, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nmot_de_passe), 8226);

  nnom = gtk_entry_new ();
  gtk_widget_show (nnom);
  gtk_fixed_put (GTK_FIXED (fixed6), nnom, 168, 128);
  gtk_widget_set_size_request (nnom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nnom), 8226);

  ntel = gtk_entry_new ();
  gtk_widget_show (ntel);
  gtk_fixed_put (GTK_FIXED (fixed6), ntel, 160, 336);
  gtk_widget_set_size_request (ntel, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ntel), 8226);

  nemail = gtk_entry_new ();
  gtk_widget_show (nemail);
  gtk_fixed_put (GTK_FIXED (fixed6), nemail, 160, 376);
  gtk_widget_set_size_request (nemail, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nemail), 8226);

  nadresse = gtk_entry_new ();
  gtk_widget_show (nadresse);
  gtk_fixed_put (GTK_FIXED (fixed6), nadresse, 160, 416);
  gtk_widget_set_size_request (nadresse, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nadresse), 8226);

  nprenom = gtk_entry_new ();
  gtk_widget_show (nprenom);
  gtk_fixed_put (GTK_FIXED (fixed6), nprenom, 168, 168);
  gtk_widget_set_size_request (nprenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nprenom), 8226);

  label26 = gtk_label_new (_("identifiant"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed6), label26, 48, 64);
  gtk_widget_set_size_request (label26, 104, 17);

  label27 = gtk_label_new (_("mot de passe"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed6), label27, 48, 96);
  gtk_widget_set_size_request (label27, 104, 17);

  label28 = gtk_label_new (_("nom"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed6), label28, 72, 128);
  gtk_widget_set_size_request (label28, 41, 17);

  label30 = gtk_label_new (_("adresse"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed6), label30, 40, 424);
  gtk_widget_set_size_request (label30, 96, 16);

  label31 = gtk_label_new (_("email"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed6), label31, 56, 384);
  gtk_widget_set_size_request (label31, 49, 17);

  label32 = gtk_label_new (_("tel"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed6), label32, 64, 336);
  gtk_widget_set_size_request (label32, 49, 17);

  label33 = gtk_label_new (_("prenom"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed6), label33, 56, 176);
  gtk_widget_set_size_request (label33, 72, 17);

  njour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  njour = gtk_spin_button_new (GTK_ADJUSTMENT (njour_adj), 1, 0);
  gtk_widget_show (njour);
  gtk_fixed_put (GTK_FIXED (fixed6), njour, 184, 264);
  gtk_widget_set_size_request (njour, 60, 27);

  nmois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  nmois = gtk_spin_button_new (GTK_ADJUSTMENT (nmois_adj), 1, 0);
  gtk_widget_show (nmois);
  gtk_fixed_put (GTK_FIXED (fixed6), nmois, 296, 264);
  gtk_widget_set_size_request (nmois, 60, 27);

  nannee_adj = gtk_adjustment_new (1, 1990, 2020, 1, 10, 10);
  nannee = gtk_spin_button_new (GTK_ADJUSTMENT (nannee_adj), 1, 0);
  gtk_widget_show (nannee);
  gtk_fixed_put (GTK_FIXED (fixed6), nannee, 416, 272);
  gtk_widget_set_size_request (nannee, 60, 27);

  label34 = gtk_label_new (_("date de naissance"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed6), label34, 8, 272);
  gtk_widget_set_size_request (label34, 152, 17);

  label35 = gtk_label_new (_("annee"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed6), label35, 400, 248);
  gtk_widget_set_size_request (label35, 49, 17);

  label36 = gtk_label_new (_("jour"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed6), label36, 184, 248);
  gtk_widget_set_size_request (label36, 49, 17);

  label37 = gtk_label_new (_("mois"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed6), label37, 304, 248);
  gtk_widget_set_size_request (label37, 49, 17);

  label38 = gtk_label_new (_("sexe"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed6), label38, 64, 216);
  gtk_widget_set_size_request (label38, 49, 17);

  id = gtk_entry_new ();
  gtk_widget_show (id);
  gtk_fixed_put (GTK_FIXED (fixed6), id, 376, 8);
  gtk_widget_set_size_request (id, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (id), 8226);

  label29 = gtk_label_new (_("modifier d'employer"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed6), label29, 56, 8);
  gtk_widget_set_size_request (label29, 160, 16);

  nsexe = gtk_combo_box_entry_new_text ();
  gtk_widget_show (nsexe);
  gtk_fixed_put (GTK_FIXED (fixed6), nsexe, 152, 208);
  gtk_widget_set_size_request (nsexe, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (nsexe), _("homme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (nsexe), _("femme"));

  image12 = create_pixmap (window5, "pngtree-business-male-icon-vector-png-image_916468.jpg");
  gtk_widget_show (image12);
  gtk_fixed_put (GTK_FIXED (fixed6), image12, 497, 80);
  gtk_widget_set_size_request (image12, 183, 256);

  oui = gtk_label_new ("");
  gtk_widget_show (oui);
  gtk_fixed_put (GTK_FIXED (fixed6), oui, 320, 56);
  gtk_widget_set_size_request (oui, 185, 27);

  label50 = gtk_label_new (_("id rechercher"));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed6), label50, 280, 16);
  gtk_widget_set_size_request (label50, 95, 18);

  valider = gtk_button_new_with_mnemonic (_("valider"));
  gtk_widget_show (valider);
  gtk_fixed_put (GTK_FIXED (fixed6), valider, 464, 40);
  gtk_widget_set_size_request (valider, 74, 29);

  afficher = gtk_button_new ();
  gtk_widget_show (afficher);
  gtk_fixed_put (GTK_FIXED (fixed6), afficher, 512, 416);
  gtk_widget_set_size_request (afficher, 152, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (afficher), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-goto-bottom", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("afficher"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox8), label40, FALSE, FALSE, 0);

  modifierr = gtk_button_new ();
  gtk_widget_show (modifierr);
  gtk_fixed_put (GTK_FIXED (fixed6), modifierr, 528, 368);
  gtk_widget_set_size_request (modifierr, 104, 37);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (modifierr), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label51 = gtk_label_new_with_mnemonic (_("modifierr"));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox9), label51, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) valider, "clicked",
                    G_CALLBACK (on_valider_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficher, "clicked",
                    G_CALLBACK (on_afficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifierr, "clicked",
                    G_CALLBACK (on_modifierr_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  /*GLADE_HOOKUP_OBJECT_NO_REF (window5, window5, "window5");
  GLADE_HOOKUP_OBJECT (window5, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window5, nid, "nid");
  GLADE_HOOKUP_OBJECT (window5, nmot_de_passe, "nmot_de_passe");
  GLADE_HOOKUP_OBJECT (window5, nnom, "nnom");
  GLADE_HOOKUP_OBJECT (window5, ntel, "ntel");
  GLADE_HOOKUP_OBJECT (window5, nemail, "nemail");
  GLADE_HOOKUP_OBJECT (window5, nadresse, "nadresse");
  GLADE_HOOKUP_OBJECT (window5, nprenom, "nprenom");
  GLADE_HOOKUP_OBJECT (window5, label26, "label26");
  GLADE_HOOKUP_OBJECT (window5, label27, "label27");
  GLADE_HOOKUP_OBJECT (window5, label28, "label28");
  GLADE_HOOKUP_OBJECT (window5, label30, "label30");
  GLADE_HOOKUP_OBJECT (window5, label31, "label31");
  GLADE_HOOKUP_OBJECT (window5, label32, "label32");
  GLADE_HOOKUP_OBJECT (window5, label33, "label33");
  GLADE_HOOKUP_OBJECT (window5, njour, "njour");
  GLADE_HOOKUP_OBJECT (window5, nmois, "nmois");
  GLADE_HOOKUP_OBJECT (window5, nannee, "nannee");
  GLADE_HOOKUP_OBJECT (window5, label34, "label34");
  GLADE_HOOKUP_OBJECT (window5, label35, "label35");
  GLADE_HOOKUP_OBJECT (window5, label36, "label36");
  GLADE_HOOKUP_OBJECT (window5, label37, "label37");
  GLADE_HOOKUP_OBJECT (window5, label38, "label38");
  GLADE_HOOKUP_OBJECT (window5, id, "id");
  GLADE_HOOKUP_OBJECT (window5, label29, "label29");
  GLADE_HOOKUP_OBJECT (window5, nsexe, "nsexe");
  GLADE_HOOKUP_OBJECT (window5, image12, "image12");
  GLADE_HOOKUP_OBJECT (window5, oui, "oui");
  GLADE_HOOKUP_OBJECT (window5, label50, "label50");
  GLADE_HOOKUP_OBJECT (window5, valider, "valider");
  GLADE_HOOKUP_OBJECT (window5, afficher, "afficher");
  GLADE_HOOKUP_OBJECT (window5, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window5, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window5, image8, "image8");
  GLADE_HOOKUP_OBJECT (window5, label40, "label40");
  GLADE_HOOKUP_OBJECT (window5, modifierr, "modifierr");
  GLADE_HOOKUP_OBJECT (window5, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (window5, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (window5, image9, "image9");
  GLADE_HOOKUP_OBJECT (window5, label51, "label51");

  return window5;
}*/

/*GtkWidget*
create_window6 (void)
{
  GtkWidget *window6;
  GtkWidget *fixed7;
  GtkWidget *supp;
  GtkWidget *confirmer;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label53;
  GtkWidget *label52;
  GtkWidget *suppr;
  GtkWidget *debut;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label54;

  window6 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window6), _("window6"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (window6), fixed7);

  supp = gtk_entry_new ();
  gtk_widget_show (supp);
  gtk_fixed_put (GTK_FIXED (fixed7), supp, 96, 80);
  gtk_widget_set_size_request (supp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (supp), 8226);

  confirmer = gtk_button_new ();
  gtk_widget_show (confirmer);
  gtk_fixed_put (GTK_FIXED (fixed7), confirmer, 216, 184);
  gtk_widget_set_size_request (confirmer, 128, 29);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (confirmer), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label53 = gtk_label_new_with_mnemonic (_("appliquer"));
  gtk_widget_show (label53);
  gtk_box_pack_start (GTK_BOX (hbox10), label53, FALSE, FALSE, 0);

  label52 = gtk_label_new (_("id supprimer"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed7), label52, 112, 32);
  gtk_widget_set_size_request (label52, 112, 16);

  suppr = gtk_label_new ("");
  gtk_widget_show (suppr);
  gtk_fixed_put (GTK_FIXED (fixed7), suppr, 96, 136);
  gtk_widget_set_size_request (suppr, 177, 20);

  debut = gtk_button_new ();
  gtk_widget_show (debut);
  gtk_fixed_put (GTK_FIXED (fixed7), debut, 64, 184);
  gtk_widget_set_size_request (debut, 74, 29);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (debut), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-goto-first", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label54 = gtk_label_new_with_mnemonic (_("debut"));
  gtk_widget_show (label54);
  gtk_box_pack_start (GTK_BOX (hbox11), label54, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) confirmer, "clicked",
                    G_CALLBACK (on_confirmer_clicked),
                    NULL);
  g_signal_connect ((gpointer) debut, "clicked",
                    G_CALLBACK (on_debut_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  /*GLADE_HOOKUP_OBJECT_NO_REF (window6, window6, "window6");
  GLADE_HOOKUP_OBJECT (window6, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window6, supp, "supp");
  GLADE_HOOKUP_OBJECT (window6, confirmer, "confirmer");
  GLADE_HOOKUP_OBJECT (window6, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window6, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window6, image10, "image10");
  GLADE_HOOKUP_OBJECT (window6, label53, "label53");
  GLADE_HOOKUP_OBJECT (window6, label52, "label52");
  GLADE_HOOKUP_OBJECT (window6, suppr, "suppr");
  GLADE_HOOKUP_OBJECT (window6, debut, "debut");
  GLADE_HOOKUP_OBJECT (window6, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (window6, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window6, image11, "image11");
  GLADE_HOOKUP_OBJECT (window6, label54, "label54");

  return window6;
}*/






















void
on_annuler_clicked                     (GtkButton       *button,
                                        gpointer         user_data)
{
/*GtkWidget *window1,*window3;

window3=lookup_widget(objet,"window3");

gtk_widget_destroy(window3);
window1=create_window1(); */
}


void
on_connexion_clicked                   (GtkWidget       *objet_graphique,
                                        gpointer         user_data)
{

GtkWidget *window1,*window2;

window1=lookup_widget(objet_graphique,"window1");


window2=create_window2();
gtk_widget_show(window2);
gtk_widget_hide(window1);


}


void
on_inscription_clicked                 (GtkButton       *button,
                                        gpointer         user_data)
{

}



void
on_button_clicked                      (GtkWidget       *objet_graphique,
                                        gpointer         user_data)
{

int x;
char username[100];
char password[100];
char message[29]="Bienvenue Dans Votre Espace";
GtkWidget *window3;
GtkWidget *input1;
GtkWidget *input2;
GtkWidget *output1;
GtkWidget *output2;
input1=lookup_widget(objet_graphique,"entryuser");
input2=lookup_widget(objet_graphique,"entrypass");
output1=lookup_widget(objet_graphique,"labelespace");
output2=lookup_widget(objet_graphique,"labelerror");
strcpy(username,gtk_entry_get_text(GTK_ENTRY(input1)));
strcpy(password,gtk_entry_get_text(GTK_ENTRY(input2)));
x=verifier(username,password);
if (x!=-1)
{


GtkWidget *window2,*window3;

window2=lookup_widget(objet_graphique,"window2");


window3=create_window3();
gtk_widget_show(window3);
gtk_widget_hide(window2);



}
else
{
gtk_label_set_text(GTK_LABEL(output2),"mot de passe pu user name faut");
}
}


void
on_afficher_clicked                    (GtkWidget       *objet,
                                        gpointer         user_data)
{

GtkWidget *window3;
GtkWidget *window4;
GtkWidget *treeview1;

window4=lookup_widget(objet,"window3");

gtk_widget_destroy(window3);
window4=lookup_widget(objet,"window4");
window4=create_window4();

gtk_widget_show(window4);

treeview1=lookup_widget(window4,"treeview1");

afficher_personne(treeview1);
}


void
on_ajouter_clicked                     (GtkWidget       *objet,
                                        gpointer         user_data)
{
personne p;
GtkWidget *input1,*input2,*input3,*input4,*sexe,*jour,*mois,*annee,*input5,*input6,*input7;

GtkWidget *output1;
GtkWidget *output2;
GtkWidget *output3;
GtkWidget *output4;
GtkWidget *output5;
GtkWidget *output6;
GtkWidget *output7;
GtkWidget *output8;

char empty[]="\0";
GtkWidget *window3;

window3=lookup_widget(objet,"window3");

output8=lookup_widget(objet,"label556");
output7=lookup_widget(objet,"erreur7");
output6=lookup_widget(objet,"erreur6");
output5=lookup_widget(objet,"erreur5");
output4=lookup_widget(objet,"erreur4");
output3=lookup_widget(objet,"erreur3");
output2=lookup_widget(objet,"erreur2");
output1=lookup_widget(objet,"erreur1");
input1=lookup_widget(objet,"identifiant");
input2=lookup_widget(objet,"mot_de_passe");
input3=lookup_widget(objet,"nom");
input4=lookup_widget(objet,"prenom");
input5=lookup_widget(objet,"tel");
input6=lookup_widget(objet,"email");
input7=lookup_widget(objet,"adresse");
jour=lookup_widget(objet,"jour");
mois=lookup_widget(objet,"mois");
annee=lookup_widget(objet,"annee");
sexe=lookup_widget(objet,"sexe");


strcpy(p.identifiant,gtk_entry_get_text(GTK_ENTRY(input1)));
strcpy(p.mot_de_passe,gtk_entry_get_text(GTK_ENTRY(input2)));
strcpy(p.nom,gtk_entry_get_text(GTK_ENTRY(input3)));
strcpy(p.prenom,gtk_entry_get_text(GTK_ENTRY(input4)));
strcpy(p.sexe,gtk_combo_box_get_active_text(GTK_COMBO_BOX(sexe)));
p.jour=gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(jour));
p.mois=gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(mois));
p.annee=gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(annee));
strcpy(p.tel,gtk_entry_get_text(GTK_ENTRY(input5)));
strcpy(p.email,gtk_entry_get_text(GTK_ENTRY(input6)));
strcpy(p.adresse,gtk_entry_get_text(GTK_ENTRY(input7)));
if(strcmp(p.identifiant,empty)==0)
{
gtk_label_set_text(GTK_LABEL(output1),"est oblig de ecrire"); 
}
else if(strcmp(p.mot_de_passe,empty)==0)
{
gtk_label_set_text(GTK_LABEL(output2),"est oblig de ecrire");
}
else if(strcmp(p.nom,empty)==0)
{
gtk_label_set_text(GTK_LABEL(output3),"est oblig de ecrire");
}
else if(strcmp(p.prenom,empty)==0)
{
gtk_label_set_text(GTK_LABEL(output4),"est oblig de ecrire");
}
else if(strcmp(p.tel,empty)==0)
{
gtk_label_set_text(GTK_LABEL(output5),"est oblig de ecrire");
}
else if(strcmp(p.email,empty)==0)
{
gtk_label_set_text(GTK_LABEL(output6),"est oblig de ecrire");
}
else if(strcmp(p.adresse,empty)==0)
{
gtk_label_set_text(GTK_LABEL(output7),"est oblig de ecrire");
}
else
{
ajouter_personne(p);
role(p);
gtk_label_set_text(GTK_LABEL(output8),"employer est ajouter");
}
}


void
on_retour_clicked                      (GtkWidget       *objet,
                                        gpointer         user_data)
{

GtkWidget *window3,*window4;

window4=lookup_widget(objet,"window4");

gtk_widget_destroy(window4);
window3=create_window3();


}








void
on_supprimer_clicked                   (GtkWidget       *objet,
                                        gpointer         user_data)
{
GtkWidget *window3;
GtkWidget *window6;


window6=lookup_widget(objet,"window3");

gtk_widget_destroy(window3);
window6=lookup_widget(objet,"window6");
window6=create_window6();

gtk_widget_show(window6);

}


void
on_modifier_clicked                    (GtkWidget       *objet,
                                        gpointer         user_data)
{
GtkWidget *window3;
GtkWidget *window5;


window5=lookup_widget(objet,"window3");

gtk_widget_destroy(window3);
window5=lookup_widget(objet,"window5");
window5=create_window5();

gtk_widget_show(window5);


}


void
on_modifierr_clicked                   (GtkWidget       *objet,
                                        gpointer         user_data)
{
personne p;
GtkWidget *window5;
GtkWidget *input1,*input2,*input3,*input4,*sexe,*jour,*mois,*annee,*input5,*input6,*input7;
GtkWidget *output0;

window5=lookup_widget(objet,"window5");
char id [30];
char mdp[30];
char adresses[100];

output0=lookup_widget(objet,"label558");
input1=lookup_widget(objet,"nid");
input2=lookup_widget(objet,"nmot_de_passe");
input3=lookup_widget(objet,"nnom");
input4=lookup_widget(objet,"nprenom");
input5=lookup_widget(objet,"ntel");
input6=lookup_widget(objet,"nemail");
input7=lookup_widget(objet,"nadresse");
jour=lookup_widget(objet,"njour");
mois=lookup_widget(objet,"nmois");
annee=lookup_widget(objet,"nannee");
sexe=lookup_widget(objet,"nsexe");

strcpy(p.identifiant,gtk_entry_get_text(GTK_ENTRY(input1)));
strcpy(p.mot_de_passe,gtk_entry_get_text(GTK_ENTRY(input2)));
strcpy(p.nom,gtk_entry_get_text(GTK_ENTRY(input3)));
strcpy(p.prenom,gtk_entry_get_text(GTK_ENTRY(input4)));
strcpy(p.sexe,gtk_combo_box_get_active_text(GTK_COMBO_BOX(sexe)));
p.jour=gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(jour));
p.mois=gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(mois));
p.annee=gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(annee));
strcpy(p.tel,gtk_entry_get_text(GTK_ENTRY(input5)));
strcpy(p.email,gtk_entry_get_text(GTK_ENTRY(input6)));
strcpy(p.adresse,gtk_entry_get_text(GTK_ENTRY(input7)));
strcpy(adresses,gtk_entry_get_text(GTK_ENTRY(input7)));
strcpy(mdp,gtk_entry_get_text(GTK_ENTRY(input2)));
strcpy(id,gtk_entry_get_text(GTK_ENTRY(input1)));


modifier_personne (p);
modifier_personnee(id,mdp,adresses);
gtk_label_set_text(GTK_LABEL(output0),"Modifier terminer");
}


void
on_valider_clicked                     (GtkWidget       *objet,
                                        gpointer         user_data)
{
personne p;
GtkWidget window5;
GtkWidget *input1,*output8,*output1,*output2,*output3,*output4,*output5,*output6,*output7;

char id [30];
char erreur[50], *markup; const char *format="<span foreground=\"blue\"><b>\%s</b></span>";

output8=lookup_widget(objet,"oui");
output1=lookup_widget(objet,"nid");
output2=lookup_widget(objet,"nmot_de_passe");
output3=lookup_widget(objet,"nnom");
output4=lookup_widget(objet,"nprenom");
output5=lookup_widget(objet,"ntel");
output6=lookup_widget(objet,"nemail");
output7=lookup_widget(objet,"nadresse");
input1=lookup_widget(objet,"id");
strcpy(id,gtk_entry_get_text(GTK_ENTRY(input1)));

FILE *f;
	f=fopen("employers.txt","r");
	if(f!=NULL)
{
while(fscanf(f,"%s %s %s %s %s %d %d %d %s %s %s\n",p.identifiant,p.mot_de_passe,p.nom,p.prenom,p.sexe,&p.jour,&p.mois,&p.annee,p.tel,p.email,p.adresse)!=EOF)
{
	if (strcmp(p.identifiant,id)==0)
{
gtk_entry_set_text (GTK_ENTRY (output1),p.identifiant);
gtk_entry_set_text (GTK_ENTRY (output2),p.mot_de_passe);
gtk_entry_set_text (GTK_ENTRY (output3),p.nom);
gtk_entry_set_text (GTK_ENTRY (output4),p.prenom);
gtk_entry_set_text (GTK_ENTRY (output5),p.tel);
gtk_entry_set_text (GTK_ENTRY (output6),p.email);
gtk_entry_set_text (GTK_ENTRY (output7),p.adresse);


sprintf(erreur,"ce id existe");
 markup=g_markup_printf_escaped(format,erreur);
 gtk_label_set_markup(GTK_LABEL(output8),markup);
}
else{
 sprintf(erreur,"ce id n'existe pas");
 markup=g_markup_printf_escaped(format,erreur);
 gtk_label_set_markup(GTK_LABEL(output8),markup);
}

}
}



}


void
on_debut_clicked                       (GtkWidget       *objet,
                                        gpointer         user_data)
{
GtkWidget *window3,*window6;

window6=lookup_widget(objet,"window6");

gtk_widget_destroy(window6);
window3=create_window3();
}


void
on_confirmer_clicked                   (GtkWidget       *objet,
                                        gpointer         user_data)
{
GtkWidget *window6;
GtkWidget *input;
GtkWidget *outputp;

char supp[30];
personne p;

outputp=lookup_widget(objet,"suppr");
input=lookup_widget(objet,"supp");
strcpy(supp,gtk_entry_get_text(GTK_ENTRY(input)));
supprimerid(supp);
supprimer_personne(supp);
gtk_label_set_text(GTK_LABEL(outputp),"supprimer avec succee");
}


void
on_sortie_clicked                      (GtkWidget       *objet,
                                        gpointer         user_data)
{
GtkWidget *window1,*window3;

window3=lookup_widget(objet,"window3");

gtk_widget_destroy(window3);
window1=create_windowacceuil();
gtk_widget_show(window1);

}

