/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interfacev.h"
#include "gest.h"
#include "support.h"


#include "interfaceadmin.h"
#include "support.h"
#include "supporta.h"
#include "employers.h"
#include "fonction.h"
#include "fonctions.h"
#include "interface.h"
#include "interfacere.h"
#include "interfacehe.h"
#include "gestionhotel.h"




#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

/*GtkWidget*
create_gestionvol (void)
{
  GtkWidget *gestionvol;
  GtkWidget *fixed1;
  GtkWidget *treeview1;
  GtkWidget *button1n;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *button2n;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *button3n;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label3;

  gestionvol = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gestionvol), _("gestionvol"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (gestionvol), fixed1);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed1), treeview1, 48, 56);
  gtk_widget_set_size_request (treeview1, 848, 240);

  button1n = gtk_button_new ();
  gtk_widget_show (button1n);
  gtk_fixed_put (GTK_FIXED (fixed1), button1n, 408, 328);
  gtk_widget_set_size_request (button1n, 248, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1n), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  button2n = gtk_button_new ();
  gtk_widget_show (button2n);
  gtk_fixed_put (GTK_FIXED (fixed1), button2n, 16, 368);
  gtk_widget_set_size_request (button2n, 106, 37);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button2n), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  button3n = gtk_button_new ();
  gtk_widget_show (button3n);
  gtk_fixed_put (GTK_FIXED (fixed1), button3n, 912, 8);
  gtk_widget_set_size_request (button3n, 98, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button3n), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("quitte"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button1n, "clicked",
                    G_CALLBACK (on_button1n_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2n, "clicked",
                    G_CALLBACK (on_button2n_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3n, "clicked",
                    G_CALLBACK (on_button3n_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
 /* GLADE_HOOKUP_OBJECT_NO_REF (gestionvol, gestionvol, "gestionvol");
  GLADE_HOOKUP_OBJECT (gestionvol, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (gestionvol, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (gestionvol, button1n, "button1n");
  GLADE_HOOKUP_OBJECT (gestionvol, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (gestionvol, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (gestionvol, image1, "image1");
  GLADE_HOOKUP_OBJECT (gestionvol, label1, "label1");
  GLADE_HOOKUP_OBJECT (gestionvol, button2n, "button2n");
  GLADE_HOOKUP_OBJECT (gestionvol, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (gestionvol, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (gestionvol, image2, "image2");
  GLADE_HOOKUP_OBJECT (gestionvol, label2, "label2");
  GLADE_HOOKUP_OBJECT (gestionvol, button3n, "button3n");
  GLADE_HOOKUP_OBJECT (gestionvol, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (gestionvol, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (gestionvol, image3, "image3");
  GLADE_HOOKUP_OBJECT (gestionvol, label3, "label3");

  return gestionvol;
}

GtkWidget*
create_ajoutervol (void)
{
  GtkWidget *ajoutervol;
  GtkWidget *fixed2;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *entry7;
  GtkWidget *label5;
  GtkWidget *label7;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *label6;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *label8;
  GtkWidget *label4;
  GtkWidget *label11;
  GtkWidget *combobox1;
  GtkWidget *button7;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label30;
  GtkWidget *button4;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label12;

  ajoutervol = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajoutervol), _("ajoutervol"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (ajoutervol), fixed2);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed2), entry1, 192, 24);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed2), entry2, 624, 16);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  spinbutton1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton1, 200, 80);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  spinbutton2_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton2, 320, 80);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  spinbutton3_adj = gtk_adjustment_new (2019, 2019, 2050, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton3, 448, 80);
  gtk_widget_set_size_request (spinbutton3, 60, 27);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed2), entry3, 624, 64);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed2), entry4, 192, 128);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed2), entry5, 624, 112);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed2), entry7, 192, 176);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  label5 = gtk_label_new (_("<b>ville d'arriv\303\251e:</b>"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed2), label5, 504, 16);
  gtk_widget_set_size_request (label5, 112, 25);
  gtk_label_set_use_markup (GTK_LABEL (label5), TRUE);

  label7 = gtk_label_new (_("<b>dur\303\251e de vol:</b>"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed2), label7, 512, 64);
  gtk_widget_set_size_request (label7, 105, 33);
  gtk_label_set_use_markup (GTK_LABEL (label7), TRUE);

  label9 = gtk_label_new (_("<b>prix du vol:</b>"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed2), label9, 520, 112);
  gtk_widget_set_size_request (label9, 105, 33);
  gtk_label_set_use_markup (GTK_LABEL (label9), TRUE);

  label10 = gtk_label_new (_("<b>classe:</b>"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed2), label10, 536, 152);
  gtk_widget_set_size_request (label10, 89, 33);
  gtk_label_set_use_markup (GTK_LABEL (label10), TRUE);

  label6 = gtk_label_new (_("<b>date de d\303\251part:</b>"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed2), label6, 16, 80);
  gtk_widget_set_size_request (label6, 120, 25);
  gtk_label_set_use_markup (GTK_LABEL (label6), TRUE);

  label23 = gtk_label_new (_("<u>jour</u>"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed2), label23, 136, 80);
  gtk_widget_set_size_request (label23, 64, 24);
  gtk_label_set_use_markup (GTK_LABEL (label23), TRUE);

  label24 = gtk_label_new (_("<u>mois</u>"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed2), label24, 256, 80);
  gtk_widget_set_size_request (label24, 64, 24);
  gtk_label_set_use_markup (GTK_LABEL (label24), TRUE);

  label25 = gtk_label_new (_("<u>annee</u>"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed2), label25, 384, 80);
  gtk_widget_set_size_request (label25, 64, 25);
  gtk_label_set_use_markup (GTK_LABEL (label25), TRUE);

  label8 = gtk_label_new (_("<b>nombre des voyageurs:</b>"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 16, 120);
  gtk_widget_set_size_request (label8, 168, 40);
  gtk_label_set_use_markup (GTK_LABEL (label8), TRUE);

  label4 = gtk_label_new (_("<b>ville de d\303\251part:</b>"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed2), label4, 72, 24);
  gtk_widget_set_size_request (label4, 112, 32);
  gtk_label_set_use_markup (GTK_LABEL (label4), TRUE);

  label11 = gtk_label_new (_("<b>id vol:</b>"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed2), label11, 120, 176);
  gtk_widget_set_size_request (label11, 88, 25);
  gtk_label_set_use_markup (GTK_LABEL (label11), TRUE);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed2), combobox1, 640, 152);
  gtk_widget_set_size_request (combobox1, 128, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Economique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Premium"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Premi\303\250re"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Classe Affaire"));

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed2), button7, 480, 224);
  gtk_widget_set_size_request (button7, 106, 37);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button7), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("afficher"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox7), label30, FALSE, FALSE, 0);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed2), button4, 288, 224);
  gtk_widget_set_size_request (button4, 112, 37);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button4), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox4), label12, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_button7_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  /*GLADE_HOOKUP_OBJECT_NO_REF (ajoutervol, ajoutervol, "ajoutervol");
  GLADE_HOOKUP_OBJECT (ajoutervol, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (ajoutervol, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (ajoutervol, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (ajoutervol, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (ajoutervol, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (ajoutervol, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (ajoutervol, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (ajoutervol, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (ajoutervol, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (ajoutervol, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (ajoutervol, label5, "label5");
  GLADE_HOOKUP_OBJECT (ajoutervol, label7, "label7");
  GLADE_HOOKUP_OBJECT (ajoutervol, label9, "label9");
  GLADE_HOOKUP_OBJECT (ajoutervol, label10, "label10");
  GLADE_HOOKUP_OBJECT (ajoutervol, label6, "label6");
  GLADE_HOOKUP_OBJECT (ajoutervol, label23, "label23");
  GLADE_HOOKUP_OBJECT (ajoutervol, label24, "label24");
  GLADE_HOOKUP_OBJECT (ajoutervol, label25, "label25");
  GLADE_HOOKUP_OBJECT (ajoutervol, label8, "label8");
  GLADE_HOOKUP_OBJECT (ajoutervol, label4, "label4");
  GLADE_HOOKUP_OBJECT (ajoutervol, label11, "label11");
  GLADE_HOOKUP_OBJECT (ajoutervol, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (ajoutervol, button7, "button7");
  GLADE_HOOKUP_OBJECT (ajoutervol, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (ajoutervol, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (ajoutervol, image7, "image7");
  GLADE_HOOKUP_OBJECT (ajoutervol, label30, "label30");
  GLADE_HOOKUP_OBJECT (ajoutervol, button4, "button4");
  GLADE_HOOKUP_OBJECT (ajoutervol, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (ajoutervol, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (ajoutervol, image4, "image4");
  GLADE_HOOKUP_OBJECT (ajoutervol, label12, "label12");

  return ajoutervol;
}

GtkWidget*
create_modifvol (void)
{
  GtkWidget *modifvol;
  GtkWidget *fixed3;
  GtkWidget *entry8;
  GtkWidget *entry9;
  GtkWidget *entry10;
  GtkWidget *entry11;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkObject *spinbutton5i_adj;
  GtkWidget *spinbutton5i;
  GtkObject *spinbutton6i_adj;
  GtkWidget *spinbutton6i;
  GtkWidget *entry13;
  GtkWidget *entry14;
  GtkWidget *label15;
  GtkWidget *label18;
  GtkWidget *label14;
  GtkWidget *label16;
  GtkWidget *label29;
  GtkWidget *label28;
  GtkWidget *label27;
  GtkWidget *label17;
  GtkWidget *label13;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *button6i;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label22;
  GtkWidget *button5i;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label21;
  GtkWidget *combobox2;

  modifvol = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifvol), _("modifvol"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (modifvol), fixed3);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed3), entry8, 176, 40);
  gtk_widget_set_size_request (entry8, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed3), entry9, 568, 32);
  gtk_widget_set_size_request (entry9, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed3), entry10, 568, 80);
  gtk_widget_set_size_request (entry10, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  entry11 = gtk_entry_new ();
  gtk_widget_show (entry11);
  gtk_fixed_put (GTK_FIXED (fixed3), entry11, 568, 120);
  gtk_widget_set_size_request (entry11, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11), 8226);

  spinbutton4_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton4, 160, 80);
  gtk_widget_set_size_request (spinbutton4, 60, 27);

  spinbutton5i_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton5i = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5i_adj), 1, 0);
  gtk_widget_show (spinbutton5i);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton5i, 280, 80);
  gtk_widget_set_size_request (spinbutton5i, 60, 27);

  spinbutton6i_adj = gtk_adjustment_new (2019, 2019, 2050, 1, 10, 10);
  spinbutton6i = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6i_adj), 1, 0);
  gtk_widget_show (spinbutton6i);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton6i, 392, 80);
  gtk_widget_set_size_request (spinbutton6i, 60, 27);

  entry13 = gtk_entry_new ();
  gtk_widget_show (entry13);
  gtk_fixed_put (GTK_FIXED (fixed3), entry13, 184, 128);
  gtk_widget_set_size_request (entry13, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry13), 8226);

  entry14 = gtk_entry_new ();
  gtk_widget_show (entry14);
  gtk_fixed_put (GTK_FIXED (fixed3), entry14, 184, 176);
  gtk_widget_set_size_request (entry14, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry14), 8226);

  label15 = gtk_label_new (_("<b>date de depart:</b>"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed3), label15, 0, 80);
  gtk_widget_set_size_request (label15, 120, 32);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);

  label18 = gtk_label_new (_("<b>classe:</b>"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed3), label18, 496, 152);
  gtk_widget_set_size_request (label18, 81, 48);
  gtk_label_set_use_markup (GTK_LABEL (label18), TRUE);

  label14 = gtk_label_new (_("<b>ville d'arrivee:</b>"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed3), label14, 448, 32);
  gtk_widget_set_size_request (label14, 112, 32);
  gtk_label_set_use_markup (GTK_LABEL (label14), TRUE);

  label16 = gtk_label_new (_("<b>duree de vol:</b>"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed3), label16, 456, 80);
  gtk_widget_set_size_request (label16, 104, 32);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  label29 = gtk_label_new (_("<u>annee</u>"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed3), label29, 336, 80);
  gtk_widget_set_size_request (label29, 57, 25);
  gtk_label_set_use_markup (GTK_LABEL (label29), TRUE);

  label28 = gtk_label_new (_("<u>mois</u>"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed3), label28, 224, 80);
  gtk_widget_set_size_request (label28, 56, 25);
  gtk_label_set_use_markup (GTK_LABEL (label28), TRUE);

  label27 = gtk_label_new (_("<u>jour</u>"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed3), label27, 112, 80);
  gtk_widget_set_size_request (label27, 56, 25);
  gtk_label_set_use_markup (GTK_LABEL (label27), TRUE);

  label17 = gtk_label_new (_("<b>prix du vol:</b>"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed3), label17, 464, 120);
  gtk_widget_set_size_request (label17, 104, 32);
  gtk_label_set_use_markup (GTK_LABEL (label17), TRUE);

  label13 = gtk_label_new (_("<b>ville de depart:</b>"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed3), label13, 48, 40);
  gtk_widget_set_size_request (label13, 112, 32);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);

  label19 = gtk_label_new (_("<b>nombre des voyageurs:</b>"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed3), label19, 16, 120);
  gtk_widget_set_size_request (label19, 168, 48);
  gtk_label_set_use_markup (GTK_LABEL (label19), TRUE);

  label20 = gtk_label_new (_("<b>id vol:</b>"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed3), label20, 96, 176);
  gtk_widget_set_size_request (label20, 88, 24);
  gtk_label_set_use_markup (GTK_LABEL (label20), TRUE);

  button6i = gtk_button_new ();
  gtk_widget_show (button6i);
  gtk_fixed_put (GTK_FIXED (fixed3), button6i, 440, 208);
  gtk_widget_set_size_request (button6i, 98, 37);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button6i), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("supprimeri"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox6), label22, FALSE, FALSE, 0);

  button5i = gtk_button_new ();
  gtk_widget_show (button5i);
  gtk_fixed_put (GTK_FIXED (fixed3), button5i, 312, 208);
  gtk_widget_set_size_request (button5i, 98, 37);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button5i), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox5), label21, FALSE, FALSE, 0);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox2, 576, 160);
  gtk_widget_set_size_request (combobox2, 144, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Economique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Premium"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Premi\303\250re"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Classe Affaire"));

  g_signal_connect ((gpointer) button6i, "clicked",
                    G_CALLBACK (on_button6i_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5i, "clicked",
                    G_CALLBACK (on_button5i_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
 /* GLADE_HOOKUP_OBJECT_NO_REF (modifvol, modifvol, "modifvol");
  GLADE_HOOKUP_OBJECT (modifvol, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (modifvol, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (modifvol, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (modifvol, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (modifvol, entry11, "entry11");
  GLADE_HOOKUP_OBJECT (modifvol, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (modifvol, spinbutton5i, "spinbutton5i");
  GLADE_HOOKUP_OBJECT (modifvol, spinbutton6i, "spinbutton6i");
  GLADE_HOOKUP_OBJECT (modifvol, entry13, "entry13");
  GLADE_HOOKUP_OBJECT (modifvol, entry14, "entry14");
  GLADE_HOOKUP_OBJECT (modifvol, label15, "label15");
  GLADE_HOOKUP_OBJECT (modifvol, label18, "label18");
  GLADE_HOOKUP_OBJECT (modifvol, label14, "label14");
  GLADE_HOOKUP_OBJECT (modifvol, label16, "label16");
  GLADE_HOOKUP_OBJECT (modifvol, label29, "label29");
  GLADE_HOOKUP_OBJECT (modifvol, label28, "label28");
  GLADE_HOOKUP_OBJECT (modifvol, label27, "label27");
  GLADE_HOOKUP_OBJECT (modifvol, label17, "label17");
  GLADE_HOOKUP_OBJECT (modifvol, label13, "label13");
  GLADE_HOOKUP_OBJECT (modifvol, label19, "label19");
  GLADE_HOOKUP_OBJECT (modifvol, label20, "label20");
  GLADE_HOOKUP_OBJECT (modifvol, button6i, "button6i");
  GLADE_HOOKUP_OBJECT (modifvol, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (modifvol, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (modifvol, image6, "image6");
  GLADE_HOOKUP_OBJECT (modifvol, label22, "label22");
  GLADE_HOOKUP_OBJECT (modifvol, button5i, "button5i");
  GLADE_HOOKUP_OBJECT (modifvol, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (modifvol, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (modifvol, image5, "image5");
  GLADE_HOOKUP_OBJECT (modifvol, label21, "label21");
  GLADE_HOOKUP_OBJECT (modifvol, combobox2, "combobox2");

  return modifvol;
}*/


















void
on_button1n_clicked                    (GtkWidget       *objet_graphique,
                                        gpointer         user_data)
{
GtkWidget *ajoutervol;
GtkWidget *gestionvol;
ajoutervol= create_ajoutervol();
gtk_widget_show (ajoutervol);
gestionvol= lookup_widget(objet_graphique,"gestionvol");
gtk_widget_hide(gestionvol);

}


void
on_button2n_clicked                    (GtkWidget       *objet_graphique,
                                        gpointer         user_data)
{
GtkWidget *ajoutervol;
GtkWidget *gestionvol;
ajoutervol= create_ajoutervol();
gtk_widget_show (ajoutervol);
gestionvol= lookup_widget(objet_graphique,"gestionvol");
gtk_widget_hide(gestionvol);
}


void
on_button3n_clicked                    (GtkWidget      *objet_graphique,
                                        gpointer         user_data)
{
GtkWidget *gestionvol;
GtkWidget *windowacceuil;
gestionvol=lookup_widget(objet_graphique,"gestionvol");

gtk_widget_destroy(gestionvol);
windowacceuil=create_windowacceuil();
gtk_widget_show(windowacceuil);
}


void
on_button4_clicked                     (GtkWidget        *objet_graphique,
                                        gpointer         user_data)
{
	vol p;
	
	GtkWidget *input1,*input2,*input3,*input4,*input5,*input6,*input7,*input8,*input9,*input10;
	GtkWidget *ajoutervol;

	ajoutervol=lookup_widget(objet_graphique,"ajoutervol");
	
	input1=lookup_widget(objet_graphique,"entry7");
	input2=lookup_widget(objet_graphique,"entry1");
	input3=lookup_widget(objet_graphique,"entry2");
	input4=lookup_widget(objet_graphique,"entry3");
	input5=lookup_widget(objet_graphique,"entry4");
	input6=lookup_widget(objet_graphique,"entry5");
	
	GtkWidget *spinbutton1;
	GtkWidget *spinbutton2;
	GtkWidget *spinbutton3;
	GtkWidget *combobox1;
	
	

	spinbutton1=lookup_widget(objet_graphique, "spinbutton1");
	spinbutton2=lookup_widget(objet_graphique, "spinbutton2");
	spinbutton3=lookup_widget(objet_graphique, "spinbutton3");
	combobox1=lookup_widget(objet_graphique, "combobox1");

        p.jour=gtk_spin_button_get_value_as_int (GTK_SPIN_BUTTON(spinbutton1));
	p.mois=gtk_spin_button_get_value_as_int (GTK_SPIN_BUTTON(spinbutton2));
	p.annee=gtk_spin_button_get_value_as_int (GTK_SPIN_BUTTON(spinbutton3));
	
	strcpy(p.classe,gtk_combo_box_get_active_text (GTK_COMBO_BOX(combobox1)));
	/*p.jour=JJ;
	p.mois=MM;
	p.annee=AA;*/

	strcpy(p.id,gtk_entry_get_text(GTK_ENTRY(input1)));
	strcpy(p.depart,gtk_entry_get_text(GTK_ENTRY(input2)));
	strcpy(p.arriver,gtk_entry_get_text(GTK_ENTRY(input3)));
	strcpy(p.duree,gtk_entry_get_text(GTK_ENTRY(input4)));
	strcpy(p.nbrvoyageur,gtk_entry_get_text(GTK_ENTRY(input5)));
	strcpy(p.prix,gtk_entry_get_text(GTK_ENTRY(input6)));
	ajouter(p);
     
}



void
on_treeview1_row_activated             (GtkWidget     *objet_graphique,
                                        GtkTreePath     *path,
                                        GtkTreeViewColumn *column,
                                        gpointer         user_data)
{
GtkWidget *idn ,*departn,*arrivern,*journ,*moisn,*anneen,*dureen,*nbrvoyageurn,*prixn,*classen,*modifvol,*gestionvol,*treeview;
char *id,*depart,*arriver,*duree,*nbrvoyageur,*prix,*classe;
int jour,mois,annee;
	modifvol=create_modifvol();
	treeview=lookup_widget(objet_graphique,"treeview1");
	gestionvol=lookup_widget(objet_graphique,"gestionvol");
	idn=lookup_widget(modifvol,"entry14");
	departn=lookup_widget(modifvol,"entry8");
	arrivern=lookup_widget(modifvol,"entry9");
	dureen=lookup_widget(modifvol,"entry10");
	nbrvoyageurn=lookup_widget(modifvol,"entry13");
	prixn=lookup_widget(modifvol,"entry11");

	

	journ=lookup_widget(modifvol,"spinbutton4");
	moisn=lookup_widget(modifvol,"spinbutton5i");
 	anneen=lookup_widget(modifvol,"spinbutton6i");
	classen=lookup_widget(modifvol,"combobox2");
	
	
	GtkTreeIter iter;
	GtkTreeModel *model=gtk_tree_view_get_model (GTK_TREE_VIEW(treeview));
	gtk_tree_model_get_iter(model,&iter,path);
	gtk_tree_model_get (model,&iter,0,&id,1,&depart,2,&arriver,3,&jour,4,&mois,5,&annee,6,&duree,7,&nbrvoyageur,8,&prix,9,&classe,-1);
	printf("%s %s %s %d %d %d %s %s %s %s",id,depart,arriver,jour,mois,annee,duree,nbrvoyageur,prix,classe);
	gtk_entry_set_text(GTK_ENTRY (idn),_(id));
	gtk_entry_set_text(GTK_ENTRY (departn),_(depart));
        gtk_entry_set_text(GTK_ENTRY (arrivern),_(arriver));
	 gtk_entry_set_text(GTK_ENTRY (dureen),_(duree));
	 gtk_entry_set_text(GTK_ENTRY (nbrvoyageurn),_(nbrvoyageur));
	 gtk_entry_set_text(GTK_ENTRY (prixn),_(prix));
	 gtk_combo_box_append_text(GTK_COMBO_BOX (classen),_(classe));
	/*gtk_spin_button_set_value(GTK_SPIN_BUTTON(journ),jour);
	gtk_spin_button_set_value(GTK_SPIN_BUTTON (moisn),mois);
	gtk_spin_button_set_value(GTK_SPIN_BUTTON (anneen),annee);*/

	gtk_widget_hide(gestionvol);
	gtk_widget_show(modifvol);
}


void
on_button5i_clicked                     (GtkWidget       *objet_graphique,
                                        gpointer         user_data)
{
GtkWidget *id,*depart,*arriver,*jour,*mois,*annee,*duree,*current,*nbrvoyageur,*prix,*classe,*gestionvol,*modifvol,*List_View;
	char idk[20],departk[20],arriverk[20],dureek[20],nbrvoyageurk[20],prixk[20],classek[20];
	int jourk,moisk,anneek;

	modifvol=lookup_widget(objet_graphique,"modifvol");
	id=lookup_widget(objet_graphique,"entry14");
	depart=lookup_widget(objet_graphique,"entry8");
	arriver=lookup_widget(objet_graphique,"entry9");
	duree=lookup_widget(objet_graphique,"entry10");
	nbrvoyageur=lookup_widget(objet_graphique,"entry13");
	prix=lookup_widget(objet_graphique,"entry11");

	
	jour=lookup_widget(objet_graphique,"spinbutton4");
	mois=lookup_widget(objet_graphique,"spinbutton5");
	annee=lookup_widget(objet_graphique,"spinbutton6");
	
	classe=lookup_widget(objet_graphique,"combobox2");
	strcpy(idk,gtk_entry_get_text(GTK_ENTRY(id)));
	strcpy(departk,gtk_entry_get_text(GTK_ENTRY(depart)));
	strcpy(arriverk,gtk_entry_get_text(GTK_ENTRY(arriver)));
	strcpy(dureek,gtk_entry_get_text(GTK_ENTRY(duree)));
	strcpy(nbrvoyageurk,gtk_entry_get_text(GTK_ENTRY(nbrvoyageur)));
	strcpy(prixk,gtk_entry_get_text(GTK_ENTRY(prix)));
	jourk=gtk_spin_button_get_value_as_int(jour);
	moisk=gtk_spin_button_get_value_as_int(mois);
	anneek=gtk_spin_button_get_value_as_int(annee);
	strcpy(classek,gtk_combo_box_get_active_text(GTK_COMBO_BOX(classe)));
	
	modifier(idk,departk,arriverk,jourk,moisk,anneek,dureek,nbrvoyageurk,prixk,classek);
	gestionvol=create_gestionvol();
	gtk_widget_show (gestionvol);
	current=lookup_widget(objet_graphique,"modifvol");
	gtk_widget_hide(current);
	List_View=lookup_widget(gestionvol,"treeview1");
	afficher(List_View);
}


void
on_button6i_clicked                     (GtkWidget       *objet_graphique,
                                        gpointer         user_data)
{
GtkWidget *id,*depart,*arriver,*jour,*mois,*annee,*duree,*current,*nbrvoyageur,*prix,*classe,*gestionvol,*modifvol,*List_View;
	 char idk[20],departk[20],arriverk[20],dureek[20],nbrvoyageurk[20],prixk[20],classek[20];
	int jourk,moisk,anneek;

	
	id=lookup_widget(objet_graphique,"entry14");
	depart=lookup_widget(objet_graphique,"entry8");
	arriver=lookup_widget(objet_graphique,"entry9");
	duree=lookup_widget(objet_graphique,"entry10");
	nbrvoyageur=lookup_widget(objet_graphique,"entry13");
	prix=lookup_widget(objet_graphique,"entry11");

	
	jour=lookup_widget(objet_graphique,"spinbutton4");
	mois=lookup_widget(objet_graphique,"spinbutton5i");
	annee=lookup_widget(objet_graphique,"spinbutton6i");
	
	classe=lookup_widget(objet_graphique,"combobox2");
	strcpy(idk,gtk_entry_get_text(GTK_ENTRY(id)));
	strcpy(departk,gtk_entry_get_text(GTK_ENTRY(depart)));
	strcpy(arriverk,gtk_entry_get_text(GTK_ENTRY(arriver)));
	strcpy(dureek,gtk_entry_get_text(GTK_ENTRY(duree)));
	strcpy(nbrvoyageurk,gtk_entry_get_text(GTK_ENTRY(nbrvoyageur)));
	strcpy(prixk,gtk_entry_get_text(GTK_ENTRY(prix)));
	jourk=gtk_spin_button_get_value_as_int(jour);
	moisk=gtk_spin_button_get_value_as_int(mois);
	anneek=gtk_spin_button_get_value_as_int(annee);
	strcpy(classek,gtk_combo_box_get_active_text(GTK_COMBO_BOX(classe)));
	
	supprimeri(idk);
	gestionvol=create_gestionvol();
	gtk_widget_show (gestionvol);
	current=lookup_widget(objet_graphique,"modifvol");
	gtk_widget_hide(current);
	List_View=lookup_widget(gestionvol,"treeview1");
	afficher(List_View);
}




void
on_button7_clicked                     (GtkWidget       *objet_graphique,
                                        gpointer         user_data)
{

	GtkWidget *ajoutervol;
	GtkWidget *gestionvol;
	GtkWidget *treeview1;

	ajoutervol=lookup_widget(objet_graphique, "ajoutervol");

	gtk_widget_hide(ajoutervol);
	
	gestionvol=create_gestionvol();

	gtk_widget_show_all(gestionvol);

	treeview1=lookup_widget(gestionvol,"treeview1");
	afficher(treeview1);
}


