/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1 (void);
GtkWidget* create_window2 (void);
GtkWidget* create_window3 (void);
GtkWidget* create_window4 (void);
GtkWidget* create_window5 (void);
GtkWidget* create_window6 (void);
GtkWidget* create_windowinscription (void);
GtkWidget* create_windowacceuil (void);
GtkWidget* create_window00 (void);
GtkWidget* create_windowfelecitations (void);
GtkWidget* create_windowespaceclient (void);
GtkWidget* create_windowdesactivercompte (void);
GtkWidget* create_gestionvol (void);
GtkWidget* create_ajoutervol (void);
GtkWidget* create_modifvol (void);
