/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interfacere.h"
#include "interfacehe.h"
#include "gestionhotel.h"
#include "interfaceadmin.h"
#include "support.h"
#include "supporta.h"
#include "supporth.h"
#include "employers.h"
#include "fonction.h"
#include "fonctions.h"
#include "interface.h"
#include "interfacev.h"
#include "gest.h"







#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_reservationhotel (void)
{
  GtkWidget *reservationhotel;
  GtkWidget *fixed1;
  GtkWidget *entryprixmax;
  GtkWidget *treeview1;
  GtkObject *nbnuit_adj;
  GtkWidget *nbnuit;
  GtkObject *nbchambre_adj;
  GtkWidget *nbchambre;
  GtkObject *nbetoile_adj;
  GtkWidget *nbetoile;
  GtkWidget *labelaide1;
  GtkWidget *calendar1;
  GtkWidget *buttonrechercherh;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label10;
  GtkWidget *labelchambre;
  GtkWidget *labelville;
  GtkWidget *labeletoile;
  GtkWidget *labelprixmax;
  GtkWidget *labelnbnuit;
  GtkWidget *labeldate;
  GtkWidget *comboboxregion;
  GtkWidget *comboboxpension;
  GtkWidget *labelerreurhotel;
  GtkWidget *labelaide2;
  GtkWidget *labeltitre;
  GtkWidget *label39;
  GtkWidget *labelerreurdate;
  GtkWidget *labelpension;
  GtkWidget *buttonretourh;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label11;
  GtkWidget *buttonreserverh;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label12;

  reservationhotel = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (reservationhotel, 800, 700);
  gtk_window_set_title (GTK_WINDOW (reservationhotel), _("Reservation Hotel"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (reservationhotel), fixed1);

  entryprixmax = gtk_entry_new ();
  gtk_widget_show (entryprixmax);
  gtk_fixed_put (GTK_FIXED (fixed1), entryprixmax, 112, 144);
  gtk_widget_set_size_request (entryprixmax, 100, 25);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprixmax), 8226);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed1), treeview1, 100, 376);
  gtk_widget_set_size_request (treeview1, 600, 250);

  nbnuit_adj = gtk_adjustment_new (1, 1, 10, 1, 10, 10);
  nbnuit = gtk_spin_button_new (GTK_ADJUSTMENT (nbnuit_adj), 1, 0);
  gtk_widget_show (nbnuit);
  gtk_fixed_put (GTK_FIXED (fixed1), nbnuit, 376, 144);
  gtk_widget_set_size_request (nbnuit, 100, 27);

  nbchambre_adj = gtk_adjustment_new (1, 1, 50, 1, 10, 10);
  nbchambre = gtk_spin_button_new (GTK_ADJUSTMENT (nbchambre_adj), 1, 0);
  gtk_widget_show (nbchambre);
  gtk_fixed_put (GTK_FIXED (fixed1), nbchambre, 376, 224);
  gtk_widget_set_size_request (nbchambre, 100, 27);

  nbetoile_adj = gtk_adjustment_new (1, 1, 5, 1, 10, 10);
  nbetoile = gtk_spin_button_new (GTK_ADJUSTMENT (nbetoile_adj), 1, 0);
  gtk_widget_show (nbetoile);
  gtk_fixed_put (GTK_FIXED (fixed1), nbetoile, 112, 216);
  gtk_widget_set_size_request (nbetoile, 100, 27);

  labelaide1 = gtk_label_new ("");
  gtk_widget_show (labelaide1);
  gtk_fixed_put (GTK_FIXED (fixed1), labelaide1, 24, 304);
  gtk_widget_set_size_request (labelaide1, 170, 50);
  gtk_misc_set_alignment (GTK_MISC (labelaide1), 0, 0);

  calendar1 = gtk_calendar_new ();
  gtk_widget_show (calendar1);
  gtk_fixed_put (GTK_FIXED (fixed1), calendar1, 536, 80);
  gtk_widget_set_size_request (calendar1, 200, 180);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  buttonrechercherh = gtk_button_new ();
  gtk_widget_show (buttonrechercherh);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonrechercherh, 312, 304);
  gtk_widget_set_size_request (buttonrechercherh, 120, 30);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttonrechercherh), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox1), label10, FALSE, FALSE, 0);

  labelchambre = gtk_label_new (_("Nb de chambre :"));
  gtk_widget_show (labelchambre);
  gtk_fixed_put (GTK_FIXED (fixed1), labelchambre, 240, 224);
  gtk_widget_set_size_request (labelchambre, 130, 25);
  gtk_misc_set_alignment (GTK_MISC (labelchambre), 0, 0.5);

  labelville = gtk_label_new (_("Region"));
  gtk_widget_show (labelville);
  gtk_fixed_put (GTK_FIXED (fixed1), labelville, 8, 72);
  gtk_widget_set_size_request (labelville, 100, 25);
  gtk_misc_set_alignment (GTK_MISC (labelville), 0, 0.5);

  labeletoile = gtk_label_new (_("Nb etoile"));
  gtk_widget_show (labeletoile);
  gtk_fixed_put (GTK_FIXED (fixed1), labeletoile, 8, 224);
  gtk_widget_set_size_request (labeletoile, 100, 25);
  gtk_misc_set_alignment (GTK_MISC (labeletoile), 0, 0.5);

  labelprixmax = gtk_label_new (_("prix max"));
  gtk_widget_show (labelprixmax);
  gtk_fixed_put (GTK_FIXED (fixed1), labelprixmax, 8, 144);
  gtk_widget_set_size_request (labelprixmax, 100, 25);
  gtk_misc_set_alignment (GTK_MISC (labelprixmax), 0, 0.5);

  labelnbnuit = gtk_label_new (_("Nb de nuit :"));
  gtk_widget_show (labelnbnuit);
  gtk_fixed_put (GTK_FIXED (fixed1), labelnbnuit, 240, 144);
  gtk_widget_set_size_request (labelnbnuit, 100, 25);
  gtk_misc_set_alignment (GTK_MISC (labelnbnuit), 0, 0.5);

  labeldate = gtk_label_new (_("Date arrivee"));
  gtk_widget_show (labeldate);
  gtk_fixed_put (GTK_FIXED (fixed1), labeldate, 584, 56);
  gtk_widget_set_size_request (labeldate, 100, 25);
  gtk_misc_set_alignment (GTK_MISC (labeldate), 0, 0.5);

  comboboxregion = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxregion);
  gtk_fixed_put (GTK_FIXED (fixed1), comboboxregion, 112, 72);
  gtk_widget_set_size_request (comboboxregion, 100, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxregion), _("Sousse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxregion), _("Tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxregion), _("Sfax"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxregion), _("Hammamet"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxregion), _("Djerba"));

  comboboxpension = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxpension);
  gtk_fixed_put (GTK_FIXED (fixed1), comboboxpension, 376, 72);
  gtk_widget_set_size_request (comboboxpension, 100, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxpension), _("1/2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxpension), _("complete"));

  labelerreurhotel = gtk_label_new ("");
  gtk_widget_show (labelerreurhotel);
  gtk_fixed_put (GTK_FIXED (fixed1), labelerreurhotel, 544, 648);
  gtk_widget_set_size_request (labelerreurhotel, 230, 25);
  gtk_misc_set_alignment (GTK_MISC (labelerreurhotel), 0, 0.5);

  labelaide2 = gtk_label_new (_(" "));
  gtk_widget_show (labelaide2);
  gtk_fixed_put (GTK_FIXED (fixed1), labelaide2, 120, 584);
  gtk_widget_set_size_request (labelaide2, 500, 25);
  gtk_misc_set_alignment (GTK_MISC (labelaide2), 0, 0.5);

  labeltitre = gtk_label_new (_("Reservation d'Hotel"));
  gtk_widget_show (labeltitre);
  gtk_fixed_put (GTK_FIXED (fixed1), labeltitre, 300, 16);
  gtk_widget_set_size_request (labeltitre, 200, 25);

  label39 = gtk_label_new (_("*Cliquez pour s\303\251lectionner \nla date d'arriv\303\251e"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed1), label39, 536, 264);
  gtk_widget_set_size_request (label39, 250, 50);

  labelerreurdate = gtk_label_new ("");
  gtk_widget_show (labelerreurdate);
  gtk_fixed_put (GTK_FIXED (fixed1), labelerreurdate, 272, 336);
  gtk_widget_set_size_request (labelerreurdate, 300, 25);
  gtk_misc_set_alignment (GTK_MISC (labelerreurdate), 0, 0.5);

  labelpension = gtk_label_new (_("Pension :"));
  gtk_widget_show (labelpension);
  gtk_fixed_put (GTK_FIXED (fixed1), labelpension, 240, 72);
  gtk_widget_set_size_request (labelpension, 75, 25);
  gtk_misc_set_alignment (GTK_MISC (labelpension), 0, 0.5);

  buttonretourh = gtk_button_new ();
  gtk_widget_show (buttonretourh);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonretourh, 104, 640);
  gtk_widget_set_size_request (buttonretourh, 100, 30);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttonretourh), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox2), label11, FALSE, FALSE, 0);

  buttonreserverh = gtk_button_new ();
  gtk_widget_show (buttonreserverh);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonreserverh, 544, 640);
  gtk_widget_set_size_request (buttonreserverh, 100, 30);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (buttonreserverh), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Reserver"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox3), label12, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) reservationhotel, "destroy",
                    G_CALLBACK (on_reservationhotel_destroy),
                    NULL);
  g_signal_connect ((gpointer) calendar1, "day_selected",
                    G_CALLBACK (on_calendar1_day_selected),
                    NULL);
  g_signal_connect ((gpointer) buttonrechercherh, "clicked",
                    G_CALLBACK (on_buttonrechercherh_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonretourh, "clicked",
                    G_CALLBACK (on_buttonretourh_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonreserverh, "clicked",
                    G_CALLBACK (on_buttonreserverh_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (reservationhotel, reservationhotel, "reservationhotel");
  GLADE_HOOKUP_OBJECT (reservationhotel, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (reservationhotel, entryprixmax, "entryprixmax");
  GLADE_HOOKUP_OBJECT (reservationhotel, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (reservationhotel, nbnuit, "nbnuit");
  GLADE_HOOKUP_OBJECT (reservationhotel, nbchambre, "nbchambre");
  GLADE_HOOKUP_OBJECT (reservationhotel, nbetoile, "nbetoile");
  GLADE_HOOKUP_OBJECT (reservationhotel, labelaide1, "labelaide1");
  GLADE_HOOKUP_OBJECT (reservationhotel, calendar1, "calendar1");
  GLADE_HOOKUP_OBJECT (reservationhotel, buttonrechercherh, "buttonrechercherh");
  GLADE_HOOKUP_OBJECT (reservationhotel, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (reservationhotel, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (reservationhotel, image1, "image1");
  GLADE_HOOKUP_OBJECT (reservationhotel, label10, "label10");
  GLADE_HOOKUP_OBJECT (reservationhotel, labelchambre, "labelchambre");
  GLADE_HOOKUP_OBJECT (reservationhotel, labelville, "labelville");
  GLADE_HOOKUP_OBJECT (reservationhotel, labeletoile, "labeletoile");
  GLADE_HOOKUP_OBJECT (reservationhotel, labelprixmax, "labelprixmax");
  GLADE_HOOKUP_OBJECT (reservationhotel, labelnbnuit, "labelnbnuit");
  GLADE_HOOKUP_OBJECT (reservationhotel, labeldate, "labeldate");
  GLADE_HOOKUP_OBJECT (reservationhotel, comboboxregion, "comboboxregion");
  GLADE_HOOKUP_OBJECT (reservationhotel, comboboxpension, "comboboxpension");
  GLADE_HOOKUP_OBJECT (reservationhotel, labelerreurhotel, "labelerreurhotel");
  GLADE_HOOKUP_OBJECT (reservationhotel, labelaide2, "labelaide2");
  GLADE_HOOKUP_OBJECT (reservationhotel, labeltitre, "labeltitre");
  GLADE_HOOKUP_OBJECT (reservationhotel, label39, "label39");
  GLADE_HOOKUP_OBJECT (reservationhotel, labelerreurdate, "labelerreurdate");
  GLADE_HOOKUP_OBJECT (reservationhotel, labelpension, "labelpension");
  GLADE_HOOKUP_OBJECT (reservationhotel, buttonretourh, "buttonretourh");
  GLADE_HOOKUP_OBJECT (reservationhotel, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (reservationhotel, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (reservationhotel, image2, "image2");
  GLADE_HOOKUP_OBJECT (reservationhotel, label11, "label11");
  GLADE_HOOKUP_OBJECT (reservationhotel, buttonreserverh, "buttonreserverh");
  GLADE_HOOKUP_OBJECT (reservationhotel, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (reservationhotel, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (reservationhotel, image3, "image3");
  GLADE_HOOKUP_OBJECT (reservationhotel, label12, "label12");

  return reservationhotel;
}

GtkWidget*
create_choixreservation (void)
{
  GtkWidget *choixreservation;
  GtkWidget *fixed2;
  GtkWidget *label15;
  GtkWidget *buttonreservationvol;
  GtkWidget *buttonreservationhotel;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label16;
  GtkWidget *buttonafficherreservation;

  choixreservation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (choixreservation, 800, 700);
  gtk_window_set_title (GTK_WINDOW (choixreservation), _("Choix de reservation"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (choixreservation), fixed2);

  label15 = gtk_label_new (_("Choix de reservation"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed2), label15, 300, 80);
  gtk_widget_set_size_request (label15, 200, 25);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);

  buttonreservationvol = gtk_button_new_with_mnemonic (_("Reservation vol"));
  gtk_widget_show (buttonreservationvol);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonreservationvol, 300, 272);
  gtk_widget_set_size_request (buttonreservationvol, 200, 40);

  buttonreservationhotel = gtk_button_new ();
  gtk_widget_show (buttonreservationhotel);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonreservationhotel, 300, 176);
  gtk_widget_set_size_request (buttonreservationhotel, 200, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (buttonreservationhotel), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("Reservation hotel"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox4), label16, FALSE, FALSE, 0);

  buttonafficherreservation = gtk_button_new_with_mnemonic (_("Afficher mes reservations"));
  gtk_widget_show (buttonafficherreservation);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonafficherreservation, 300, 360);
  gtk_widget_set_size_request (buttonafficherreservation, 200, 40);

  g_signal_connect ((gpointer) choixreservation, "destroy",
                    G_CALLBACK (on_choixreservation_destroy),
                    NULL);
  g_signal_connect ((gpointer) buttonreservationvol, "clicked",
                    G_CALLBACK (on_buttonreservationvol_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonreservationhotel, "clicked",
                    G_CALLBACK (on_buttonreservationhotel_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonafficherreservation, "clicked",
                    G_CALLBACK (on_buttonafficherreservation_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (choixreservation, choixreservation, "choixreservation");
  GLADE_HOOKUP_OBJECT (choixreservation, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (choixreservation, label15, "label15");
  GLADE_HOOKUP_OBJECT (choixreservation, buttonreservationvol, "buttonreservationvol");
  GLADE_HOOKUP_OBJECT (choixreservation, buttonreservationhotel, "buttonreservationhotel");
  GLADE_HOOKUP_OBJECT (choixreservation, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (choixreservation, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (choixreservation, image4, "image4");
  GLADE_HOOKUP_OBJECT (choixreservation, label16, "label16");
  GLADE_HOOKUP_OBJECT (choixreservation, buttonafficherreservation, "buttonafficherreservation");

  return choixreservation;
}

GtkWidget*
create_reservationvol (void)
{
  GtkWidget *reservationvol;
  GtkWidget *fixed3;
  GtkObject *jour_adj;
  GtkWidget *jour;
  GtkObject *mois_adj;
  GtkWidget *mois;
  GtkObject *annee_adj;
  GtkWidget *annee;
  GtkWidget *entryprixmax;
  GtkWidget *treeview2;
  GtkWidget *retourv;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label28;
  GtkWidget *labelreservationvol;
  GtkWidget *labelregiondepart;
  GtkWidget *labelprixmax;
  GtkWidget *labelclasse;
  GtkWidget *reserverv;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label29;
  GtkWidget *labeldatedepart;
  GtkWidget *labeljour;
  GtkWidget *labelmois;
  GtkWidget *labelannee;
  GtkWidget *labelregionarrivee;
  GtkWidget *rechercherv;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label25;
  GtkWidget *comboboxregionarrivee;
  GtkWidget *comboboxregiondepart;
  GtkWidget *comboboxclasse;
  GtkWidget *labelnbplace;
  GtkWidget *comboboxplace;

  reservationvol = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (reservationvol, 800, 700);
  gtk_window_set_title (GTK_WINDOW (reservationvol), _("Reservation Vol"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (reservationvol), fixed3);

  jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jour = gtk_spin_button_new (GTK_ADJUSTMENT (jour_adj), 1, 0);
  gtk_widget_show (jour);
  gtk_fixed_put (GTK_FIXED (fixed3), jour, 472, 72);
  gtk_widget_set_size_request (jour, 60, 27);

  mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  mois = gtk_spin_button_new (GTK_ADJUSTMENT (mois_adj), 1, 0);
  gtk_widget_show (mois);
  gtk_fixed_put (GTK_FIXED (fixed3), mois, 592, 72);
  gtk_widget_set_size_request (mois, 60, 27);

  annee_adj = gtk_adjustment_new (2019, 2019, 2050, 1, 10, 10);
  annee = gtk_spin_button_new (GTK_ADJUSTMENT (annee_adj), 1, 0);
  gtk_widget_show (annee);
  gtk_fixed_put (GTK_FIXED (fixed3), annee, 720, 72);
  gtk_widget_set_size_request (annee, 60, 27);

  entryprixmax = gtk_entry_new ();
  gtk_widget_show (entryprixmax);
  gtk_fixed_put (GTK_FIXED (fixed3), entryprixmax, 168, 72);
  gtk_widget_set_size_request (entryprixmax, 100, 25);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprixmax), 8226);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview2, 250, 288);
  gtk_widget_set_size_request (treeview2, 300, 200);

  retourv = gtk_button_new ();
  gtk_widget_show (retourv);
  gtk_fixed_put (GTK_FIXED (fixed3), retourv, 152, 528);
  gtk_widget_set_size_request (retourv, 100, 29);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (retourv), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox6), label28, FALSE, FALSE, 0);

  labelreservationvol = gtk_label_new (_("Reservation vol"));
  gtk_widget_show (labelreservationvol);
  gtk_fixed_put (GTK_FIXED (fixed3), labelreservationvol, 288, 16);
  gtk_widget_set_size_request (labelreservationvol, 200, 25);

  labelregiondepart = gtk_label_new (_("Region de depart"));
  gtk_widget_show (labelregiondepart);
  gtk_fixed_put (GTK_FIXED (fixed3), labelregiondepart, 16, 120);
  gtk_widget_set_size_request (labelregiondepart, 150, 25);
  gtk_misc_set_alignment (GTK_MISC (labelregiondepart), 0, 0.5);

  labelprixmax = gtk_label_new (_("prix max"));
  gtk_widget_show (labelprixmax);
  gtk_fixed_put (GTK_FIXED (fixed3), labelprixmax, 16, 72);
  gtk_widget_set_size_request (labelprixmax, 100, 25);
  gtk_misc_set_alignment (GTK_MISC (labelprixmax), 0, 0.5);

  labelclasse = gtk_label_new (_("Classe"));
  gtk_widget_show (labelclasse);
  gtk_fixed_put (GTK_FIXED (fixed3), labelclasse, 16, 168);
  gtk_widget_set_size_request (labelclasse, 130, 25);
  gtk_misc_set_alignment (GTK_MISC (labelclasse), 0, 0.5);

  reserverv = gtk_button_new ();
  gtk_widget_show (reserverv);
  gtk_fixed_put (GTK_FIXED (fixed3), reserverv, 552, 528);
  gtk_widget_set_size_request (reserverv, 100, 29);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (reserverv), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("Reserver"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox7), label29, FALSE, FALSE, 0);

  labeldatedepart = gtk_label_new (_("Date de depart"));
  gtk_widget_show (labeldatedepart);
  gtk_fixed_put (GTK_FIXED (fixed3), labeldatedepart, 304, 72);
  gtk_widget_set_size_request (labeldatedepart, 100, 25);
  gtk_misc_set_alignment (GTK_MISC (labeldatedepart), 0, 0.5);

  labeljour = gtk_label_new (_("Jour :"));
  gtk_widget_show (labeljour);
  gtk_fixed_put (GTK_FIXED (fixed3), labeljour, 416, 72);
  gtk_widget_set_size_request (labeljour, 50, 25);
  gtk_misc_set_alignment (GTK_MISC (labeljour), 0, 0.5);

  labelmois = gtk_label_new (_("Mois :"));
  gtk_widget_show (labelmois);
  gtk_fixed_put (GTK_FIXED (fixed3), labelmois, 536, 72);
  gtk_widget_set_size_request (labelmois, 50, 25);

  labelannee = gtk_label_new (_("Annee :"));
  gtk_widget_show (labelannee);
  gtk_fixed_put (GTK_FIXED (fixed3), labelannee, 656, 72);
  gtk_widget_set_size_request (labelannee, 60, 25);
  gtk_misc_set_alignment (GTK_MISC (labelannee), 0, 0.5);

  labelregionarrivee = gtk_label_new (_("Region d'arrivee"));
  gtk_widget_show (labelregionarrivee);
  gtk_fixed_put (GTK_FIXED (fixed3), labelregionarrivee, 304, 120);
  gtk_widget_set_size_request (labelregionarrivee, 150, 25);
  gtk_misc_set_alignment (GTK_MISC (labelregionarrivee), 0, 0.5);

  rechercherv = gtk_button_new ();
  gtk_widget_show (rechercherv);
  gtk_fixed_put (GTK_FIXED (fixed3), rechercherv, 328, 224);
  gtk_widget_set_size_request (rechercherv, 120, 30);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (rechercherv), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox5), label25, FALSE, FALSE, 0);

  comboboxregionarrivee = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxregionarrivee);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxregionarrivee, 472, 120);
  gtk_widget_set_size_request (comboboxregionarrivee, 100, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxregionarrivee), _("Sousse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxregionarrivee), _("Tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxregionarrivee), _("Sfax"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxregionarrivee), _("Hammamet"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxregionarrivee), _("Djerba"));

  comboboxregiondepart = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxregiondepart);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxregiondepart, 168, 120);
  gtk_widget_set_size_request (comboboxregiondepart, 100, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxregiondepart), _("Sousse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxregiondepart), _("Tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxregiondepart), _("Sfax"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxregiondepart), _("Hammamet"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxregiondepart), _("Djerba"));

  comboboxclasse = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxclasse);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxclasse, 168, 168);
  gtk_widget_set_size_request (comboboxclasse, 100, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxclasse), _("Bussiness"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxclasse), _("Eco"));

  labelnbplace = gtk_label_new (_("Nombre de place"));
  gtk_widget_show (labelnbplace);
  gtk_fixed_put (GTK_FIXED (fixed3), labelnbplace, 304, 168);
  gtk_widget_set_size_request (labelnbplace, 150, 25);
  gtk_misc_set_alignment (GTK_MISC (labelnbplace), 0, 0.5);

  comboboxplace = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxplace);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxplace, 472, 168);
  gtk_widget_set_size_request (comboboxplace, 100, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxplace), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxplace), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxplace), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxplace), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxplace), _("5"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxplace), _("6"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxplace), _("7"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxplace), _("8"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxplace), _("9"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxplace), _("10"));

  g_signal_connect ((gpointer) reservationvol, "destroy",
                    G_CALLBACK (on_reservationvol_destroy),
                    NULL);
  g_signal_connect ((gpointer) retourv, "clicked",
                    G_CALLBACK (on_retourv_clicked),
                    NULL);
  g_signal_connect ((gpointer) reserverv, "clicked",
                    G_CALLBACK (on_reserverv_clicked),
                    NULL);
  g_signal_connect ((gpointer) rechercherv, "clicked",
                    G_CALLBACK (on_rechercherv_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (reservationvol, reservationvol, "reservationvol");
  GLADE_HOOKUP_OBJECT (reservationvol, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (reservationvol, jour, "jour");
  GLADE_HOOKUP_OBJECT (reservationvol, mois, "mois");
  GLADE_HOOKUP_OBJECT (reservationvol, annee, "annee");
  GLADE_HOOKUP_OBJECT (reservationvol, entryprixmax, "entryprixmax");
  GLADE_HOOKUP_OBJECT (reservationvol, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (reservationvol, retourv, "retourv");
  GLADE_HOOKUP_OBJECT (reservationvol, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (reservationvol, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (reservationvol, image6, "image6");
  GLADE_HOOKUP_OBJECT (reservationvol, label28, "label28");
  GLADE_HOOKUP_OBJECT (reservationvol, labelreservationvol, "labelreservationvol");
  GLADE_HOOKUP_OBJECT (reservationvol, labelregiondepart, "labelregiondepart");
  GLADE_HOOKUP_OBJECT (reservationvol, labelprixmax, "labelprixmax");
  GLADE_HOOKUP_OBJECT (reservationvol, labelclasse, "labelclasse");
  GLADE_HOOKUP_OBJECT (reservationvol, reserverv, "reserverv");
  GLADE_HOOKUP_OBJECT (reservationvol, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (reservationvol, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (reservationvol, image7, "image7");
  GLADE_HOOKUP_OBJECT (reservationvol, label29, "label29");
  GLADE_HOOKUP_OBJECT (reservationvol, labeldatedepart, "labeldatedepart");
  GLADE_HOOKUP_OBJECT (reservationvol, labeljour, "labeljour");
  GLADE_HOOKUP_OBJECT (reservationvol, labelmois, "labelmois");
  GLADE_HOOKUP_OBJECT (reservationvol, labelannee, "labelannee");
  GLADE_HOOKUP_OBJECT (reservationvol, labelregionarrivee, "labelregionarrivee");
  GLADE_HOOKUP_OBJECT (reservationvol, rechercherv, "rechercherv");
  GLADE_HOOKUP_OBJECT (reservationvol, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (reservationvol, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (reservationvol, image5, "image5");
  GLADE_HOOKUP_OBJECT (reservationvol, label25, "label25");
  GLADE_HOOKUP_OBJECT (reservationvol, comboboxregionarrivee, "comboboxregionarrivee");
  GLADE_HOOKUP_OBJECT (reservationvol, comboboxregiondepart, "comboboxregiondepart");
  GLADE_HOOKUP_OBJECT (reservationvol, comboboxclasse, "comboboxclasse");
  GLADE_HOOKUP_OBJECT (reservationvol, labelnbplace, "labelnbplace");
  GLADE_HOOKUP_OBJECT (reservationvol, comboboxplace, "comboboxplace");

  return reservationvol;
}

GtkWidget*
create_mesreservations (void)
{
  GtkWidget *mesreservations;
  GtkWidget *fixed4;
  GtkWidget *treeview3;
  GtkWidget *labeltitre;
  GtkWidget *buttonaffichemesresev;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label38;
  GtkWidget *label37;
  GtkWidget *labelaideresv;
  GtkWidget *buttonpayer;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label36;
  GtkWidget *buttonretourr;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label31;
  GtkWidget *buttonupdateresev;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label32;
  GtkWidget *buttonsupprimerreserv;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label33;
  GtkWidget *labelerreurreservation;

  mesreservations = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (mesreservations, 800, 700);
  gtk_window_set_title (GTK_WINDOW (mesreservations), _("mesreservations"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (mesreservations), fixed4);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_fixed_put (GTK_FIXED (fixed4), treeview3, 25, 232);
  gtk_widget_set_size_request (treeview3, 750, 200);

  labeltitre = gtk_label_new (_("La liste de vos reservations"));
  gtk_widget_show (labeltitre);
  gtk_fixed_put (GTK_FIXED (fixed4), labeltitre, 300, 88);
  gtk_widget_set_size_request (labeltitre, 200, 25);

  buttonaffichemesresev = gtk_button_new ();
  gtk_widget_show (buttonaffichemesresev);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonaffichemesresev, 320, 120);
  gtk_widget_set_size_request (buttonaffichemesresev, 170, 30);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (buttonaffichemesresev), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-print", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_("Afficher Reservation"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox12), label38, FALSE, FALSE, 0);

  label37 = gtk_label_new (_("*Double-cliquez une ligne pour l'a s\303\251lection\303\251e"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed4), label37, 100, 180);
  gtk_widget_set_size_request (label37, 350, 25);
  gtk_misc_set_alignment (GTK_MISC (label37), 0, 0.5);

  labelaideresv = gtk_label_new ("");
  gtk_widget_show (labelaideresv);
  gtk_fixed_put (GTK_FIXED (fixed4), labelaideresv, 100, 456);
  gtk_widget_set_size_request (labelaideresv, 500, 25);
  gtk_misc_set_alignment (GTK_MISC (labelaideresv), 0, 0.5);

  buttonpayer = gtk_button_new ();
  gtk_widget_show (buttonpayer);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonpayer, 344, 584);
  gtk_widget_set_size_request (buttonpayer, 100, 30);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (buttonpayer), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("Payer"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox11), label36, FALSE, FALSE, 0);

  buttonretourr = gtk_button_new ();
  gtk_widget_show (buttonretourr);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonretourr, 592, 584);
  gtk_widget_set_size_request (buttonretourr, 100, 30);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (buttonretourr), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox8), label31, FALSE, FALSE, 0);

  buttonupdateresev = gtk_button_new ();
  gtk_widget_show (buttonupdateresev);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonupdateresev, 88, 584);
  gtk_widget_set_size_request (buttonupdateresev, 100, 30);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (buttonupdateresev), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox9), label32, FALSE, FALSE, 0);

  buttonsupprimerreserv = gtk_button_new ();
  gtk_widget_show (buttonsupprimerreserv);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonsupprimerreserv, 344, 640);
  gtk_widget_set_size_request (buttonsupprimerreserv, 100, 30);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (buttonsupprimerreserv), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox10), label33, FALSE, FALSE, 0);

  labelerreurreservation = gtk_label_new ("");
  gtk_widget_show (labelerreurreservation);
  gtk_fixed_put (GTK_FIXED (fixed4), labelerreurreservation, 296, 552);
  gtk_widget_set_size_request (labelerreurreservation, 200, 25);
  gtk_misc_set_alignment (GTK_MISC (labelerreurreservation), 0, 0.5);

  g_signal_connect ((gpointer) mesreservations, "destroy",
                    G_CALLBACK (on_mesreservations_destroy),
                    NULL);
  g_signal_connect ((gpointer) buttonaffichemesresev, "clicked",
                    G_CALLBACK (on_buttonaffichemesresev_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonpayer, "clicked",
                    G_CALLBACK (on_buttonpayer_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonretourr, "clicked",
                    G_CALLBACK (on_buttonretourr_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonupdateresev, "clicked",
                    G_CALLBACK (on_buttonupdateresev_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonsupprimerreserv, "clicked",
                    G_CALLBACK (on_buttonsupprimerreserv_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mesreservations, mesreservations, "mesreservations");
  GLADE_HOOKUP_OBJECT (mesreservations, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (mesreservations, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (mesreservations, labeltitre, "labeltitre");
  GLADE_HOOKUP_OBJECT (mesreservations, buttonaffichemesresev, "buttonaffichemesresev");
  GLADE_HOOKUP_OBJECT (mesreservations, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (mesreservations, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (mesreservations, image12, "image12");
  GLADE_HOOKUP_OBJECT (mesreservations, label38, "label38");
  GLADE_HOOKUP_OBJECT (mesreservations, label37, "label37");
  GLADE_HOOKUP_OBJECT (mesreservations, labelaideresv, "labelaideresv");
  GLADE_HOOKUP_OBJECT (mesreservations, buttonpayer, "buttonpayer");
  GLADE_HOOKUP_OBJECT (mesreservations, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (mesreservations, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (mesreservations, image11, "image11");
  GLADE_HOOKUP_OBJECT (mesreservations, label36, "label36");
  GLADE_HOOKUP_OBJECT (mesreservations, buttonretourr, "buttonretourr");
  GLADE_HOOKUP_OBJECT (mesreservations, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (mesreservations, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (mesreservations, image8, "image8");
  GLADE_HOOKUP_OBJECT (mesreservations, label31, "label31");
  GLADE_HOOKUP_OBJECT (mesreservations, buttonupdateresev, "buttonupdateresev");
  GLADE_HOOKUP_OBJECT (mesreservations, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (mesreservations, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (mesreservations, image9, "image9");
  GLADE_HOOKUP_OBJECT (mesreservations, label32, "label32");
  GLADE_HOOKUP_OBJECT (mesreservations, buttonsupprimerreserv, "buttonsupprimerreserv");
  GLADE_HOOKUP_OBJECT (mesreservations, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (mesreservations, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (mesreservations, image10, "image10");
  GLADE_HOOKUP_OBJECT (mesreservations, label33, "label33");
  GLADE_HOOKUP_OBJECT (mesreservations, labelerreurreservation, "labelerreurreservation");

  return mesreservations;
}

GtkWidget*
create_windowsuppresion (void)
{
  GtkWidget *windowsuppresion;
  GtkWidget *fixed5;
  GtkWidget *radiobutton2;
  GSList *radiobutton2_group = NULL;
  GtkWidget *radiobutton1;
  GtkWidget *labelconfirmersup;
  GtkWidget *buttonconfsup;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label41;

  windowsuppresion = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowsuppresion, 500, 300);
  gtk_window_set_title (GTK_WINDOW (windowsuppresion), _("Supprimer"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (windowsuppresion), fixed5);

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("non"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton2, 200, 168);
  gtk_widget_set_size_request (radiobutton2, 100, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton2_group);
  radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("oui"));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton1, 200, 120);
  gtk_widget_set_size_request (radiobutton1, 100, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton2_group);
  radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  labelconfirmersup = gtk_label_new (_("Voulez vous vraiment supprimer votre reservation \npour l'hotel?"));
  gtk_widget_show (labelconfirmersup);
  gtk_fixed_put (GTK_FIXED (fixed5), labelconfirmersup, 50, 56);
  gtk_widget_set_size_request (labelconfirmersup, 400, 50);
  gtk_misc_set_alignment (GTK_MISC (labelconfirmersup), 0, 0.5);

  buttonconfsup = gtk_button_new ();
  gtk_widget_show (buttonconfsup);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonconfsup, 200, 232);
  gtk_widget_set_size_request (buttonconfsup, 100, 30);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (buttonconfsup), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("confirmer"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox13), label41, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) windowsuppresion, "destroy",
                    G_CALLBACK (on_windowsuppresion_destroy),
                    NULL);
  g_signal_connect ((gpointer) buttonconfsup, "clicked",
                    G_CALLBACK (on_buttonconfsup_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowsuppresion, windowsuppresion, "windowsuppresion");
  GLADE_HOOKUP_OBJECT (windowsuppresion, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (windowsuppresion, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (windowsuppresion, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (windowsuppresion, labelconfirmersup, "labelconfirmersup");
  GLADE_HOOKUP_OBJECT (windowsuppresion, buttonconfsup, "buttonconfsup");
  GLADE_HOOKUP_OBJECT (windowsuppresion, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (windowsuppresion, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (windowsuppresion, image13, "image13");
  GLADE_HOOKUP_OBJECT (windowsuppresion, label41, "label41");

  return windowsuppresion;
}

GtkWidget*
create_windowmodification (void)
{
  GtkWidget *windowmodification;
  GtkWidget *fixed6;
  GtkWidget *calendar2;
  GtkWidget *label42;
  GtkObject *spinbuttonmodifienbchambre_adj;
  GtkWidget *spinbuttonmodifienbchambre;
  GtkObject *spinbuttonmodifienbnuit_adj;
  GtkWidget *spinbuttonmodifienbnuit;
  GtkWidget *label44;
  GtkWidget *label43;
  GtkWidget *label45;
  GtkWidget *buttonmodifierannuler;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label47;
  GtkWidget *buttonmodifieconf;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label46;
  GtkWidget *comboboxmodifipension;

  windowmodification = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowmodification, 500, 400);
  gtk_window_set_title (GTK_WINDOW (windowmodification), _("Modification"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (windowmodification), fixed6);

  calendar2 = gtk_calendar_new ();
  gtk_widget_show (calendar2);
  gtk_fixed_put (GTK_FIXED (fixed6), calendar2, 32, 40);
  gtk_widget_set_size_request (calendar2, 200, 180);
  gtk_calendar_display_options (GTK_CALENDAR (calendar2),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  label42 = gtk_label_new (_("*Double-cliquez pour s\303\251lectionner\nune date"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed6), label42, 248, 48);
  gtk_widget_set_size_request (label42, 250, 50);

  spinbuttonmodifienbchambre_adj = gtk_adjustment_new (1, 1, 10, 1, 10, 10);
  spinbuttonmodifienbchambre = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmodifienbchambre_adj), 1, 0);
  gtk_widget_show (spinbuttonmodifienbchambre);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbuttonmodifienbchambre, 144, 248);
  gtk_widget_set_size_request (spinbuttonmodifienbchambre, 100, 25);

  spinbuttonmodifienbnuit_adj = gtk_adjustment_new (1, 1, 10, 1, 10, 10);
  spinbuttonmodifienbnuit = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmodifienbnuit_adj), 1, 0);
  gtk_widget_show (spinbuttonmodifienbnuit);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbuttonmodifienbnuit, 144, 288);
  gtk_widget_set_size_request (spinbuttonmodifienbnuit, 100, 25);

  label44 = gtk_label_new (_("Nb nuit :"));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed6), label44, 32, 288);
  gtk_widget_set_size_request (label44, 100, 25);
  gtk_misc_set_alignment (GTK_MISC (label44), 0, 0.5);

  label43 = gtk_label_new (_("Nb chambre :"));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed6), label43, 32, 248);
  gtk_widget_set_size_request (label43, 100, 25);
  gtk_misc_set_alignment (GTK_MISC (label43), 0, 0.5);

  label45 = gtk_label_new (_("Pension :"));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed6), label45, 264, 248);
  gtk_widget_set_size_request (label45, 80, 25);
  gtk_misc_set_alignment (GTK_MISC (label45), 0, 0.5);

  buttonmodifierannuler = gtk_button_new ();
  gtk_widget_show (buttonmodifierannuler);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonmodifierannuler, 64, 352);
  gtk_widget_set_size_request (buttonmodifierannuler, 100, 29);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (buttonmodifierannuler), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_("annuler"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox15), label47, FALSE, FALSE, 0);

  buttonmodifieconf = gtk_button_new ();
  gtk_widget_show (buttonmodifieconf);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonmodifieconf, 336, 352);
  gtk_widget_set_size_request (buttonmodifieconf, 100, 30);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (buttonmodifieconf), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label46 = gtk_label_new_with_mnemonic (_("confirmer"));
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox14), label46, FALSE, FALSE, 0);

  comboboxmodifipension = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxmodifipension);
  gtk_fixed_put (GTK_FIXED (fixed6), comboboxmodifipension, 344, 248);
  gtk_widget_set_size_request (comboboxmodifipension, 100, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxmodifipension), _("1/2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxmodifipension), _("complete"));

  g_signal_connect ((gpointer) calendar2, "day_selected",
                    G_CALLBACK (on_calendar2_day_selected),
                    NULL);
  g_signal_connect ((gpointer) buttonmodifierannuler, "clicked",
                    G_CALLBACK (on_buttonmodifierannuler_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonmodifieconf, "clicked",
                    G_CALLBACK (on_buttonmodifieconf_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowmodification, windowmodification, "windowmodification");
  GLADE_HOOKUP_OBJECT (windowmodification, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (windowmodification, calendar2, "calendar2");
  GLADE_HOOKUP_OBJECT (windowmodification, label42, "label42");
  GLADE_HOOKUP_OBJECT (windowmodification, spinbuttonmodifienbchambre, "spinbuttonmodifienbchambre");
  GLADE_HOOKUP_OBJECT (windowmodification, spinbuttonmodifienbnuit, "spinbuttonmodifienbnuit");
  GLADE_HOOKUP_OBJECT (windowmodification, label44, "label44");
  GLADE_HOOKUP_OBJECT (windowmodification, label43, "label43");
  GLADE_HOOKUP_OBJECT (windowmodification, label45, "label45");
  GLADE_HOOKUP_OBJECT (windowmodification, buttonmodifierannuler, "buttonmodifierannuler");
  GLADE_HOOKUP_OBJECT (windowmodification, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (windowmodification, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (windowmodification, image15, "image15");
  GLADE_HOOKUP_OBJECT (windowmodification, label47, "label47");
  GLADE_HOOKUP_OBJECT (windowmodification, buttonmodifieconf, "buttonmodifieconf");
  GLADE_HOOKUP_OBJECT (windowmodification, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (windowmodification, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (windowmodification, image14, "image14");
  GLADE_HOOKUP_OBJECT (windowmodification, label46, "label46");
  GLADE_HOOKUP_OBJECT (windowmodification, comboboxmodifipension, "comboboxmodifipension");

  return windowmodification;
}






































































	extern hotel tab1[100],tab_dispo[100];
	extern struct reservationhotel tab2[100];
	extern int nb_hotel,nb_hotel_resv,nb_hotel_dispo,creation_colonne1,creation_colonne2;
	extern reservationhotel recherche;
	
	//quand le user va se connecter j'aurais sa cni
	
	extern char *cni_connect;
	extern int nb_resv_user;
	
	//lid de le reservation qui sera sélectionée
	extern int id_resev_selec;
	
	//resoudre le pb de rafraichissment
	extern GtkListStore *store1;
	extern GtkListStore *store2;

	//la date
	extern int jour_local;
	extern int mois_local;
	extern int annee_local;


	


/*************************************************************************************************************************/
void on_buttonreservationhotel_clicked(GtkWidget *objet,gpointer user_data)
{
	//pour que les colomuns saffichent
	creation_colonne1 = 0;
	creation_colonne2 = 0;

	GtkWidget *fenetrehotel,*fenetrechoix;
	
	fenetrechoix = lookup_widget(objet,"choixreservation");
	gtk_widget_destroy(fenetrechoix);
	
	fenetrehotel = create_reservationhotel();
	gtk_widget_show(fenetrehotel);


}

void on_buttonrechercherh_clicked(GtkWidget *objet,gpointer user_data)
{	


	//recuperons la date systeme

    recherche.dt_res.jour = jour_local;
    recherche.dt_res.mois = mois_local;
    recherche.dt_res.annee = annee_local;
    
    //controlons le calendrier
    GtkWidget *aidedate1;
    aidedate1 = lookup_widget(objet,"labelerreurdate");
    int test_date_valide;
    

    
    //je teste si la date est valide
    test_date_valide = is_date_valide(recherche.dt_res,recherche.arrive);
    
    if(!test_date_valide){
    	//if(store1 != NULL)
    		gtk_list_store_clear(store1);
    	gtk_label_set_markup(GTK_LABEL(aidedate1),"<span foreground = \"#FF0000\" weight=\"bold\">*Sélectionnez une date valide!!!</span>");
    }
    else{//si tout va bien on lui affiche les recherches
    
    //on enleve tout potentiel message d'erreur
    gtk_label_set_text(GTK_LABEL(aidedate1),"");
    
		GtkWidget *combobox1;
		GtkWidget *combobox2;
		GtkWidget *combobox3;
		GtkWidget *input1,*input2,*input3,*aide1;

		int i;

		
		char prixmax[10],standing[6],pension[10];
		int Prixmax;

		
		input2 = lookup_widget (objet,"nbnuit");
		input3 = lookup_widget (objet,"nbchambre");

		combobox1 = lookup_widget(objet,"comboboxregion");
		combobox2 = lookup_widget(objet,"comboboxpension");
		combobox3 = lookup_widget(objet,"nbetoile");

		input1 = lookup_widget (objet,"entryprixmax");
		

		//j'enregistre dans des chaines de caracteres ensuite je vais les convertir en int pour exploiter
		strcpy(prixmax,gtk_entry_get_text(GTK_ENTRY(input1)));
		
		//eviter coredumped
		if(strcmp(prixmax,"") == 0){
			recherche.prix = 1000;
		}
		else{
			Prixmax = atoi(prixmax);
			recherche.prix = Prixmax;
		}

		
		recherche.nb_nuit = gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(input2));
		recherche.nb_chambre = gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(input3));
		recherche.standing = gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(combobox3));
		
		if (gtk_combo_box_get_active (GTK_COMBO_BOX(combobox1)) != -1 )
			strcpy(recherche.region,gtk_combo_box_get_active_text(GTK_COMBO_BOX(combobox1)));
		else
			strcpy(recherche.region,"tunisie");
		
		
		//occupons nous de la pension
		
		recherche.pension = 1; // par defaut la pension est complète
		if (gtk_combo_box_get_active(GTK_COMBO_BOX(combobox2)) == 0){
			strcpy(pension,gtk_combo_box_get_active_text(GTK_COMBO_BOX(combobox2)));
			recherche.pension = 0;
		}
		

		// l'id cest le nombre d'éléments dans le fichier hotel reservé avec l'id connecté
		recherche.id = nb_resv_user;
		
		//nous cherchons le nombre d'hotel dispo en fonction des critères
		nb_hotel_dispo = tab_hotels_dispo(tab1,nb_hotel,tab_dispo,recherche);
		
		//nous implementons le signal row-activated
		GtkWidget *treeview;
		treeview = lookup_widget(objet,"treeview1");
		g_signal_connect(treeview, "row-activated", (GCallback) view_onRowActivated, NULL);
		//je cree les colonnes une seule fois
		if(creation_colonne1 == 0){
			GtkCellRenderer *renderer;
			GtkTreeViewColumn *column;
					
			renderer = gtk_cell_renderer_pixbuf_new();
			column = gtk_tree_view_column_new_with_attributes(" Apercu",renderer,"pixbuf",IMG,NULL);
			gtk_tree_view_append_column(GTK_TREE_VIEW(treeview),column);
		
			renderer = gtk_cell_renderer_text_new();
			column = gtk_tree_view_column_new_with_attributes(" Region",renderer,"text",REGION,NULL);
			gtk_tree_view_append_column(GTK_TREE_VIEW(treeview),column);
			
			renderer = gtk_cell_renderer_text_new();
			column = gtk_tree_view_column_new_with_attributes(" Nom",renderer,"text",NOM,NULL);
			gtk_tree_view_append_column(GTK_TREE_VIEW(treeview),column);
			
			renderer = gtk_cell_renderer_text_new();
			column = gtk_tree_view_column_new_with_attributes(" Standing",renderer,"text",STANDING,NULL);
			gtk_tree_view_append_column(GTK_TREE_VIEW(treeview),column);
			
			renderer = gtk_cell_renderer_text_new();
			column = gtk_tree_view_column_new_with_attributes(" Prix",renderer,"text",PRIX,NULL);
			gtk_tree_view_append_column(GTK_TREE_VIEW(treeview),column);
			
			creation_colonne1++;
		}
				  

		
		//affichage du treeview
		view_search_hotel(tab_dispo,nb_hotel_dispo,GTK_TREE_VIEW(treeview),store1,recherche.pension);

		//affichage des indications au clients
		aide1 = lookup_widget(objet,"labelaide1");
		gtk_label_set_text(GTK_LABEL(aide1),"*Double-cliquez sur une\nligne pour l'a sélectionée");
	}
}



/*oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*/
void on_buttonretourh_clicked(GtkWidget *objet,gpointer user_data)
{
	GtkWidget *fenetrehotel,*fenetrechoix;
	
	fenetrehotel = lookup_widget(objet,"reservationhotel");
	gtk_widget_destroy(fenetrehotel);
	
	fenetrechoix = create_choixreservation();
	gtk_widget_show(fenetrechoix);

}
/*oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*/
//fonction qui permet la selection d'une ligne
void view_onRowActivated (GtkWidget *objet,gpointer user_data){
	
	//avant toute chose je vide le message d'erreur si il etait la
	GtkWidget *aide1;
	aide1 = lookup_widget(objet,"labelerreurhotel");
	gtk_label_set_text(GTK_LABEL(aide1),"");
	
	//je commence le vrai taff...
    GtkWidget *treeview,*aide2;
    char msg[100] = "l'Hotel ";
	treeview = lookup_widget(objet,"treeview1");

	GtkTreeSelection *selection;
    GtkTreeModel     *model;
    GtkTreeIter       iter;
 

  selection = gtk_tree_view_get_selection(GTK_TREE_VIEW(treeview));
  gtk_tree_selection_set_mode (selection,GTK_SELECTION_SINGLE);
  
  if (gtk_tree_selection_get_selected(selection, &model, &iter))
  {
    gchar *name;
    int prix;
    gchar *standing,*region;

	//lorqu'une ligne est cliquée on commence a construire la reservation
    gtk_tree_model_get (model, &iter,REGION,&region,NOM,&name,PRIX,&prix,STANDING,&standing,-1);
    strcpy(recherche.nom,name);
    strcpy(recherche.region,region);
	recherche.prix = prix*recherche.nb_nuit*recherche.nb_chambre;
	recherche.standing = strlen(standing);
	
    g_print ("standing: %d\n",recherche.prix);
    
    aide2 = lookup_widget(objet,"labelaide2");
    strcat(msg,recherche.nom);
    strcat(msg," a été sélectionée cliquez sur reserver");
	gtk_label_set_text(GTK_LABEL(aide2),msg);

    g_free(name);
    g_free(standing);
    g_free(region);
  }

  }
 
/*oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*/ 
  void on_buttonreserverh_clicked(GtkWidget *objet,gpointer user_data)
{
	int a;
	GtkWidget *treeview,*aide2;

	treeview = lookup_widget(objet,"treeview1");
	

	GtkTreeSelection *selection;
    	selection = gtk_tree_view_get_selection(GTK_TREE_VIEW(treeview));
	
	a = my_tree_selection_count_selected_rows (selection);
	
	if(a == 1){
		int i,d;
		strcpy(recherche.CNI,cni_connect);
		recherche.id++;
		
		//ajout de la reservation a tab2
		tab2[nb_hotel_resv] = recherche;
		
		//je diminue le nombre de chambre
		for(i=0;i<nb_hotel;i++){
			if(strcmp(tab1[i].region,recherche.region) == 0 && strcmp(tab1[i].nom,recherche.nom) == 0 )
			{
				tab1[i].nb_chambre[recherche.pension] -= recherche.nb_chambre;
				d = i;
			}
				
		}
		
		//on augmente le nb de reservation totale et le nombre de reservation de l'user connecté
		nb_hotel_resv++;
		nb_resv_user++;
		g_print("tes reserv   %d",nb_resv_user);

		//uppload file
		uploaddatahotel("hotel.txt",tab1,nb_hotel);
		uploaddatareservhotel("hotelreserver.txt",tab2,nb_hotel_resv);
		
		g_print ("chambre restante: %d\n",tab1[d].nb_chambre[recherche.pension]);
		
			
	}
	
	//si il n'a rien sélectionné
	else{
		aide2 = lookup_widget(objet,"labelerreurhotel");
		gtk_label_set_markup(GTK_LABEL(aide2),"<span foreground = \"#FF0000\" weight=\"bold\">*Sélectionnez un hotel !!!</span>");
	}
   
}


/*******************************************************************************************************************************/

//tout sur la fenetre mes reservation
/*************************************************************************************************/
void on_buttonafficherreservation_clicked(GtkWidget *objet,gpointer user_data)
{
	//pour que les colomuns saffichent
	creation_colonne1 = 0;
	creation_colonne2 = 0;
	
	//creation de la fenentre
	GtkWidget *fenetrereserv,*fenetrechoix;
	
	fenetrechoix = lookup_widget(objet,"choixreservation");
	gtk_widget_destroy(fenetrechoix);
	
	fenetrereserv = create_mesreservations();
	gtk_widget_show(fenetrereserv);
}

  
 

void on_buttonupdateresev_clicked(GtkWidget *objet,gpointer user_data)
{
	int a;
	GtkWidget *treeview,*aide2;

	treeview = lookup_widget(objet,"treeview3");
	

	GtkTreeSelection *selection;
    	selection = gtk_tree_view_get_selection(GTK_TREE_VIEW(treeview));
	
	a = my_tree_selection_count_selected_rows (selection);
	
	if(a == 1){
		GtkWidget *fenetremodif,*fenetrechoix;
	
		fenetrechoix = lookup_widget(objet,"mesreservations");
		gtk_widget_destroy(fenetrechoix);
	
		fenetremodif = create_windowmodification();
		gtk_widget_show(fenetremodif);
		
		g_print("ok");
	}
	
	//si il n'a rien sélectionné
	else{
		aide2 = lookup_widget(objet,"labelerreurreservation");
		gtk_label_set_text(GTK_LABEL(aide2),"*Sélectionnez une reservation!!!");
	}


}
/*******************************************************************************************/
//fenetre de modification

void
on_buttonmodifierannuler_clicked(GtkWidget *objet,gpointer user_data)
{
	GtkWidget *fenetremodif,*fenetrechoix;
	
	fenetremodif = lookup_widget(objet,"windowmodification");
	gtk_widget_destroy(fenetremodif);
	
	fenetrechoix = create_choixreservation();
	gtk_widget_show(fenetrechoix);

}


void
on_buttonmodifieconf_clicked(GtkWidget *objet,gpointer user_data)
{	
	GtkWidget *input1,*input2,*combobox;
	char pension[10];

	input1 = lookup_widget (objet,"spinbuttonmodifienbnuit");
	input2 = lookup_widget (objet,"spinbuttonmodifienbchambre");
	combobox = lookup_widget(objet,"comboboxmodifipension");
	
	recherche.nb_nuit = gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(input1));
	recherche.nb_chambre = gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(input2));

	//occupons nous de la pension
	recherche.pension = 1; // par defaut la pension est complète
	if (gtk_combo_box_get_active(GTK_COMBO_BOX(combobox)) == 0){
		strcpy(pension,gtk_combo_box_get_active_text(GTK_COMBO_BOX(combobox)));
		recherche.pension = 0;
	}
	
	//on modifie dans le tableau
	update_reserv_hotel(id_resev_selec,cni_connect,recherche,tab2,nb_hotel_resv);

	//uppload file
	uploaddatareservhotel("hotelreserver.txt",tab2,nb_hotel_resv);
	g_print("dansle file");
	
	//a la fin on retourne
	GtkWidget *fenetremodif,*fenetrechoix;
	
	fenetremodif = lookup_widget(objet,"windowmodification");
	gtk_widget_destroy(fenetremodif);
	
	fenetrechoix = create_choixreservation();
	gtk_widget_show(fenetrechoix);


}
/********************************************************************************************/
/*ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*/

void on_buttonretourr_clicked(GtkWidget *objet,gpointer user_data)
{
	GtkWidget *fenetrereserv,*fenetrechoix;
	
	fenetrereserv = lookup_widget(objet,"mesreservations");
	gtk_widget_destroy(fenetrereserv);
	
	fenetrechoix = create_choixreservation();
	gtk_widget_show(fenetrechoix);

}

/*ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*/
void on_buttonsupprimerreserv_clicked(GtkWidget *objet,gpointer user_data)
{
	int a;
	GtkWidget *treeview,*aide2;

	treeview = lookup_widget(objet,"treeview3");
	

	GtkTreeSelection *selection;
    selection = gtk_tree_view_get_selection(GTK_TREE_VIEW(treeview));
	
	a = my_tree_selection_count_selected_rows (selection);
	
	if(a == 1){
	
		
		GtkWidget *fenetresup,*fenetrechoix;
	
		fenetrechoix = lookup_widget(objet,"mesreservations");
		gtk_widget_destroy(fenetrechoix);
	
		fenetresup = create_windowsuppresion ();
		gtk_widget_show(fenetresup);
		

	}
	
	//si il n'a rien sélectionné
	else{
		aide2 = lookup_widget(objet,"labelerreurreservation");
		gtk_label_set_text(GTK_LABEL(aide2),"*Sélectionnez une reservation!!!");
	}

}
/*ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*/

void on_buttonpayer_clicked(GtkWidget *objet,gpointer user_data)
{
	int a;
	GtkWidget *treeview,*aide2;

	treeview = lookup_widget(objet,"treeview3");
	

	GtkTreeSelection *selection;
        selection = gtk_tree_view_get_selection(GTK_TREE_VIEW(treeview));
	
	a = my_tree_selection_count_selected_rows (selection);
	
	if(a == 1){
		g_print("ok");
	}
	
	//si il n'a rien sélectionné
	else{
		aide2 = lookup_widget(objet,"labelerreurreservation");
		gtk_label_set_text(GTK_LABEL(aide2),"*Sélectionnez une reservation!!!");
	}


}

/*ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*/
void on_buttonaffichemesresev_clicked(GtkWidget *objet,gpointer user_data)
{

	//affichage des reservations
	GtkWidget *treeview;
	treeview = lookup_widget(objet,"treeview3");
	g_signal_connect(treeview, "row-activated", (GCallback) view_onRowActivated_resv, NULL);
	
	//je cree les colonnes une seule fois
	if(creation_colonne2 == 0){
		GtkCellRenderer *renderer;
		GtkTreeViewColumn *column;
		
		renderer = gtk_cell_renderer_text_new();
		column = gtk_tree_view_column_new_with_attributes(" Id",renderer,"text",ID,NULL);
		gtk_tree_view_append_column(GTK_TREE_VIEW(treeview),column);
		
		renderer = gtk_cell_renderer_text_new();
		column = gtk_tree_view_column_new_with_attributes(" Date de reservation",renderer,"text",DATE2,NULL);
		gtk_tree_view_append_column(GTK_TREE_VIEW(treeview),column);
		
		renderer = gtk_cell_renderer_text_new();
		column = gtk_tree_view_column_new_with_attributes(" Date d'arrivé",renderer,"text",DATERES,NULL);
		gtk_tree_view_append_column(GTK_TREE_VIEW(treeview),column);
		
		renderer = gtk_cell_renderer_text_new();
		column = gtk_tree_view_column_new_with_attributes(" Region",renderer,"text",REGION2,NULL);
		gtk_tree_view_append_column(GTK_TREE_VIEW(treeview),column);
		
		renderer = gtk_cell_renderer_text_new();
		column = gtk_tree_view_column_new_with_attributes(" Nom",renderer,"text",NOM2,NULL);
		gtk_tree_view_append_column(GTK_TREE_VIEW(treeview),column);
		
		renderer = gtk_cell_renderer_text_new();
		column = gtk_tree_view_column_new_with_attributes(" Standing",renderer,"text",STANDING2,NULL);
		gtk_tree_view_append_column(GTK_TREE_VIEW(treeview),column);
		
		renderer = gtk_cell_renderer_text_new();
		column = gtk_tree_view_column_new_with_attributes(" Nb chambre",renderer,"text",NBNUIT2,NULL);
		gtk_tree_view_append_column(GTK_TREE_VIEW(treeview),column);
		
		renderer = gtk_cell_renderer_text_new();
		column = gtk_tree_view_column_new_with_attributes(" Nb nuit",renderer,"text",NBCHAMBRE2,NULL);
		gtk_tree_view_append_column(GTK_TREE_VIEW(treeview),column);
		
		renderer = gtk_cell_renderer_text_new();
		column = gtk_tree_view_column_new_with_attributes(" Prix",renderer,"text",PRIX2,NULL);
		gtk_tree_view_append_column(GTK_TREE_VIEW(treeview),column);
		
		
		creation_colonne2++;
	}
		
	
	//affichage du treeview
	view_reserv_hotel(cni_connect,tab2,nb_hotel_resv,GTK_TREE_VIEW(treeview),store2);

}


/*oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*/
//fonction qui permet la selection d'une ligne de reservation
void view_onRowActivated_resv(GtkWidget *objet,gpointer user_data){

	//avant toute chose je vide le message d'erreur si il etait la
	GtkWidget *aide1;
	aide1 = lookup_widget(objet,"labelerreurreservation");
	gtk_label_set_text(GTK_LABEL(aide1),"");	
	
    GtkWidget *treeview,*aide2;
    char msg[] = "**Ligne sélectionée vous pouvez maintenant payer,modifier ou supprimer";
    char number[4];
	int id_resev_selec;
	treeview = lookup_widget(objet,"treeview3");

	GtkTreeSelection *selection;
    GtkTreeModel     *model;
    GtkTreeIter       iter;
 

  selection = gtk_tree_view_get_selection(GTK_TREE_VIEW(treeview));
  gtk_tree_selection_set_mode (selection,GTK_SELECTION_SINGLE);
  
  if (gtk_tree_selection_get_selected(selection, &model, &iter))
  {

	//lorqu'une ligne est cliquée on recupère son id pour gerer la suppression et la modification
    gtk_tree_model_get (model, &iter,ID,&id_resev_selec,-1);
    
    g_print ("standing: %d\n",id_resev_selec);
    
    aide2 = lookup_widget(objet,"labelaideresv");
	gtk_label_set_text(GTK_LABEL(aide2),msg);

  }

  }
 
 
/*oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*/


/******************************************************************************************************************************************/

void
on_buttonreservationvol_clicked(GtkWidget *objet,gpointer user_data){}

void
on_retourv_clicked(GtkWidget *objet,gpointer user_data){}

void
on_rechercherv_clicked(GtkWidget *objet,gpointer user_data){}

void
on_reserverv_clicked(GtkWidget *objet,gpointer user_data){}


void
on_reservationhotel_destroy(GtkWidget *objet,gpointer user_data){}

void
on_choixreservation_destroy(GtkWidget *objet,gpointer user_data){}

void
on_reservationvol_destroy(GtkWidget *objet,gpointer user_data){}
/******************************************************************************************************************************************/
void
on_mesreservations_destroy(GtkWidget *objet,gpointer user_data){
	/*uploaddatahotel("/home/fosso/Projects/reservation1/file/hotel.txt",tab1,nb_hotel);
	uploaddatareservhotel("/home/fosso/Projects/reservation1/file/hotelreserver.txt",tab2,nb_hotel_resv);
	gtk_main_quit();*/
}
/************************************************************************************************************/



//pop up suppression
/*********************************************************************************************************************************/
void
on_windowsuppresion_destroy(GtkWidget *objet,gpointer user_data)
{
	/*GtkWidget *fenetresup,*fenetrechoix;
	
	fenetresup = lookup_widget(objet,"windowsuppresion");
	gtk_widget_destroy(fenetresup);
	
	fenetrechoix = create_choixreservation();
	gtk_widget_show(fenetrechoix);*/

}


void
on_buttonconfsup_clicked(GtkWidget *objet,gpointer user_data)
{
	GtkWidget *r1,*r2;
	int resultat1,resultat2;
	
	r1 = lookup_widget(objet,"radiobutton1");
	r2 = lookup_widget(objet,"radiobutton2");
	
	/*gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (r1), FALSE);
    gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (r2), TRUE);*/
    
    g_signal_connect (GTK_TOGGLE_BUTTON (r1), "toggled", G_CALLBACK (button_toggled_cb), NULL);
    g_signal_connect (GTK_TOGGLE_BUTTON (r2), "toggled", G_CALLBACK (button_toggled_cb), NULL);
    
    resultat1 = button_toggled_cb(r1);
    resultat2 = button_toggled_cb(r2);
    
	if(resultat1){
		g_print("il veut supprimer");
		
		//fontion qui supprime
		delete_reserv_hotel(id_resev_selec,cni_connect,&nb_resv_user,tab2,&nb_hotel_resv);
	
		//uppload file
		uploaddatareservhotel("hotelreserver.txt",tab2,nb_hotel_resv);
	}
		
		
	if(resultat2)
		g_print("il ne veut pas supprimer");
		
	//après tout on retourne	
	GtkWidget *fenetresup,*fenetrechoix;
	
	fenetresup = lookup_widget(objet,"windowsuppresion");
	gtk_widget_destroy(fenetresup);
	
	fenetrechoix = create_choixreservation();
	gtk_widget_show(fenetrechoix);

}









void on_calendar2_day_selected(GtkWidget *objet,gpointer user_data)
{
	//calender
	GtkWidget * calendrier;
	calendrier = lookup_widget(objet,"calendar2");
	gtk_calendar_get_date (GTK_CALENDAR (calendrier),&recherche.arrive.annee,&recherche.arrive.mois,&recherche.arrive.jour);
	recherche.arrive.mois++;
	g_print("%d %d %d\n",recherche.arrive.jour,recherche.arrive.mois,recherche.arrive.annee);

}


void on_calendar1_day_selected(GtkWidget *objet,gpointer user_data)
{
	
	//calender
	GtkWidget * calendrier;
	calendrier = lookup_widget(objet,"calendar1");
	gtk_calendar_get_date (GTK_CALENDAR (calendrier),&recherche.arrive.annee,&recherche.arrive.mois,&recherche.arrive.jour);
	recherche.arrive.mois++;
	g_print("%d %d %d\n",recherche.arrive.jour,recherche.arrive.mois,recherche.arrive.annee);


}

