/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1 (void);
GtkWidget* create_window2 (void);
GtkWidget* create_window3 (void);
GtkWidget* create_window4 (void);
GtkWidget* create_window5 (void);
GtkWidget* create_window6 (void);





void
on_annuler_clicked                     (GtkButton       *button,
                                        gpointer         user_data);

void
on_connexion_clicked                   (GtkWidget       *button,
                                        gpointer         user_data);

void
on_inscription_clicked                 (GtkButton       *button,
                                        gpointer         user_data);

void
on_button_clicked                      (GtkWidget       *objet_graphique,
                                        gpointer         user_data);

void
on_afficher_clicked                    (GtkWidget       *objet,
                                        gpointer         user_data);

void
on_ajouter_clicked                     (GtkWidget       *objet,
                                        gpointer         user_data);

void
on_retour_clicked                      (GtkWidget       *objet,
                                        gpointer         user_data);

void
on_button13_clicked                    (GtkWidget       *objet,
                                        gpointer         user_data);




void
on_supprimer_clicked                   (GtkWidget       *objet,
                                        gpointer         user_data);

void
on_modifier_clicked                      (GtkWidget       *objet,
                                        gpointer         user_data);
void
on_modifierr_clicked                     (GtkWidget       *objet,
                                        gpointer         user_data);

void
on_valider_clicked                      (GtkWidget       *objet,
                                        gpointer         user_data);
void
on_debut_clicked                       (GtkWidget       *objet,
                                        gpointer         user_data);

void
on_confirmer_clicked                   (GtkWidget      *objet,
                                        gpointer         user_data);

void
on_sortie_clicked                      (GtkWidget       *objet,
                                        gpointer         user_data);





