/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interfacehe.h"
#include "support.h"
#include "supporta.h"
#include "employers.h"
#include "fonction.h"
#include "fonctionh.h"
#include "fonctions.h"
#include "interfaceadmin.h"
#include "interface.h"
#include "interfacere.h"
#include "gestionhotel.h"
#include "interfacev.h"
#include "interfacen.h"
#include "gest.h"


#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_espace (void)
{
  GtkWidget *espace;
  GtkWidget *fixed1;
  GtkWidget *notebook1;
  GtkWidget *_;
  GtkWidget *alignment1;
  GtkWidget *notebook2;
  GtkWidget *fixed2;
  GtkWidget *prixnuitee;
  GtkWidget *type_pension;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *prixx;
  GtkWidget *nomhotel;
  GtkWidget *typepension;
  GtkWidget *Nombre;
  GtkWidget *id;
  GtkWidget *labelp__riode;
  GtkWidget *idhebergement;
  GtkWidget *combobox3;
  GtkWidget *combobox1;
  GtkWidget *erreur3;
  GtkWidget *erreur;
  GtkWidget *erreur2;
  GtkWidget *label46;
  GtkWidget *ajouterh;
  GtkWidget *alignment2;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label38;
  GtkWidget *combobox2;
  GtkWidget *labelchambre;
  GtkWidget *labelajouter;
  GtkWidget *fixed8;
  GtkWidget *treeview1h;
  GtkWidget *id1;
  GtkWidget *idhb;
  GtkWidget *afficherh;
  GtkWidget *alignment3;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label39;
  GtkWidget *supprimerh;
  GtkWidget *alignment4;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label40;
  GtkWidget *modifierh;
  GtkWidget *alignment5;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label41;
  GtkWidget *refresh1;
  GtkWidget *alignment7;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label49;
  GtkWidget *retourh;
  GtkWidget *alignment6;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label42;
  GtkWidget *label47;
  GtkWidget *labelafficher;
  GtkWidget *label1;
  GtkWidget *labelh__bergement;
  GtkWidget *deconnexiontaha;
  GtkWidget *alignment10;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label52;
  GtkWidget *reclamationtaha;
  GtkWidget *alignment11;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label53;

  espace = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (espace), _("Espace employ\303\251"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (espace), fixed1);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed1), notebook1, 48, 72);
  gtk_widget_set_size_request (notebook1, 1128, 560);

  _ = gtk_frame_new (NULL);
  gtk_widget_show (_);
  gtk_container_add (GTK_CONTAINER (notebook1), _);
  gtk_frame_set_shadow_type (GTK_FRAME (_), GTK_SHADOW_NONE);

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (_), alignment1);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment1), 0, 0, 12, 0);

  notebook2 = gtk_notebook_new ();
  gtk_widget_show (notebook2);
  gtk_container_add (GTK_CONTAINER (alignment1), notebook2);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed2);

  prixnuitee = gtk_entry_new ();
  gtk_widget_show (prixnuitee);
  gtk_fixed_put (GTK_FIXED (fixed2), prixnuitee, 168, 176);
  gtk_widget_set_size_request (prixnuitee, 80, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (prixnuitee), 8226);

  type_pension = gtk_entry_new ();
  gtk_widget_show (type_pension);
  gtk_fixed_put (GTK_FIXED (fixed2), type_pension, 160, 336);
  gtk_widget_set_size_request (type_pension, 136, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (type_pension), 8226);

  spinbutton1_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton1, 168, 120);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  prixx = gtk_label_new (_("Prix d'une nuit\303\251e :"));
  gtk_widget_show (prixx);
  gtk_fixed_put (GTK_FIXED (fixed2), prixx, 24, 176);
  gtk_widget_set_size_request (prixx, 136, 24);

  nomhotel = gtk_label_new (_("Nom d'hotel :"));
  gtk_widget_show (nomhotel);
  gtk_fixed_put (GTK_FIXED (fixed2), nomhotel, 8, 280);
  gtk_widget_set_size_request (nomhotel, 136, 24);

  typepension = gtk_label_new (_("Type de pension :"));
  gtk_widget_show (typepension);
  gtk_fixed_put (GTK_FIXED (fixed2), typepension, 24, 336);
  gtk_widget_set_size_request (typepension, 120, 24);

  Nombre = gtk_label_new (_("Nombre d'\303\251toiles :"));
  gtk_widget_show (Nombre);
  gtk_fixed_put (GTK_FIXED (fixed2), Nombre, 24, 128);
  gtk_widget_set_size_request (Nombre, 136, 24);

  id = gtk_entry_new ();
  gtk_widget_show (id);
  gtk_fixed_put (GTK_FIXED (fixed2), id, 168, 48);
  gtk_widget_set_size_request (id, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (id), 8226);

  labelp__riode = gtk_label_new (_("Ville:"));
  gtk_widget_show (labelp__riode);
  gtk_fixed_put (GTK_FIXED (fixed2), labelp__riode, 24, 88);
  gtk_widget_set_size_request (labelp__riode, 80, 24);

  idhebergement = gtk_label_new (_("Identite H\303\251bergement :"));
  gtk_widget_show (idhebergement);
  gtk_fixed_put (GTK_FIXED (fixed2), idhebergement, 8, 56);
  gtk_widget_set_size_request (idhebergement, 160, 16);

  combobox3 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox3);
  gtk_fixed_put (GTK_FIXED (fixed2), combobox3, 160, 88);
  gtk_widget_set_size_request (combobox3, 152, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("soussa"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Mahdia"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Tabarka"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Gammarth"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Hammamet"));

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed2), combobox1, 160, 272);
  gtk_widget_set_size_request (combobox1, 208, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Mouradi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Houria"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Pacha"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Sunclub"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Byzance"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Toumana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Zenith"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Lacigale"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Darismail"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Itropika"));
  gtk_combo_box_set_add_tearoffs (GTK_COMBO_BOX (combobox1), TRUE);

  erreur3 = gtk_label_new ("");
  gtk_widget_show (erreur3);
  gtk_fixed_put (GTK_FIXED (fixed2), erreur3, 416, 344);
  gtk_widget_set_size_request (erreur3, 328, 17);

  erreur = gtk_label_new ("");
  gtk_widget_show (erreur);
  gtk_fixed_put (GTK_FIXED (fixed2), erreur, 424, 48);
  gtk_widget_set_size_request (erreur, 208, 25);

  erreur2 = gtk_label_new ("");
  gtk_widget_show (erreur2);
  gtk_fixed_put (GTK_FIXED (fixed2), erreur2, 408, 176);
  gtk_widget_set_size_request (erreur2, 216, 25);

  label46 = gtk_label_new ("");
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed2), label46, 0, 408);
  gtk_widget_set_size_request (label46, 345, 104);

  ajouterh = gtk_button_new ();
  gtk_widget_show (ajouterh);
  gtk_fixed_put (GTK_FIXED (fixed2), ajouterh, 408, 408);
  gtk_widget_set_size_request (ajouterh, 104, 48);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (ajouterh), alignment2);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox1), label38, FALSE, FALSE, 0);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_fixed_put (GTK_FIXED (fixed2), combobox2, 160, 224);
  gtk_widget_set_size_request (combobox2, 200, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("5"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("6"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("7"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("8"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("9"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("13"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("14"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("17"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("18"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("19"));

  labelchambre = gtk_label_new (_("Chambre :"));
  gtk_widget_show (labelchambre);
  gtk_fixed_put (GTK_FIXED (fixed2), labelchambre, 16, 232);
  gtk_widget_set_size_request (labelchambre, 120, 16);

  labelajouter = gtk_label_new (_("Ajouter h\303\251bergement"));
  gtk_widget_show (labelajouter);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), labelajouter);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed8);

  treeview1h = gtk_tree_view_new ();
  gtk_widget_show (treeview1h);
  gtk_fixed_put (GTK_FIXED (fixed8), treeview1h, 16, 56);
  gtk_widget_set_size_request (treeview1h, 616, 416);

  id1 = gtk_entry_new ();
  gtk_widget_show (id1);
  gtk_fixed_put (GTK_FIXED (fixed8), id1, 216, 8);
  gtk_widget_set_size_request (id1, 184, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (id1), 8226);

  idhb = gtk_label_new (_("Identite d'h\303\251bergement"));
  gtk_widget_show (idhb);
  gtk_fixed_put (GTK_FIXED (fixed8), idhb, 24, 8);
  gtk_widget_set_size_request (idhb, 176, 32);

  afficherh = gtk_button_new ();
  gtk_widget_show (afficherh);
  gtk_fixed_put (GTK_FIXED (fixed8), afficherh, 32, 488);
  gtk_widget_set_size_request (afficherh, 136, 45);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (afficherh), alignment3);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox2), label39, FALSE, FALSE, 0);

  supprimerh = gtk_button_new ();
  gtk_widget_show (supprimerh);
  gtk_fixed_put (GTK_FIXED (fixed8), supprimerh, 200, 488);
  gtk_widget_set_size_request (supprimerh, 144, 48);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (supprimerh), alignment4);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox3), label40, FALSE, FALSE, 0);

  modifierh = gtk_button_new ();
  gtk_widget_show (modifierh);
  gtk_fixed_put (GTK_FIXED (fixed8), modifierh, 368, 488);
  gtk_widget_set_size_request (modifierh, 152, 48);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (modifierh), alignment5);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox4), label41, FALSE, FALSE, 0);

  refresh1 = gtk_button_new ();
  gtk_widget_show (refresh1);
  gtk_fixed_put (GTK_FIXED (fixed8), refresh1, 632, 488);
  gtk_widget_set_size_request (refresh1, 168, 45);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (refresh1), alignment7);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label49 = gtk_label_new_with_mnemonic (_("Refresh"));
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox6), label49, FALSE, FALSE, 0);

  retourh = gtk_button_new ();
  gtk_widget_show (retourh);
  gtk_fixed_put (GTK_FIXED (fixed8), retourh, 840, 488);
  gtk_widget_set_size_request (retourh, 232, 48);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (retourh), alignment6);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label42 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox5), label42, FALSE, FALSE, 0);

  label47 = gtk_label_new ("");
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed8), label47, 664, 360);
  gtk_widget_set_size_request (label47, 360, 80);

  labelafficher = gtk_label_new (_("Gestion h\303\251bergement"));
  gtk_widget_show (labelafficher);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), labelafficher);

  label1 = gtk_label_new (_("<b></b>"));
  gtk_widget_show (label1);
  gtk_frame_set_label_widget (GTK_FRAME (_), label1);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);

  labelh__bergement = gtk_label_new (_("H\303\251bergement"));
  gtk_widget_show (labelh__bergement);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), labelh__bergement);

  deconnexiontaha = gtk_button_new ();
  gtk_widget_show (deconnexiontaha);
  gtk_fixed_put (GTK_FIXED (fixed1), deconnexiontaha, 944, 56);
  gtk_widget_set_size_request (deconnexiontaha, 226, 45);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (deconnexiontaha), alignment10);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-disconnect", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label52 = gtk_label_new_with_mnemonic (_("deconnexion"));
  gtk_widget_show (label52);
  gtk_box_pack_start (GTK_BOX (hbox9), label52, FALSE, FALSE, 0);

  reclamationtaha = gtk_button_new ();
  gtk_widget_show (reclamationtaha);
  gtk_fixed_put (GTK_FIXED (fixed1), reclamationtaha, 696, 56);
  gtk_widget_set_size_request (reclamationtaha, 232, 45);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (reclamationtaha), alignment11);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label53 = gtk_label_new_with_mnemonic (_("Reclamation"));
  gtk_widget_show (label53);
  gtk_box_pack_start (GTK_BOX (hbox10), label53, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) ajouterh, "clicked",
                    G_CALLBACK (on_ajouterh_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficherh, "clicked",
                    G_CALLBACK (on_afficherh_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimerh, "clicked",
                    G_CALLBACK (on_supprimerh_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifierh, "clicked",
                    G_CALLBACK (on_modifierh_clicked),
                    NULL);
  g_signal_connect ((gpointer) refresh1, "clicked",
                    G_CALLBACK (on_refresh1_clicked),
                    NULL);
  g_signal_connect ((gpointer) retourh, "clicked",
                    G_CALLBACK (on_retourh_clicked),
                    NULL);
  g_signal_connect ((gpointer) deconnexiontaha, "clicked",
                    G_CALLBACK (on_deconnexiontaha_clicked),
                    NULL);
  g_signal_connect ((gpointer) reclamationtaha, "clicked",
                    G_CALLBACK (on_reclamationtaha_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (espace, espace, "espace");
  GLADE_HOOKUP_OBJECT (espace, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (espace, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (espace, _, "_");
  GLADE_HOOKUP_OBJECT (espace, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (espace, notebook2, "notebook2");
  GLADE_HOOKUP_OBJECT (espace, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (espace, prixnuitee, "prixnuitee");
  GLADE_HOOKUP_OBJECT (espace, type_pension, "type_pension");
  GLADE_HOOKUP_OBJECT (espace, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (espace, prixx, "prixx");
  GLADE_HOOKUP_OBJECT (espace, nomhotel, "nomhotel");
  GLADE_HOOKUP_OBJECT (espace, typepension, "typepension");
  GLADE_HOOKUP_OBJECT (espace, Nombre, "Nombre");
  GLADE_HOOKUP_OBJECT (espace, id, "id");
  GLADE_HOOKUP_OBJECT (espace, labelp__riode, "labelp__riode");
  GLADE_HOOKUP_OBJECT (espace, idhebergement, "idhebergement");
  GLADE_HOOKUP_OBJECT (espace, combobox3, "combobox3");
  GLADE_HOOKUP_OBJECT (espace, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (espace, erreur3, "erreur3");
  GLADE_HOOKUP_OBJECT (espace, erreur, "erreur");
  GLADE_HOOKUP_OBJECT (espace, erreur2, "erreur2");
  GLADE_HOOKUP_OBJECT (espace, label46, "label46");
  GLADE_HOOKUP_OBJECT (espace, ajouterh, "ajouterh");
  GLADE_HOOKUP_OBJECT (espace, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (espace, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (espace, image1, "image1");
  GLADE_HOOKUP_OBJECT (espace, label38, "label38");
  GLADE_HOOKUP_OBJECT (espace, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (espace, labelchambre, "labelchambre");
  GLADE_HOOKUP_OBJECT (espace, labelajouter, "labelajouter");
  GLADE_HOOKUP_OBJECT (espace, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (espace, treeview1h, "treeview1h");
  GLADE_HOOKUP_OBJECT (espace, id1, "id1");
  GLADE_HOOKUP_OBJECT (espace, idhb, "idhb");
  GLADE_HOOKUP_OBJECT (espace, afficherh, "afficherh");
  GLADE_HOOKUP_OBJECT (espace, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (espace, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (espace, image2, "image2");
  GLADE_HOOKUP_OBJECT (espace, label39, "label39");
  GLADE_HOOKUP_OBJECT (espace, supprimerh, "supprimerh");
  GLADE_HOOKUP_OBJECT (espace, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (espace, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (espace, image3, "image3");
  GLADE_HOOKUP_OBJECT (espace, label40, "label40");
  GLADE_HOOKUP_OBJECT (espace, modifierh, "modifierh");
  GLADE_HOOKUP_OBJECT (espace, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (espace, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (espace, image4, "image4");
  GLADE_HOOKUP_OBJECT (espace, label41, "label41");
  GLADE_HOOKUP_OBJECT (espace, refresh1, "refresh1");
  GLADE_HOOKUP_OBJECT (espace, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (espace, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (espace, image6, "image6");
  GLADE_HOOKUP_OBJECT (espace, label49, "label49");
  GLADE_HOOKUP_OBJECT (espace, retourh, "retourh");
  GLADE_HOOKUP_OBJECT (espace, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (espace, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (espace, image5, "image5");
  GLADE_HOOKUP_OBJECT (espace, label42, "label42");
  GLADE_HOOKUP_OBJECT (espace, label47, "label47");
  GLADE_HOOKUP_OBJECT (espace, labelafficher, "labelafficher");
  GLADE_HOOKUP_OBJECT (espace, label1, "label1");
  GLADE_HOOKUP_OBJECT (espace, labelh__bergement, "labelh__bergement");
  GLADE_HOOKUP_OBJECT (espace, deconnexiontaha, "deconnexiontaha");
  GLADE_HOOKUP_OBJECT (espace, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (espace, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (espace, image9, "image9");
  GLADE_HOOKUP_OBJECT (espace, label52, "label52");
  GLADE_HOOKUP_OBJECT (espace, reclamationtaha, "reclamationtaha");
  GLADE_HOOKUP_OBJECT (espace, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (espace, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (espace, image10, "image10");
  GLADE_HOOKUP_OBJECT (espace, label53, "label53");

  return espace;
}

GtkWidget*
create_modifierheb (void)
{
  GtkWidget *modifierheb;
  GtkWidget *fixed9;
  GtkWidget *modetoiless;
  GtkWidget *modpensionn;
  GtkWidget *modnomm;
  GtkWidget *modidd;
  GtkWidget *modid;
  GtkWidget *modprix;
  GtkObject *modspinbutton_adj;
  GtkWidget *modspinbutton;
  GtkWidget *modpension;
  GtkWidget *modvillee;
  GtkWidget *modcomboboxh;
  GtkWidget *idd;
  GtkWidget *modcomboboxa;
  GtkWidget *label48;
  GtkWidget *modifierf;
  GtkWidget *alignment8;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label50;
  GtkWidget *modchambress;
  GtkWidget *modprixnuiteee;
  GtkWidget *modcombobox;
  GtkWidget *validerh;
  GtkWidget *alignment9;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label51;

  modifierheb = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifierheb), _("Modifier"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (modifierheb), fixed9);

  modetoiless = gtk_label_new (_("Nombre d'\303\251toiles :"));
  gtk_widget_show (modetoiless);
  gtk_fixed_put (GTK_FIXED (fixed9), modetoiless, 32, 160);
  gtk_widget_set_size_request (modetoiless, 136, 24);

  modpensionn = gtk_label_new (_("Type pension :"));
  gtk_widget_show (modpensionn);
  gtk_fixed_put (GTK_FIXED (fixed9), modpensionn, 32, 336);
  gtk_widget_set_size_request (modpensionn, 112, 24);

  modnomm = gtk_label_new (_("Nom d'hotel :"));
  gtk_widget_show (modnomm);
  gtk_fixed_put (GTK_FIXED (fixed9), modnomm, 24, 288);
  gtk_widget_set_size_request (modnomm, 120, 16);

  modidd = gtk_label_new (_("ID :"));
  gtk_widget_show (modidd);
  gtk_fixed_put (GTK_FIXED (fixed9), modidd, 32, 80);
  gtk_widget_set_size_request (modidd, 49, 17);

  modid = gtk_entry_new ();
  gtk_widget_show (modid);
  gtk_fixed_put (GTK_FIXED (fixed9), modid, 96, 72);
  gtk_widget_set_size_request (modid, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (modid), 8226);

  modprix = gtk_entry_new ();
  gtk_widget_show (modprix);
  gtk_fixed_put (GTK_FIXED (fixed9), modprix, 168, 200);
  gtk_widget_set_size_request (modprix, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (modprix), 8226);

  modspinbutton_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  modspinbutton = gtk_spin_button_new (GTK_ADJUSTMENT (modspinbutton_adj), 1, 0);
  gtk_widget_show (modspinbutton);
  gtk_fixed_put (GTK_FIXED (fixed9), modspinbutton, 192, 160);
  gtk_widget_set_size_request (modspinbutton, 60, 27);

  modpension = gtk_entry_new ();
  gtk_widget_show (modpension);
  gtk_fixed_put (GTK_FIXED (fixed9), modpension, 168, 328);
  gtk_widget_set_size_request (modpension, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (modpension), 8226);

  modvillee = gtk_label_new (_("Ville :"));
  gtk_widget_show (modvillee);
  gtk_fixed_put (GTK_FIXED (fixed9), modvillee, 16, 120);
  gtk_widget_set_size_request (modvillee, 104, 24);

  modcomboboxh = gtk_combo_box_new_text ();
  gtk_widget_show (modcomboboxh);
  gtk_fixed_put (GTK_FIXED (fixed9), modcomboboxh, 168, 280);
  gtk_widget_set_size_request (modcomboboxh, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (modcomboboxh), _("Mouradi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modcomboboxh), _("Houria"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modcomboboxh), _("Pacha"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modcomboboxh), _("Sunclub"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modcomboboxh), _("Byzance"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modcomboboxh), _("Toumana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modcomboboxh), _("Zenith"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modcomboboxh), _("Lacigale"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modcomboboxh), _("Darismail"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modcomboboxh), _("Itropika"));

  idd = gtk_entry_new ();
  gtk_widget_show (idd);
  gtk_fixed_put (GTK_FIXED (fixed9), idd, 192, 32);
  gtk_widget_set_size_request (idd, 168, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (idd), 8226);

  modcomboboxa = gtk_combo_box_new_text ();
  gtk_widget_show (modcomboboxa);
  gtk_fixed_put (GTK_FIXED (fixed9), modcomboboxa, 160, 112);
  gtk_widget_set_size_request (modcomboboxa, 136, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (modcomboboxa), _("soussa"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modcomboboxa), _("Mahdia"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modcomboboxa), _("Tabarka"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modcomboboxa), _("Gammarth"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modcomboboxa), _("Hammamet"));

  label48 = gtk_label_new ("");
  gtk_widget_show (label48);
  gtk_fixed_put (GTK_FIXED (fixed9), label48, 320, 368);
  gtk_widget_set_size_request (label48, 344, 112);

  modifierf = gtk_button_new ();
  gtk_widget_show (modifierf);
  gtk_fixed_put (GTK_FIXED (fixed9), modifierf, 168, 384);
  gtk_widget_set_size_request (modifierf, 136, 56);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (modifierf), alignment8);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label50 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox7), label50, FALSE, FALSE, 0);

  modchambress = gtk_label_new (_("Chambre :"));
  gtk_widget_show (modchambress);
  gtk_fixed_put (GTK_FIXED (fixed9), modchambress, 24, 248);
  gtk_widget_set_size_request (modchambress, 120, 16);

  modprixnuiteee = gtk_label_new (_("Prix du nuite :"));
  gtk_widget_show (modprixnuiteee);
  gtk_fixed_put (GTK_FIXED (fixed9), modprixnuiteee, 16, 208);
  gtk_widget_set_size_request (modprixnuiteee, 136, 16);

  modcombobox = gtk_combo_box_new_text ();
  gtk_widget_show (modcombobox);
  gtk_fixed_put (GTK_FIXED (fixed9), modcombobox, 168, 240);
  gtk_widget_set_size_request (modcombobox, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (modcombobox), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modcombobox), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modcombobox), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modcombobox), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modcombobox), _("5"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modcombobox), _("6"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modcombobox), _("7"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modcombobox), _("8"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modcombobox), _("9"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modcombobox), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modcombobox), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modcombobox), _("12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modcombobox), _("13"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modcombobox), _("14"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modcombobox), _("15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modcombobox), _("16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modcombobox), _("17"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modcombobox), _("18"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modcombobox), _("19"));

  validerh = gtk_button_new ();
  gtk_widget_show (validerh);
  gtk_fixed_put (GTK_FIXED (fixed9), validerh, 368, 32);
  gtk_widget_set_size_request (validerh, 96, 29);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (validerh), alignment9);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label51 = gtk_label_new_with_mnemonic (_("valider"));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox8), label51, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) modifierf, "clicked",
                    G_CALLBACK (on_modifierf_clicked),
                    NULL);
  g_signal_connect ((gpointer) validerh, "clicked",
                    G_CALLBACK (on_validerh_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifierheb, modifierheb, "modifierheb");
  GLADE_HOOKUP_OBJECT (modifierheb, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (modifierheb, modetoiless, "modetoiless");
  GLADE_HOOKUP_OBJECT (modifierheb, modpensionn, "modpensionn");
  GLADE_HOOKUP_OBJECT (modifierheb, modnomm, "modnomm");
  GLADE_HOOKUP_OBJECT (modifierheb, modidd, "modidd");
  GLADE_HOOKUP_OBJECT (modifierheb, modid, "modid");
  GLADE_HOOKUP_OBJECT (modifierheb, modprix, "modprix");
  GLADE_HOOKUP_OBJECT (modifierheb, modspinbutton, "modspinbutton");
  GLADE_HOOKUP_OBJECT (modifierheb, modpension, "modpension");
  GLADE_HOOKUP_OBJECT (modifierheb, modvillee, "modvillee");
  GLADE_HOOKUP_OBJECT (modifierheb, modcomboboxh, "modcomboboxh");
  GLADE_HOOKUP_OBJECT (modifierheb, idd, "idd");
  GLADE_HOOKUP_OBJECT (modifierheb, modcomboboxa, "modcomboboxa");
  GLADE_HOOKUP_OBJECT (modifierheb, label48, "label48");
  GLADE_HOOKUP_OBJECT (modifierheb, modifierf, "modifierf");
  GLADE_HOOKUP_OBJECT (modifierheb, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (modifierheb, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (modifierheb, image7, "image7");
  GLADE_HOOKUP_OBJECT (modifierheb, label50, "label50");
  GLADE_HOOKUP_OBJECT (modifierheb, modchambress, "modchambress");
  GLADE_HOOKUP_OBJECT (modifierheb, modprixnuiteee, "modprixnuiteee");
  GLADE_HOOKUP_OBJECT (modifierheb, modcombobox, "modcombobox");
  GLADE_HOOKUP_OBJECT (modifierheb, validerh, "validerh");
  GLADE_HOOKUP_OBJECT (modifierheb, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (modifierheb, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (modifierheb, image8, "image8");
  GLADE_HOOKUP_OBJECT (modifierheb, label51, "label51");

  return modifierheb;
}

GtkWidget*
create_felicitations (void)
{
  GtkWidget *felicitations;
  GtkWidget *fixed10;
  GtkWidget *label43;

  felicitations = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (felicitations), _("Congratulation"));

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (felicitations), fixed10);

  label43 = gtk_label_new (_("Votre hebergement a ete ajouter avec succes."));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed10), label43, 16, 96);
  gtk_widget_set_size_request (label43, 320, 32);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (felicitations, felicitations, "felicitations");
  GLADE_HOOKUP_OBJECT (felicitations, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (felicitations, label43, "label43");

  return felicitations;
}

GtkWidget*
create_modifiers (void)
{
  GtkWidget *modifiers;
  GtkWidget *fixed11;
  GtkWidget *label44;

  modifiers = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifiers), _("Congratulation"));

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (modifiers), fixed11);

  label44 = gtk_label_new (_("Votre hebergement a ete modifier avec succes."));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed11), label44, 40, 120);
  gtk_widget_set_size_request (label44, 328, 33);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifiers, modifiers, "modifiers");
  GLADE_HOOKUP_OBJECT (modifiers, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (modifiers, label44, "label44");

  return modifiers;
}

GtkWidget*
create_supprimer1 (void)
{
  GtkWidget *supprimer1;
  GtkWidget *fixed12;
  GtkWidget *label45;

  supprimer1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (supprimer1), _("Congratulation"));

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (supprimer1), fixed12);

  label45 = gtk_label_new (_("Votre hebergement a ete supprimer avec succes."));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed12), label45, 16, 104);
  gtk_widget_set_size_request (label45, 344, 25);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprimer1, supprimer1, "supprimer1");
  GLADE_HOOKUP_OBJECT (supprimer1, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (supprimer1, label45, "label45");

  return supprimer1;
}



























































void
on_ajouterh_clicked               (GtkWidget       *objet,
                                   gpointer   user_data)
{
heberg h;
GtkWidget *spinbutton1;
GtkWidget *etoiles;
GtkWidget *input1,*combobox3,*input3,*combobox2,*combobox1,*input6;
GtkWidget *espace;
GtkWidget *input0;

GtkWidget *output,*output2,*output3,*output10;
char empty[]="\0";
GtkWidget *felicitations;
output=lookup_widget(objet,"erreur");
output2=lookup_widget(objet,"erreur2");
output3=lookup_widget(objet,"erreur3");
output10=lookup_widget(objet,"label46");


espace=lookup_widget(objet,"espace");
input1=lookup_widget(objet,"id");
combobox3=lookup_widget(objet,"combobox3");
input0=lookup_widget(objet,"spinbutton1");
h.etoiles=gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON (spinbutton1));
input3=lookup_widget(objet,"prixnuitee");
combobox2=lookup_widget(objet,"combobox2");
combobox1=lookup_widget(objet,"combobox1");
input6=lookup_widget(objet,"type_pension");

strcpy(h.id,gtk_entry_get_text(GTK_ENTRY(input1)));
strcpy(h.ville,gtk_combo_box_get_active_text(GTK_COMBO_BOX(combobox3)));
h.etoiles=gtk_spin_button_get_value_as_int(GTK_ENTRY(input0));
strcpy(h.prixnuitee,gtk_entry_get_text(GTK_ENTRY(input3)));
strcpy(h.chambres,gtk_combo_box_get_active_text(GTK_COMBO_BOX(combobox2)));
strcpy(h.nom_hotel,gtk_combo_box_get_active_text(GTK_COMBO_BOX(combobox1)));
strcpy(h.type_pension,gtk_entry_get_text(GTK_ENTRY(input6)));
if(strcmp(h.id,empty)==0)
{
gtk_label_set_text(GTK_LABEL(output),"Ce champ est obligatoire");

}

else if(strcmp(h.prixnuitee,empty)==0)
{
gtk_label_set_text(GTK_LABEL(output2),"Ce champ est obligatoire");

}
else if(strcmp(h.type_pension,empty)==0)
{
gtk_label_set_text(GTK_LABEL(output3),"Ce champ est obligatoire");

}

else
{
ajouter_heberg(h);
/*felicitations=lookup_widget(objet,"felicitations");
felicitations=create_felicitations();
gtk_widget_show(felicitations);*/
gtk_label_set_text(GTK_LABEL(output10),"Ajout effectué avec succés..");
}

}







void
on_afficherh_clicked                    (GtkWidget       *objet,
                                        gpointer         user_data)
{

GtkWidget *espace;
GtkWidget *treeview1h;


espace=lookup_widget(objet,"espace");


treeview1h=lookup_widget(espace,"treeview1h");

afficher_heberg(treeview1h);
}






void
on_retourh_clicked                      (GtkWidget       *objet,
                                        gpointer         user_data)
{
GtkWidget *espace;

espace=lookup_widget(objet,"espace");

gtk_widget_destroy(espace);
espace=create_espace();
gtk_widget_show(espace);


}






void
on_supprimerh_clicked                   (GtkWidget       *objet,
                                        gpointer         user_data)
{
GtkWidget *espace;
GtkWidget *supprimer1;
GtkWidget *output3;
char id1[2000];
GtkWidget *input7;
input7=lookup_widget(objet,"id1");
output3=lookup_widget(objet,"label47");
strcpy(id1,gtk_entry_get_text(GTK_ENTRY(input7)));
supprimer_heberg(id1);
gtk_label_set_text(GTK_LABEL(output3),"La supression s'est effectuée avec succes.");
}


void
on_modifierh_clicked                    (GtkWidget       *objet,
                                        gpointer         user_data)
{
char id1[3000];
GtkWidget *modifierheb;
modifierheb= create_modifierheb();
gtk_widget_show(modifierheb);

}


void
on_modifierf_clicked                   (GtkWidget       *objet,
                                        gpointer         user_data)
{
char id1[3000];
heberg h1;
GtkWidget *modspinbutton;
GtkWidget *etoiles;
GtkWidget *input1,*combobox3,*input3,*combobox2,*combobox1,*input6;
//GtkWidget *modifier;
GtkWidget *input0;
GtkWidget *modcombobox;
GtkWidget *modcomboboxh;
GtkWidget *modcomboboxa;
GtkWidget *modifiers;
GtkWidget *output70;


//modifier=lookup_widget(objet,"modifier");
input1=lookup_widget(objet,"modid");
combobox3=lookup_widget(objet,"modcomboboxa");
input0=lookup_widget(objet,"modspinbutton");
h1.etoiles=gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON (modspinbutton));
input3=lookup_widget(objet,"modprix");
combobox2=lookup_widget(objet,"modcombobox");
combobox1=lookup_widget(objet,"modcomboboxh");
input6=lookup_widget(objet,"modpension");
output70=lookup_widget(objet,"label48");

strcpy(h1.id,gtk_entry_get_text(GTK_ENTRY(input1)));
strcpy(h1.ville,gtk_combo_box_get_active_text(GTK_COMBO_BOX(combobox3)));
h1.etoiles=gtk_spin_button_get_value_as_int(GTK_ENTRY(input0));
strcpy(h1.prixnuitee,gtk_entry_get_text(GTK_ENTRY(input3)));
strcpy(h1.chambres,gtk_combo_box_get_active_text(GTK_COMBO_BOX(combobox2)));
strcpy(h1.nom_hotel,gtk_combo_box_get_active_text(GTK_COMBO_BOX(combobox1)));
strcpy(h1.type_pension,gtk_entry_get_text(GTK_ENTRY(input6)));
modifier_heberg(h1);
gtk_label_set_text(GTK_LABEL(output70),"Votre hotel est mis à jour.");
/*modifiers=lookup_widget(objet,"modifiers");
modifiers=create_modifiers();
gtk_widget_show(modifiers);*/


}


void
on_validerh_clicked                     (GtkWidget       *objet,
                                        gpointer         user_data)
{

heberg h;
GtkWidget *input1,*output1,*output4,*output6;
GtkWidget *modifier;
char idd[33];
char modprix[300];
char modpension[300];


output1=lookup_widget(objet,"modid");
output4=lookup_widget(objet,"modprix");
output6=lookup_widget(objet,"modpension");
input1=lookup_widget(objet,"idd");
strcpy(idd,gtk_entry_get_text(GTK_ENTRY(input1)));
FILE *f;
	f=fopen("utilisateur.txt","r");
	if(f!=NULL)
{
while(fscanf(f,"%s %s  %d %s %s %s %s \n",h.id,h.ville,&h.etoiles,h.prixnuitee,h.chambres,h.nom_hotel,h.type_pension)!=EOF)
{
	if (strcmp(h.id,idd)==0)
{
gtk_entry_set_text (GTK_ENTRY (output1),h.id);
gtk_entry_set_text (GTK_ENTRY (output4),h.prixnuitee);
gtk_entry_set_text (GTK_ENTRY (output6),h.type_pension);

}
}
}





}


void
on_refresh1_clicked                    (GtkWidget       *objet,
                                        gpointer         user_data)
{
GtkWidget *espace;
GtkWidget *treeview1h;

espace=lookup_widget(objet,"espace");

gtk_widget_destroy(espace);
espace=create_espace();
gtk_widget_show(espace);

treeview1h=lookup_widget(espace,"treeview1h");

afficher_heberg(treeview1h);
}


void
on_deconnexiontaha_clicked             (GtkWidget       *objet,
                                        gpointer         user_data)
{
GtkWidget *espace;
GtkWidget *windowacceuil;
espace=lookup_widget(objet,"espace");

gtk_widget_destroy(espace);
windowacceuil=create_windowacceuil();
gtk_widget_show(windowacceuil);
}





void
on_reclamationtaha_clicked             (GtkWidget      *objet,
                                        gpointer         user_data)
{
GtkWidget *principal1;
principal1=create_principal1();
gtk_widget_show(principal1);
}

