/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gestionvol (void);
GtkWidget* create_ajoutervol (void);
GtkWidget* create_modifvol (void);









void
on_button1n_clicked                    (GtkWidget       *objet_graphique,
                                        gpointer         user_data);

void
on_button2n_clicked                    (GtkWidget       *objet_graphique,
                                        gpointer         user_data);

void
on_button3n_clicked                    (GtkWidget       *objet_graphique,
                                        gpointer         user_data);

void
on_button4_clicked                     (GtkWidget       *objet_graphique,
                                        gpointer         user_data);

void
on_treeview1_row_activated             (GtkWidget     *objet_graphique,
                                        GtkTreePath     *path,
                                        GtkTreeViewColumn *column,
                                        gpointer         user_data);

void
on_button5i_clicked                     (GtkWidget       *objet_graphique,
                                        gpointer         user_data);

void
on_button6i_clicked                     (GtkWidget       *objet_graphique,
                                        gpointer         user_data);

void
on_button7_clicked                     (GtkWidget       *objet_graphique,
                                        gpointer         user_data);
