/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_windowinscription (void)
{
  GtkWidget *windowinscription;
  GtkWidget *fixed1;
  GtkWidget *entrynom;
  GtkWidget *entryprenom;
  GtkObject *jour_adj;
  GtkWidget *jour;
  GtkObject *mois_adj;
  GtkWidget *mois;
  GtkObject *annee_adj;
  GtkWidget *annee;
  GtkWidget *entryadresse;
  GtkWidget *entryemail;
  GtkWidget *entrymotdepasse;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *label7;
  GtkWidget *label6;
  GtkWidget *label4;
  GtkWidget *entrymotdepasse1;
  GtkWidget *label5;
  GtkWidget *label12;
  GtkWidget *label11;
  GtkWidget *label10;
  GtkWidget *label9;
  GtkWidget *label8;
  GtkWidget *buttoninscription;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label13;
  GtkWidget *buttonretour;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label14;
  GtkWidget *erreur;
  GtkWidget *erreur1;
  GtkWidget *erreur2;
  GtkWidget *erreur4;
  GtkWidget *erreur5;
  GtkWidget *erreur3;
  GtkWidget *combobox1;
  GtkWidget *combobox2;

  windowinscription = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowinscription, 500, 500);
  gtk_window_set_title (GTK_WINDOW (windowinscription), _("Inscription"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (windowinscription), fixed1);

  entrynom = gtk_entry_new ();
  gtk_widget_show (entrynom);
  gtk_fixed_put (GTK_FIXED (fixed1), entrynom, 208, 96);
  gtk_widget_set_size_request (entrynom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynom), 8226);

  entryprenom = gtk_entry_new ();
  gtk_widget_show (entryprenom);
  gtk_fixed_put (GTK_FIXED (fixed1), entryprenom, 208, 144);
  gtk_widget_set_size_request (entryprenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprenom), 8226);

  jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jour = gtk_spin_button_new (GTK_ADJUSTMENT (jour_adj), 1, 0);
  gtk_widget_show (jour);
  gtk_fixed_put (GTK_FIXED (fixed1), jour, 288, 256);
  gtk_widget_set_size_request (jour, 60, 27);

  mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  mois = gtk_spin_button_new (GTK_ADJUSTMENT (mois_adj), 1, 0);
  gtk_widget_show (mois);
  gtk_fixed_put (GTK_FIXED (fixed1), mois, 416, 256);
  gtk_widget_set_size_request (mois, 60, 27);

  annee_adj = gtk_adjustment_new (1, 1920, 2001, 1, 10, 10);
  annee = gtk_spin_button_new (GTK_ADJUSTMENT (annee_adj), 1, 0);
  gtk_widget_show (annee);
  gtk_fixed_put (GTK_FIXED (fixed1), annee, 552, 256);
  gtk_widget_set_size_request (annee, 60, 27);

  entryadresse = gtk_entry_new ();
  gtk_widget_show (entryadresse);
  gtk_fixed_put (GTK_FIXED (fixed1), entryadresse, 216, 376);
  gtk_widget_set_size_request (entryadresse, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryadresse), 8226);

  entryemail = gtk_entry_new ();
  gtk_widget_show (entryemail);
  gtk_fixed_put (GTK_FIXED (fixed1), entryemail, 216, 424);
  gtk_widget_set_size_request (entryemail, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryemail), 8226);

  entrymotdepasse = gtk_entry_new ();
  gtk_widget_show (entrymotdepasse);
  gtk_fixed_put (GTK_FIXED (fixed1), entrymotdepasse, 216, 472);
  gtk_widget_set_size_request (entrymotdepasse, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (entrymotdepasse), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymotdepasse), 8226);

  label1 = gtk_label_new (_("Nom"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 24, 96);
  gtk_widget_set_size_request (label1, 97, 25);

  label2 = gtk_label_new (_("Prenom"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 32, 144);
  gtk_widget_set_size_request (label2, 105, 33);

  label3 = gtk_label_new (_("Pays"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 24, 184);
  gtk_widget_set_size_request (label3, 113, 33);

  label7 = gtk_label_new (_("annee"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed1), label7, 488, 264);
  gtk_widget_set_size_request (label7, 56, 16);

  label6 = gtk_label_new (_("mois"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed1), label6, 360, 264);
  gtk_widget_set_size_request (label6, 41, 17);

  label4 = gtk_label_new (_("Date de naissance"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 24, 248);
  gtk_widget_set_size_request (label4, 137, 41);

  entrymotdepasse1 = gtk_entry_new ();
  gtk_widget_show (entrymotdepasse1);
  gtk_fixed_put (GTK_FIXED (fixed1), entrymotdepasse1, 216, 520);
  gtk_widget_set_size_request (entrymotdepasse1, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (entrymotdepasse1), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymotdepasse1), 8226);

  label5 = gtk_label_new (_("jour"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed1), label5, 240, 264);
  gtk_widget_set_size_request (label5, 41, 17);

  label12 = gtk_label_new (_("Veuillez confirmer\n votre mot de passe"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed1), label12, 8, 504);
  gtk_widget_set_size_request (label12, 184, 56);

  label11 = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed1), label11, 40, 456);
  gtk_widget_set_size_request (label11, 136, 57);

  label10 = gtk_label_new (_("E-mail"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed1), label10, 32, 416);
  gtk_widget_set_size_request (label10, 137, 49);

  label9 = gtk_label_new (_("Adresse:"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed1), label9, 48, 376);
  gtk_widget_set_size_request (label9, 113, 33);

  label8 = gtk_label_new (_("Sexe"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed1), label8, 48, 312);
  gtk_widget_set_size_request (label8, 121, 41);

  buttoninscription = gtk_button_new ();
  gtk_widget_show (buttoninscription);
  gtk_fixed_put (GTK_FIXED (fixed1), buttoninscription, 824, 600);
  gtk_widget_set_size_request (buttoninscription, 146, 64);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttoninscription), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("M'inscrire"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox1), label13, FALSE, FALSE, 0);

  buttonretour = gtk_button_new ();
  gtk_widget_show (buttonretour);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonretour, 56, 600);
  gtk_widget_set_size_request (buttonretour, 120, 64);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttonretour), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox2), label14, FALSE, FALSE, 0);

  erreur = gtk_label_new ("");
  gtk_widget_show (erreur);
  gtk_fixed_put (GTK_FIXED (fixed1), erreur, 416, 520);
  gtk_widget_set_size_request (erreur, 392, 48);

  erreur1 = gtk_label_new ("");
  gtk_widget_show (erreur1);
  gtk_fixed_put (GTK_FIXED (fixed1), erreur1, 392, 88);
  gtk_widget_set_size_request (erreur1, 352, 40);

  erreur2 = gtk_label_new ("");
  gtk_widget_show (erreur2);
  gtk_fixed_put (GTK_FIXED (fixed1), erreur2, 376, 144);
  gtk_widget_set_size_request (erreur2, 224, 32);

  erreur4 = gtk_label_new ("");
  gtk_widget_show (erreur4);
  gtk_fixed_put (GTK_FIXED (fixed1), erreur4, 392, 424);
  gtk_widget_set_size_request (erreur4, 392, 32);

  erreur5 = gtk_label_new ("");
  gtk_widget_show (erreur5);
  gtk_fixed_put (GTK_FIXED (fixed1), erreur5, 416, 464);
  gtk_widget_set_size_request (erreur5, 360, 40);

  erreur3 = gtk_label_new ("");
  gtk_widget_show (erreur3);
  gtk_fixed_put (GTK_FIXED (fixed1), erreur3, 392, 376);
  gtk_widget_set_size_request (erreur3, 360, 32);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed1), combobox1, 208, 192);
  gtk_widget_set_size_request (combobox1, 161, 32);
  gtk_container_set_border_width (GTK_CONTAINER (combobox1), 1);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Afrique du Sud"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Alg\303\251rie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Angola"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("B\303\251nin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Botswana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Burkina"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Burundi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Cameroun"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Cap-Vert"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("R\303\251publique centrafricaine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Comores"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Congo"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("R\303\251publique d\303\251mocratique du Congo"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("C\303\264te d'Ivoire"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Djibouti"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("\303\211gypte"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("\303\211rythr\303\251e"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("\303\211thiopie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Gabon"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Gambie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Ghana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Guin\303\251e"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Guin\303\251e-Bissau"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Guin\303\251e \303\251quatoriale"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Kenya"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Lesotho"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Lib\303\251ria"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Libye"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Madagascar"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Malawi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Mali"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Maroc"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Maurice"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Mauritanie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Mozambique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Namibie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Niger"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Nigeria"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Ouganda"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Rwanda"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Sao Tom\303\251-et-Principe"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("S\303\251n\303\251gal"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Seychelles"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Sierra Leone"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Somalie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Soudan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Sud-Soudan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Swaziland"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Tanzanie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Tchad"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Togo"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Tunisie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Zambie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Zimbabwe"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Antigua-et-Barbuda"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Argentine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Bahamas"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Barbade"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Belize"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Bolivie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Br\303\251sil"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Canada"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Chili"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Colombie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Costa Rica"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Cuba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("R\303\251publique dominicaine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Dominique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("\303\211quateur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("\303\211tats-Unis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Grenade"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Guatemala"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Guyana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Ha\303\257ti"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Honduras"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Jama\303\257que"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Mexique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Nicaragua"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Panama"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Paraguay"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("P\303\251rou"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Porto Rico"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Saint-Christophe-et-Ni\303\251v\303\250s"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Sainte-Lucie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Saint-Vincent-et-les Grenadines"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Salvador"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Suriname"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Trinit\303\251-et-Tobago"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Uruguay"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Venezuela"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Afghanistan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Arabie saoudite"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Bahre\303\257n"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Bangladesh"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Bhoutan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Birmanie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Brunei"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Cambodge"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Chine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Cor\303\251e du Nord"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Cor\303\251e du Sud"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("\303\211mirats arabes unis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Inde"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Indon\303\251sie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Irak"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Iran"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Isra\303\253l"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Japon"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Jordanie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Kazakhstan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Kirghizistan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Kowe\303\257t"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Laos"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Liban"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Malaisie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Maldives"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Mongolie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("N\303\251pal"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Oman"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Ouzb\303\251kistan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Palestine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Pakistan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Philippines"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Qatar"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Singapour"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Sri Lanka"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Syrie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Tadjikistan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Ta\303\257wan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Tha\303\257lande"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Timor oriental"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Turkm\303\251nistan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Turquie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Vi\303\252t Nam"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Y\303\251men"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Allemagne"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Albanie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Andorre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Arm\303\251nie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Autriche"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Azerba\303\257djan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Belgique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Bi\303\251lorussie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Bosnie-Herz\303\251govine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Bulgarie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Chypre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Croatie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Danemark"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Espagne"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Estonie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Finlande"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("France"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("G\303\251orgie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Gr\303\250ce"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Hongrie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Irlande"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Islande"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Italie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Lettonie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Liechtenstein"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Lituanie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Luxembourg"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("R\303\251publique de Mac\303\251doine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Malte"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Moldavie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Monaco"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Mont\303\251n\303\251gro"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Norv\303\250ge"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Pays-Bas"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Pologne"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Portugal"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("R\303\251publique tch\303\250que"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Roumanie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Royaume-Uni"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Russie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Saint-Marin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Serbie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Slovaquie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Slov\303\251nie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Su\303\250de"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Suisse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Ukraine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Vatican"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Australie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Fidji"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Kiribati"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Marshall"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Micron\303\251sie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Nauru"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Nouvelle-Z\303\251lande"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Palaos"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Papouasie-Nouvelle-Guin\303\251e"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Salomon"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Samoa"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Tonga"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Tuvalu"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Vanuatu"));

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_fixed_put (GTK_FIXED (fixed1), combobox2, 216, 320);
  gtk_widget_set_size_request (combobox2, 97, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Male"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Femelle"));

  g_signal_connect ((gpointer) buttoninscription, "clicked",
                    G_CALLBACK (on_buttoninscription_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonretour, "clicked",
                    G_CALLBACK (on_buttonretour_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowinscription, windowinscription, "windowinscription");
  GLADE_HOOKUP_OBJECT (windowinscription, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (windowinscription, entrynom, "entrynom");
  GLADE_HOOKUP_OBJECT (windowinscription, entryprenom, "entryprenom");
  GLADE_HOOKUP_OBJECT (windowinscription, jour, "jour");
  GLADE_HOOKUP_OBJECT (windowinscription, mois, "mois");
  GLADE_HOOKUP_OBJECT (windowinscription, annee, "annee");
  GLADE_HOOKUP_OBJECT (windowinscription, entryadresse, "entryadresse");
  GLADE_HOOKUP_OBJECT (windowinscription, entryemail, "entryemail");
  GLADE_HOOKUP_OBJECT (windowinscription, entrymotdepasse, "entrymotdepasse");
  GLADE_HOOKUP_OBJECT (windowinscription, label1, "label1");
  GLADE_HOOKUP_OBJECT (windowinscription, label2, "label2");
  GLADE_HOOKUP_OBJECT (windowinscription, label3, "label3");
  GLADE_HOOKUP_OBJECT (windowinscription, label7, "label7");
  GLADE_HOOKUP_OBJECT (windowinscription, label6, "label6");
  GLADE_HOOKUP_OBJECT (windowinscription, label4, "label4");
  GLADE_HOOKUP_OBJECT (windowinscription, entrymotdepasse1, "entrymotdepasse1");
  GLADE_HOOKUP_OBJECT (windowinscription, label5, "label5");
  GLADE_HOOKUP_OBJECT (windowinscription, label12, "label12");
  GLADE_HOOKUP_OBJECT (windowinscription, label11, "label11");
  GLADE_HOOKUP_OBJECT (windowinscription, label10, "label10");
  GLADE_HOOKUP_OBJECT (windowinscription, label9, "label9");
  GLADE_HOOKUP_OBJECT (windowinscription, label8, "label8");
  GLADE_HOOKUP_OBJECT (windowinscription, buttoninscription, "buttoninscription");
  GLADE_HOOKUP_OBJECT (windowinscription, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (windowinscription, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (windowinscription, image1, "image1");
  GLADE_HOOKUP_OBJECT (windowinscription, label13, "label13");
  GLADE_HOOKUP_OBJECT (windowinscription, buttonretour, "buttonretour");
  GLADE_HOOKUP_OBJECT (windowinscription, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (windowinscription, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (windowinscription, image2, "image2");
  GLADE_HOOKUP_OBJECT (windowinscription, label14, "label14");
  GLADE_HOOKUP_OBJECT (windowinscription, erreur, "erreur");
  GLADE_HOOKUP_OBJECT (windowinscription, erreur1, "erreur1");
  GLADE_HOOKUP_OBJECT (windowinscription, erreur2, "erreur2");
  GLADE_HOOKUP_OBJECT (windowinscription, erreur4, "erreur4");
  GLADE_HOOKUP_OBJECT (windowinscription, erreur5, "erreur5");
  GLADE_HOOKUP_OBJECT (windowinscription, erreur3, "erreur3");
  GLADE_HOOKUP_OBJECT (windowinscription, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (windowinscription, combobox2, "combobox2");

  return windowinscription;
}

GtkWidget*
create_windowacceuil (void)
{
  GtkWidget *windowacceuil;
  GtkWidget *fixed2;
  GtkWidget *button3;
  GtkWidget *buttoninscription1;
  GtkWidget *button1;

  windowacceuil = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowacceuil, 500, 250);
  gtk_window_set_title (GTK_WINDOW (windowacceuil), _("Acceuil"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (windowacceuil), fixed2);

  button3 = gtk_button_new_with_mnemonic (_("Catalogue"));
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed2), button3, 184, 192);
  gtk_widget_set_size_request (button3, 112, 56);

  buttoninscription1 = gtk_button_new_with_mnemonic (_("Inscription"));
  gtk_widget_show (buttoninscription1);
  gtk_fixed_put (GTK_FIXED (fixed2), buttoninscription1, 184, 104);
  gtk_widget_set_size_request (buttoninscription1, 112, 56);

  button1 = gtk_button_new_with_mnemonic (_("Connexion"));
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed2), button1, 184, 24);
  gtk_widget_set_size_request (button1, 112, 56);

  g_signal_connect ((gpointer) buttoninscription1, "clicked",
                    G_CALLBACK (on_buttoninscription1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowacceuil, windowacceuil, "windowacceuil");
  GLADE_HOOKUP_OBJECT (windowacceuil, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (windowacceuil, button3, "button3");
  GLADE_HOOKUP_OBJECT (windowacceuil, buttoninscription1, "buttoninscription1");
  GLADE_HOOKUP_OBJECT (windowacceuil, button1, "button1");

  return windowacceuil;
}

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed3;
  GtkWidget *button5;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label16;
  GtkWidget *entrylogin;
  GtkWidget *entrypassword;
  GtkWidget *meconnecter;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label523;
  GtkWidget *label25;
  GtkWidget *label17;
  GtkWidget *label18;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("Se connecter"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (window1), fixed3);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed3), button5, 16, 192);
  gtk_widget_set_size_request (button5, 138, 61);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button5), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("Acceuil"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox3), label16, FALSE, FALSE, 0);

  entrylogin = gtk_entry_new ();
  gtk_widget_show (entrylogin);
  gtk_fixed_put (GTK_FIXED (fixed3), entrylogin, 152, 48);
  gtk_widget_set_size_request (entrylogin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrylogin), 8226);

  entrypassword = gtk_entry_new ();
  gtk_widget_show (entrypassword);
  gtk_fixed_put (GTK_FIXED (fixed3), entrypassword, 152, 96);
  gtk_widget_set_size_request (entrypassword, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (entrypassword), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrypassword), 8226);

  meconnecter = gtk_button_new ();
  gtk_widget_show (meconnecter);
  gtk_fixed_put (GTK_FIXED (fixed3), meconnecter, 200, 192);
  gtk_widget_set_size_request (meconnecter, 146, 64);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (meconnecter), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label523 = gtk_label_new_with_mnemonic (_("Me connecter"));
  gtk_widget_show (label523);
  gtk_box_pack_start (GTK_BOX (hbox8), label523, FALSE, FALSE, 0);

  label25 = gtk_label_new (_("<span foreground=\"red\"></span>"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed3), label25, 40, 128);
  gtk_widget_set_size_request (label25, 288, 64);
  gtk_label_set_use_markup (GTK_LABEL (label25), TRUE);

  label17 = gtk_label_new (_("<span foreground=\"green\"><b>E-mail</b></span>"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed3), label17, 48, 56);
  gtk_widget_set_size_request (label17, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label17), TRUE);

  label18 = gtk_label_new (_("<span foreground=\"green\"><b>Mot de passe</b></span>"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed3), label18, 8, 96);
  gtk_widget_set_size_request (label18, 120, 40);
  gtk_label_set_use_markup (GTK_LABEL (label18), TRUE);

  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);
  g_signal_connect ((gpointer) meconnecter, "clicked",
                    G_CALLBACK (on_meconnecter_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window1, button5, "button5");
  GLADE_HOOKUP_OBJECT (window1, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window1, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window1, image3, "image3");
  GLADE_HOOKUP_OBJECT (window1, label16, "label16");
  GLADE_HOOKUP_OBJECT (window1, entrylogin, "entrylogin");
  GLADE_HOOKUP_OBJECT (window1, entrypassword, "entrypassword");
  GLADE_HOOKUP_OBJECT (window1, meconnecter, "meconnecter");
  GLADE_HOOKUP_OBJECT (window1, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window1, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window1, image8, "image8");
  GLADE_HOOKUP_OBJECT (window1, label523, "label523");
  GLADE_HOOKUP_OBJECT (window1, label25, "label25");
  GLADE_HOOKUP_OBJECT (window1, label17, "label17");
  GLADE_HOOKUP_OBJECT (window1, label18, "label18");

  return window1;
}

GtkWidget*
create_windowfelecitations (void)
{
  GtkWidget *windowfelecitations;
  GtkWidget *fixed4;
  GtkWidget *button6;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label20;
  GtkWidget *label19;

  windowfelecitations = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowfelecitations), _("window2"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (windowfelecitations), fixed4);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed4), button6, 80, 168);
  gtk_widget_set_size_request (button6, 264, 88);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button6), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("Me connecter"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox4), label20, FALSE, FALSE, 0);

  label19 = gtk_label_new (_("<span color=\"green\">F\303\251l\303\251citations , votre compte a \303\251t\303\251 cr\303\251\303\251 avec\nsucc\303\251es , cliquez sur le bouton pour acceder\n                             \303\240 votre espace.</span>"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed4), label19, 40, 64);
  gtk_widget_set_size_request (label19, 328, 104);
  gtk_label_set_use_markup (GTK_LABEL (label19), TRUE);

  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_button6_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowfelecitations, windowfelecitations, "windowfelecitations");
  GLADE_HOOKUP_OBJECT (windowfelecitations, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (windowfelecitations, button6, "button6");
  GLADE_HOOKUP_OBJECT (windowfelecitations, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (windowfelecitations, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (windowfelecitations, image4, "image4");
  GLADE_HOOKUP_OBJECT (windowfelecitations, label20, "label20");
  GLADE_HOOKUP_OBJECT (windowfelecitations, label19, "label19");

  return windowfelecitations;
}

GtkWidget*
create_windowespaceclient (void)
{
  GtkWidget *windowespaceclient;
  GtkWidget *fixed5;
  GtkWidget *deconnexion;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label24;
  GtkWidget *label527;
  GtkWidget *nomsb;
  GtkObject *joursb_adj;
  GtkWidget *joursb;
  GtkObject *moissb_adj;
  GtkWidget *moissb;
  GtkObject *anneesb_adj;
  GtkWidget *anneesb;
  GtkWidget *prenomsb;
  GtkWidget *adressesb;
  GtkWidget *motdepassesb;
  GtkWidget *label542;
  GtkWidget *payssb;
  GtkWidget *sexesb;
  GtkWidget *updatesb;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label546;
  GtkWidget *button1000;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label540;
  GtkWidget *label529;
  GtkWidget *label530;
  GtkWidget *label528;
  GtkWidget *label544;
  GtkWidget *label543;
  GtkWidget *label532;
  GtkWidget *label545;
  GtkWidget *label549;
  GtkWidget *label531;
  GtkWidget *label550;
  GtkWidget *label548;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview1201;
  GtkWidget *sblabel;

  windowespaceclient = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowespaceclient), _("Sky Travel"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (windowespaceclient), fixed5);

  deconnexion = gtk_button_new ();
  gtk_widget_show (deconnexion);
  gtk_fixed_put (GTK_FIXED (fixed5), deconnexion, 976, 48);
  gtk_widget_set_size_request (deconnexion, 146, 56);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (deconnexion), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("Me deconnecter"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox5), label24, FALSE, FALSE, 0);

  label527 = gtk_label_new (_("<span  foreground=\"blue\"><b><u>Mes R\303\251clamations:</u></b></span>"));
  gtk_widget_show (label527);
  gtk_fixed_put (GTK_FIXED (fixed5), label527, 0, 0);
  gtk_widget_set_size_request (label527, 160, 48);
  gtk_label_set_use_markup (GTK_LABEL (label527), TRUE);

  nomsb = gtk_entry_new ();
  gtk_widget_show (nomsb);
  gtk_fixed_put (GTK_FIXED (fixed5), nomsb, 160, 192);
  gtk_widget_set_size_request (nomsb, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nomsb), 8226);

  joursb_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  joursb = gtk_spin_button_new (GTK_ADJUSTMENT (joursb_adj), 1, 0);
  gtk_widget_show (joursb);
  gtk_fixed_put (GTK_FIXED (fixed5), joursb, 232, 320);
  gtk_widget_set_size_request (joursb, 60, 27);

  moissb_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  moissb = gtk_spin_button_new (GTK_ADJUSTMENT (moissb_adj), 1, 0);
  gtk_widget_show (moissb);
  gtk_fixed_put (GTK_FIXED (fixed5), moissb, 336, 320);
  gtk_widget_set_size_request (moissb, 60, 27);

  anneesb_adj = gtk_adjustment_new (1, 0, 2001, 1, 10, 10);
  anneesb = gtk_spin_button_new (GTK_ADJUSTMENT (anneesb_adj), 1, 0);
  gtk_widget_show (anneesb);
  gtk_fixed_put (GTK_FIXED (fixed5), anneesb, 440, 320);
  gtk_widget_set_size_request (anneesb, 60, 27);

  prenomsb = gtk_entry_new ();
  gtk_widget_show (prenomsb);
  gtk_fixed_put (GTK_FIXED (fixed5), prenomsb, 160, 232);
  gtk_widget_set_size_request (prenomsb, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenomsb), 8226);

  adressesb = gtk_entry_new ();
  gtk_widget_show (adressesb);
  gtk_fixed_put (GTK_FIXED (fixed5), adressesb, 160, 448);
  gtk_widget_set_size_request (adressesb, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (adressesb), 8226);

  motdepassesb = gtk_entry_new ();
  gtk_widget_show (motdepassesb);
  gtk_fixed_put (GTK_FIXED (fixed5), motdepassesb, 160, 488);
  gtk_widget_set_size_request (motdepassesb, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (motdepassesb), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (motdepassesb), 8226);

  label542 = gtk_label_new ("");
  gtk_widget_show (label542);
  gtk_fixed_put (GTK_FIXED (fixed5), label542, 96, 264);
  gtk_widget_set_size_request (label542, 296, 48);

  payssb = gtk_entry_new ();
  gtk_widget_show (payssb);
  gtk_fixed_put (GTK_FIXED (fixed5), payssb, 160, 416);
  gtk_widget_set_size_request (payssb, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (payssb), 8226);

  sexesb = gtk_entry_new ();
  gtk_widget_show (sexesb);
  gtk_fixed_put (GTK_FIXED (fixed5), sexesb, 160, 376);
  gtk_widget_set_size_request (sexesb, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (sexesb), 8226);

  updatesb = gtk_button_new ();
  gtk_widget_show (updatesb);
  gtk_fixed_put (GTK_FIXED (fixed5), updatesb, 0, 536);
  gtk_widget_set_size_request (updatesb, 200, 72);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (updatesb), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label546 = gtk_label_new_with_mnemonic (_("Mettre \303\240 jour mon profil"));
  gtk_widget_show (label546);
  gtk_box_pack_start (GTK_BOX (hbox13), label546, FALSE, FALSE, 0);

  button1000 = gtk_button_new ();
  gtk_widget_show (button1000);
  gtk_fixed_put (GTK_FIXED (fixed5), button1000, 224, 536);
  gtk_widget_set_size_request (button1000, 202, 72);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button1000), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label540 = gtk_label_new_with_mnemonic (_("D\303\251sactiver mon compte"));
  gtk_widget_show (label540);
  gtk_box_pack_start (GTK_BOX (hbox11), label540, FALSE, FALSE, 0);

  label529 = gtk_label_new (_("<span foreground=\"green\"><b><u>Prenom:</u></b></span>"));
  gtk_widget_show (label529);
  gtk_fixed_put (GTK_FIXED (fixed5), label529, 0, 232);
  gtk_widget_set_size_request (label529, 64, 32);
  gtk_label_set_use_markup (GTK_LABEL (label529), TRUE);

  label530 = gtk_label_new (_("<span foreground=\"green\"><b><u>E-mail:</u></b></span>"));
  gtk_widget_show (label530);
  gtk_fixed_put (GTK_FIXED (fixed5), label530, 0, 280);
  gtk_widget_set_size_request (label530, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label530), TRUE);

  label528 = gtk_label_new (_("<span foreground=\"green\"><b><u>Nom:</u></b></span>"));
  gtk_widget_show (label528);
  gtk_fixed_put (GTK_FIXED (fixed5), label528, 0, 192);
  gtk_widget_set_size_request (label528, 40, 40);
  gtk_label_set_use_markup (GTK_LABEL (label528), TRUE);

  label544 = gtk_label_new (_("<span foreground=\"green\"><b><u>Pays:</u></b></span>"));
  gtk_widget_show (label544);
  gtk_fixed_put (GTK_FIXED (fixed5), label544, 0, 424);
  gtk_widget_set_size_request (label544, 48, 17);
  gtk_label_set_use_markup (GTK_LABEL (label544), TRUE);

  label543 = gtk_label_new (_("<span foreground=\"green\"><b><u>Mot de Passe:</u></b></span>"));
  gtk_widget_show (label543);
  gtk_fixed_put (GTK_FIXED (fixed5), label543, 0, 488);
  gtk_widget_set_size_request (label543, 105, 24);
  gtk_label_set_use_markup (GTK_LABEL (label543), TRUE);

  label532 = gtk_label_new (_("<span foreground=\"green\"><b><u>Adresse:</u></b></span>"));
  gtk_widget_show (label532);
  gtk_fixed_put (GTK_FIXED (fixed5), label532, 0, 448);
  gtk_widget_set_size_request (label532, 64, 32);
  gtk_label_set_use_markup (GTK_LABEL (label532), TRUE);

  label545 = gtk_label_new (_("<span foreground=\"green\"><b><u>Sexe:</u></b></span>"));
  gtk_widget_show (label545);
  gtk_fixed_put (GTK_FIXED (fixed5), label545, 0, 376);
  gtk_widget_set_size_request (label545, 48, 32);
  gtk_label_set_use_markup (GTK_LABEL (label545), TRUE);

  label549 = gtk_label_new (_("<u>mois</u>"));
  gtk_widget_show (label549);
  gtk_fixed_put (GTK_FIXED (fixed5), label549, 288, 328);
  gtk_widget_set_size_request (label549, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label549), TRUE);

  label531 = gtk_label_new (_("<span foreground=\"green\"><b><u>Date de naissance:</u></b></span>"));
  gtk_widget_show (label531);
  gtk_fixed_put (GTK_FIXED (fixed5), label531, 0, 312);
  gtk_widget_set_size_request (label531, 136, 40);
  gtk_label_set_use_markup (GTK_LABEL (label531), TRUE);

  label550 = gtk_label_new (_("<u>annee</u>"));
  gtk_widget_show (label550);
  gtk_fixed_put (GTK_FIXED (fixed5), label550, 392, 328);
  gtk_widget_set_size_request (label550, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label550), TRUE);

  label548 = gtk_label_new (_("<u>jour</u>"));
  gtk_widget_show (label548);
  gtk_fixed_put (GTK_FIXED (fixed5), label548, 184, 328);
  gtk_widget_set_size_request (label548, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label548), TRUE);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed5), scrolledwindow1, 152, 8);
  gtk_widget_set_size_request (scrolledwindow1, 624, 120);

  treeview1201 = gtk_tree_view_new ();
  gtk_widget_show (treeview1201);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview1201);

  sblabel = gtk_label_new ("");
  gtk_widget_show (sblabel);
  gtk_fixed_put (GTK_FIXED (fixed5), sblabel, 552, 536);
  gtk_widget_set_size_request (sblabel, 440, 49);

  g_signal_connect ((gpointer) deconnexion, "clicked",
                    G_CALLBACK (on_deconnexion_clicked),
                    NULL);
  g_signal_connect ((gpointer) updatesb, "clicked",
                    G_CALLBACK (on_updatesb_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1000, "clicked",
                    G_CALLBACK (on_buttonsupprimer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowespaceclient, windowespaceclient, "windowespaceclient");
  GLADE_HOOKUP_OBJECT (windowespaceclient, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (windowespaceclient, deconnexion, "deconnexion");
  GLADE_HOOKUP_OBJECT (windowespaceclient, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (windowespaceclient, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (windowespaceclient, image5, "image5");
  GLADE_HOOKUP_OBJECT (windowespaceclient, label24, "label24");
  GLADE_HOOKUP_OBJECT (windowespaceclient, label527, "label527");
  GLADE_HOOKUP_OBJECT (windowespaceclient, nomsb, "nomsb");
  GLADE_HOOKUP_OBJECT (windowespaceclient, joursb, "joursb");
  GLADE_HOOKUP_OBJECT (windowespaceclient, moissb, "moissb");
  GLADE_HOOKUP_OBJECT (windowespaceclient, anneesb, "anneesb");
  GLADE_HOOKUP_OBJECT (windowespaceclient, prenomsb, "prenomsb");
  GLADE_HOOKUP_OBJECT (windowespaceclient, adressesb, "adressesb");
  GLADE_HOOKUP_OBJECT (windowespaceclient, motdepassesb, "motdepassesb");
  GLADE_HOOKUP_OBJECT (windowespaceclient, label542, "label542");
  GLADE_HOOKUP_OBJECT (windowespaceclient, payssb, "payssb");
  GLADE_HOOKUP_OBJECT (windowespaceclient, sexesb, "sexesb");
  GLADE_HOOKUP_OBJECT (windowespaceclient, updatesb, "updatesb");
  GLADE_HOOKUP_OBJECT (windowespaceclient, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (windowespaceclient, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (windowespaceclient, image13, "image13");
  GLADE_HOOKUP_OBJECT (windowespaceclient, label546, "label546");
  GLADE_HOOKUP_OBJECT (windowespaceclient, button1000, "button1000");
  GLADE_HOOKUP_OBJECT (windowespaceclient, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (windowespaceclient, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (windowespaceclient, image11, "image11");
  GLADE_HOOKUP_OBJECT (windowespaceclient, label540, "label540");
  GLADE_HOOKUP_OBJECT (windowespaceclient, label529, "label529");
  GLADE_HOOKUP_OBJECT (windowespaceclient, label530, "label530");
  GLADE_HOOKUP_OBJECT (windowespaceclient, label528, "label528");
  GLADE_HOOKUP_OBJECT (windowespaceclient, label544, "label544");
  GLADE_HOOKUP_OBJECT (windowespaceclient, label543, "label543");
  GLADE_HOOKUP_OBJECT (windowespaceclient, label532, "label532");
  GLADE_HOOKUP_OBJECT (windowespaceclient, label545, "label545");
  GLADE_HOOKUP_OBJECT (windowespaceclient, label549, "label549");
  GLADE_HOOKUP_OBJECT (windowespaceclient, label531, "label531");
  GLADE_HOOKUP_OBJECT (windowespaceclient, label550, "label550");
  GLADE_HOOKUP_OBJECT (windowespaceclient, label548, "label548");
  GLADE_HOOKUP_OBJECT (windowespaceclient, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (windowespaceclient, treeview1201, "treeview1201");
  GLADE_HOOKUP_OBJECT (windowespaceclient, sblabel, "sblabel");

  return windowespaceclient;
}

GtkWidget*
create_windowdesactivercompte (void)
{
  GtkWidget *windowdesactivercompte;
  GtkWidget *fixed7;
  GtkWidget *entryemail1;
  GtkWidget *entrymotdepasse1;
  GtkWidget *buttondesactivercompte1;
  GtkWidget *button8;
  GtkWidget *label500;
  GtkWidget *label547;
  GtkWidget *label36;
  GtkWidget *label37;

  windowdesactivercompte = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowdesactivercompte), _("Desactiver mon compte"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (windowdesactivercompte), fixed7);

  entryemail1 = gtk_entry_new ();
  gtk_widget_show (entryemail1);
  gtk_fixed_put (GTK_FIXED (fixed7), entryemail1, 144, 88);
  gtk_widget_set_size_request (entryemail1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryemail1), 8226);

  entrymotdepasse1 = gtk_entry_new ();
  gtk_widget_show (entrymotdepasse1);
  gtk_fixed_put (GTK_FIXED (fixed7), entrymotdepasse1, 144, 144);
  gtk_widget_set_size_request (entrymotdepasse1, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (entrymotdepasse1), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymotdepasse1), 8226);

  buttondesactivercompte1 = gtk_button_new_with_mnemonic (_("Desactiver"));
  gtk_widget_show (buttondesactivercompte1);
  gtk_fixed_put (GTK_FIXED (fixed7), buttondesactivercompte1, 240, 256);
  gtk_widget_set_size_request (buttondesactivercompte1, 122, 56);

  button8 = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed7), button8, 16, 264);
  gtk_widget_set_size_request (button8, 130, 53);

  label500 = gtk_label_new ("");
  gtk_widget_show (label500);
  gtk_fixed_put (GTK_FIXED (fixed7), label500, 56, 192);
  gtk_widget_set_size_request (label500, 320, 48);

  label547 = gtk_label_new (_("<span color=\"red\">Vous etes sur le point de desactiver votre compte, si\n vous en etes sur entrez votre email et votre mot de\n passe pour continuer,si non vous pouvez rentrer dans \nvotre espace et nous envoyer une reclamation.</span>"));
  gtk_widget_show (label547);
  gtk_fixed_put (GTK_FIXED (fixed7), label547, 16, 8);
  gtk_widget_set_size_request (label547, 360, 72);
  gtk_label_set_use_markup (GTK_LABEL (label547), TRUE);

  label36 = gtk_label_new (_("<span color=\"green\"><b><u>E-mail:</u></b></span>"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed7), label36, 40, 88);
  gtk_widget_set_size_request (label36, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label36), TRUE);

  label37 = gtk_label_new (_("<span color=\"green\"><b><u>Mot de passe:</u></b></span>"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed7), label37, 16, 144);
  gtk_widget_set_size_request (label37, 96, 32);
  gtk_label_set_use_markup (GTK_LABEL (label37), TRUE);

  g_signal_connect ((gpointer) buttondesactivercompte1, "clicked",
                    G_CALLBACK (on_buttondesactivercompte1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_button8_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowdesactivercompte, windowdesactivercompte, "windowdesactivercompte");
  GLADE_HOOKUP_OBJECT (windowdesactivercompte, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (windowdesactivercompte, entryemail1, "entryemail1");
  GLADE_HOOKUP_OBJECT (windowdesactivercompte, entrymotdepasse1, "entrymotdepasse1");
  GLADE_HOOKUP_OBJECT (windowdesactivercompte, buttondesactivercompte1, "buttondesactivercompte1");
  GLADE_HOOKUP_OBJECT (windowdesactivercompte, button8, "button8");
  GLADE_HOOKUP_OBJECT (windowdesactivercompte, label500, "label500");
  GLADE_HOOKUP_OBJECT (windowdesactivercompte, label547, "label547");
  GLADE_HOOKUP_OBJECT (windowdesactivercompte, label36, "label36");
  GLADE_HOOKUP_OBJECT (windowdesactivercompte, label37, "label37");

  return windowdesactivercompte;
}

