/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowinscription (void);
GtkWidget* create_windowacceuil (void);
GtkWidget* create_window1 (void);
GtkWidget* create_windowfelecitations (void);
GtkWidget* create_windowespaceclient (void);
GtkWidget* create_windowdesactivercompte (void);
