/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_reservationhotel (void);
GtkWidget* create_choixreservation (void);
GtkWidget* create_reservationvol (void);
GtkWidget* create_mesreservations (void);
GtkWidget* create_windowsuppresion (void);
GtkWidget* create_windowmodification (void);
GtkWidget* create_Facture (void);
