/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Reclamation_client (void);
GtkWidget* create_Creer (void);
GtkWidget* create_consulter (void);
GtkWidget* create_employe (void);
GtkWidget* create_principal1 (void);
GtkWidget* create_modifier (void);
GtkWidget* create_reponse (void);
